### ISSUE TITLE
[FEATURE] new ldap functionality

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#112]
changes to the accountWizard since 4.14:
<img width="850" alt="Screenshot 2020-01-15 at 10 30 36" src="https://user-images.githubusercontent.com/2486961/72423233-33a6c680-3784-11ea-92f1-de26dea4c67f.png">

a filter dropdown and a column for the source of a possible conflict

TBD

**Additional context**
LDAP has different levels of integration. all of which are readonly from a cloudstack point of view and which are not distinquished between from the ui at the moment.
Note that the newest, domain level account binding, depends on domain level settings.

**Comment by DaanHoogland** [comment]
this seems to be doubling #39 
note also that the add ldap configuration and ldap configuration list overview are not yet fully functional for this domain level binding:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/2486961/72424728-ba5ca300-3786-11ea-8a4b-ce9d8533635f.png">

**Comment by rhtyd** [comment]
Thanks @DaanHoogland we've the add ldap config form added (but yes without the domainid option)

**Comment by DaanHoogland** [comment]
ok, @rhtyd yet another thing came to mind. there is no ui part for this now, but the truststores might need some consideration as well ;)

**Comment by rhtyd** [comment]
Basic form merged now: https://github.com/apache/cloudstack-primate/pull/116
Future extension can be done on this, after technical preview milestone.

**Comment by DaanHoogland** [comment]
did a quick test but i have some questions. the conflict column is not there.
Lert's discuss after tech preview, as said. i see these as a purely functional issue.

And it seems that domain settings for users are inherited (which is not true on the API, is it?)
This might have serious consequences for the way user-ids might be seen as conflicting.

**Comment by rhtyd** [comment]
@DaanHoogland can you check current Primate and update/advise on this ticket what's missing or needs to be added? Thanks.

**Comment by DaanHoogland** [comment]
ok, @rhtyd I think the two screenprints at the top are the main thing. Doing a full test is sure to give more, but that will take some time, and i'll add tickets for what ever comes up.

**Comment by rhtyd** [comment]
Check/refer https://github.com/apache/cloudstack/pull/3694 TBD later cc @davidjumani

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by rhtyd** [comment]
@davidjumani Primate QA server has a LDAP server now, you can test against that let me know if the requested features are not clear

**Comment by rhtyd** [comment]
PR received, tested; will merge PR after final review
