### ISSUE TITLE
Add instructions on how to avoid system-wide global npm package installation

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#12]
Commands like
```bash
sudo npm install -g @vue/cli webpack eslint
```
will install global dependencies system-wide, which will cause conflicts with files installed by a package manager (rpm, dpkg, ...).

There should be instructions in the README on how to avoid overriding system files.

For example, it's possible to set up a separate runtime directory for node/npm modules and simply run npm from there. This will pick up the local modules instead of those from the system.

**Comment by rhtyd** [comment]
@onitake thanks, we're all new to UI so best practices are likely not known or followed but PRs are welcome.

**Comment by onitake** [comment]
I'll try to write Dockerfile that illustrates how this should work.
So far, I've done my test deployments using Ansible, but having a Primate  container may be very useful for quick rollout.
