### ISSUE TITLE
Bug: For VPC Public IPs, allow selection of tier

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#137]
Old UI-> Network -> VPC -> public IPs -> select public IP that is not static-nat -> Select enable SNAT

For a public IP in VPC, allow selection of tier when enabling SNAT for a public IP:
![Screenshot from 2020-01-28 14-05-31](https://user-images.githubusercontent.com/95203/73247645-5b137f80-41d7-11ea-9e14-0f8353d2b165.png)

**Comment by rhtyd** [comment]
- On load, if public IP belong to a vpc (i.e. record.vpcid will be not null) then show the tiers/network select; and call the listNetworks API to get list of valid tiers/network:
![Screenshot from 2020-01-28 18-38-41](https://user-images.githubusercontent.com/95203/73267577-56fb5800-41ff-11ea-9764-73fa6b8444f1.png)

- On selection, call the list VMs API to list VMs belonging to a specific tier/network and the VPC:
![Screenshot from 2020-01-28 18-39-14](https://user-images.githubusercontent.com/95203/73267583-595db200-41ff-11ea-9d83-87160fcba21b.png)

@RitchieVincent ^^

**Comment by rhtyd** [comment]
@RitchieVincent any update on this fix?

**Comment by RitchieVincent** [comment]
@rhtyd PR submitted here: https://github.com/apache/cloudstack-primate/pull/149
