### ISSUE TITLE
Proxy to API should contain the full path

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#14]
Since commit b0165258f7f43bdd5e79355b1b1c809acc0a9bc7 , the API proxy stopped working for me. Our API server is served over a reverse proxy that doesn't handle /client very well, so we need the proxy forward on /client/api .
I tried several combinations (with/without path etc.) on CS_URL, but none of them work.

Is there a particular reason why this was changed to /client? Is there some CS API that needs to be accessed via /client?

**Comment by rhtyd** [comment]
@onitake with the change, now console proxy etc. all work, that's why it was changed. Can you try the latest? What changes did you have to make, to make it work for you?

**Comment by onitake** [comment]
Ah yes, I forgot about the console proxy. It won't work with only the /client/api redirection.
I don't quite understand with /client doesn't for me. I suspect it's something to do with my management server reverse proxy. Further investigation needed.

On the other hand, this will be obsolete anyway when #21 gets merged.

**Comment by rhtyd** [comment]
Per your comment @onitake as https://github.com/apache/cloudstack-primate/pull/21 is merged, closing this as this gets obsolete per your comment.
