### ISSUE TITLE
[BUG] JS console exception when clicking on Infrastructure > Summary

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#157]
**Describe the bug**
JS console exceptions when clicking on Infrastructure > Summary.

**To Reproduce**
1. Go to Infrastructure > Summary
2. See the following errors in the JS console:

vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object 

found in

---> <ListView> at src/components/view/ListView.vue
       <Resource> at src/views/AutogenView.vue
         <RouteView> at src/layouts/RouteView.vue... (1 recursive calls)
           <Anonymous>
             <ALayoutContent>
               <Anonymous>
                 <ALayout>
                   <Anonymous>
                     <ALayout>
                       <GlobalLayout> at src/components/page/GlobalLayout.vue
                         <BasicLayout> at src/layouts/BasicLayout.vue
                           <ALocaleProvider>
                             <App> at src/App.vue
                               <Root>
							   

vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "dataSource". Expected Array, got Object 

found in

---> <ATable>
       <ListView> at src/components/view/ListView.vue
         <Resource> at src/views/AutogenView.vue
           <RouteView> at src/layouts/RouteView.vue... (1 recursive calls)
             <Anonymous>
               <ALayoutContent>
                 <Anonymous>
                   <ALayout>
                     <Anonymous>
                       <ALayout>
                         <GlobalLayout> at src/components/page/GlobalLayout.vue
                           <BasicLayout> at src/layouts/BasicLayout.vue
                             <ALocaleProvider>
                               <App> at src/App.vue
                                 <Root>
								 
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: data.slice is not a function"

found in

---> <Table>
       <ATable>
         <ListView> at src/components/view/ListView.vue
           <Resource> at src/views/AutogenView.vue
             <RouteView> at src/layouts/RouteView.vue... (1 recursive calls)
               <Anonymous>
                 <ALayoutContent>
                   <Anonymous>
                     <ALayout>
                       <Anonymous>
                         <ALayout>
                           <GlobalLayout> at src/components/page/GlobalLayout.vue
                             <BasicLayout> at src/layouts/BasicLayout.vue
                               <ALocaleProvider>
                                 <App> at src/App.vue
                                   <Root>

vue.runtime.esm.js?2b0e:1888 TypeError: data.slice is not a function
    at VueComponent.getLocalData (Table.js?372e:1026)
    at VueComponent.getCurrentPageData (Table.js?372e:975)
    at VueComponent.renderTable (Table.js?372e:1079)
    at children (Table.js?372e:1154)
    at Proxy.render (LocaleReceiver.js?e5cd:44)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.run (vue.runtime.esm.js?2b0e:4554)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)

**Expected behavior**
There should be no exceptions.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome 
 - Version 80.0.3987.100 (Official Build) (64-bit)

**Additional context**
Once triggered, the problem leads to similar exceptions when clicking on other UI sections.

**Comment by rhtyd** [comment]
Fixed and not reproducible on latest master, please confirm and close @vladimirpetrov

**Comment by vladimirpetrov** [comment]
The issue has been fixed.
