### ISSUE TITLE
[BUG] VM Settings should be read-only if the VM is running

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#161]
**Describe the bug**
In the old UI, VM settings cannot be modified if the VM is running. We need to add this restriction to Primate as well.

**To Reproduce**
1. Go to Compute > Instances > select a running instance > settings
2. Try to add/modify/remove a setting.

**Expected behavior**
You should not be allowed to modify VM settings while the VM is running.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chromer
 - Version: 80.0.3987.100 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Assigned to @davidjumani
