### ISSUE TITLE
[BUG] Group action buttons don't work properly (Events, Alerts, VM)

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#162]
**Describe the bug**
The delete/archive event button has very funny behavior. If no check box is selected it still deletes/arhives the top item, which is not very obvious. The selection boxes seem to be ignored, but still sometimes they are deselected after archiving (deleting) of event.

Notes by @rhtyd 
Group action buttons need to be supported for vm, event and alert views.

**To Reproduce**
1. Go to 'Events'.
2. Click on the 'Delete' or 'Archive' event icon.
3. Inspect the result.
4. Mark some (or all) of the events (check the selection boxes), then click again on the 'Delete' or 'Archive' event icon.

Result: The top event is deleted (archived), regardless of the checked boxes and sometimes they are deselected.

**Expected behavior**
Exactly and only the marked events must be deleted/archived.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome 
 - Version: 80.0.3987.106 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
Test cases:
- Group action for events and alerts and instance

**Comment by rhtyd** [comment]
I'm moving group actions to 1.0/GA. Will look into individual event/alert actions for tech preview.

**Comment by rhtyd** [comment]
Another note: https://github.com/apache/cloudstack-primate/pull/424/files to be checked against old UI and added.

**Comment by rhtyd** [comment]
With @shwstppr

**Comment by rhtyd** [comment]
PR received

**Comment by rhtyd** [comment]
Fixed in 750ea60696aefa0b33913d9e195f37b51f24ac4c
