### ISSUE TITLE
[BUG] Wrong pagination on Storage > Volumes

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#164]
**Describe the bug**
Pagination on Storage > Volumes page shows only the first 10 items and hides the fact you have more until you explicitly set 20/40/80/100 items per page.

**To Reproduce**
1. Go to 'Storage > Volumes' page and make sure you have more than 10 items there
2. Look at the pagination line - it says you have only 10 items and you cannot go to the next page. Refreshing the page or logging out/in does not help.
3. Change the setting to 20 (or more) items per page - now everything looks better but still there is no box for going to a direct page. If you change it back to 10 though, the problem is again there.

**Expected behavior**
The pagination should work properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/74722384-7e16d980-5241-11ea-9cdb-3ed36c0a8ec5.png)
![image](https://user-images.githubusercontent.com/12384665/74722528-bfa78480-5241-11ea-95ea-27e3d73b980b.png)
Both screenshots are with equal number of items, only the pagination settings are different.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.106 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Issue fixed in https://github.com/apache/cloudstack/pull/3894, tested on http://primate-qa.cloudstack.cloud:8080/client/master
