### ISSUE TITLE
[BUG] Storage > Volumes > Resize volume - wrong dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#165]
**Describe the bug**
The Storage > Volumes > Resize volume dialog allows to enter custom volume, instead of using current disk offerings.

**To Reproduce**
1. Go to a volume in Storage > Volumes and click on the 'Resize' icon.
2. Look at the dialog

**Expected behavior**
This dialog should provide a drop-down menu with the current disk offerings.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/74724321-c4ba0300-5244-11ea-8089-1cde6eba86b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.106 (Official Build) (64-bit)

**Additional context**
Difference with the old UI.

**Comment by rhtyd** [comment]
Assigned to @Pearl1594

**Comment by rhtyd** [comment]
@vladimirpetrov fixed please re-review

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
