### ISSUE TITLE
Sorting should be global not per page

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#168]
**Describe the bug**
Currently, if you have more than one page and sort some of the columns, only the results in that particular page are sorted - like there are no other items. This is not the typical UI behavior.

**To Reproduce**
1. Go to a grid, containing a lot of element (multiple pages)
2. Sort by some column and look at the result

**Expected behavior**
The sorting must be applied for all items, not only for this particular page.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov This is not possible, would require backend change. The sorting behaviour is same as in old UI. I've marked it as an enhancement.

**Comment by rhtyd** [comment]
@vladimirpetrov I'm closing this as `won't fix` as Primate cannot fix this without the backend API allowing sorting of all items. The issue needs to be raised/fixing at https://github.com/apache/cloudstack thanks.
