### ISSUE TITLE
Missing eslint peer dependencies

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#17]
I found some more dependencies that are missing:
* eslint-plugin-import
* eslint-plugin-node
* eslint-plugin-promise
* eslint-plugin-standard

Without these, the build step will fail.

**Comment by rhtyd** [comment]
@onitake Did you run `npm install` on primate, after installing global packages - `sudo npm install -g @vue/cli webpack eslint`

**Comment by onitake** [comment]
Yes, I did. But this only installs the tools globally and not the peer dependencies. Those need to be added to the package.json.

**Comment by onitake** [comment]
When the deps are installed, eslint throws a ton of errors. I'll open a separate issue for that.

**Comment by rhtyd** [comment]
Thanks for sharing, do you know (or have figured) how to fix your issues @onitake ?

**Comment by onitake** [comment]
#19 now includes fixes for the lint errors.
