### ISSUE TITLE
[BUG] Selected instance actions difference between old and new UI

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#173]
**Describe the bug**
Here are the differences between the old and new UI:

| Running instance - old UI | Running instance - Primate UI |
|---------------------------|-------------------------------|
| Stop instance | Stop instance |
| Reboot instance | Reboot instance |
| Take VM snapshot | Create VM snapshot |
| ~~Take VM volume snapshot~~ | |
| Assign VM to backup offering | |
| Destroy instance | Destroy instance |
| Reinstall VM | Reinstall VM |
| Attach ISO | Attach ISO |
| Reset password | |
| Migrate instance to another host | Migrate instance to another host |
| Change service offering | |
| Reset SSH Key Pair | |
| View console | View console |
| | Update VM |
| | Scale VM |

Probably 'Scale VM' could be a replacement of 'Change service offering' - they are quite similar. But still this could be confusing for the current users. Actually, 'Scale VM' has one additional field 'Details' which I'm not really sure how to use.

| Stopped instance - old UI | Stopped instance - Primate UI |
|---------------------------|-------------------------------|
| Start instance | Start VM |
| Take VM snapshot | |
| ~~Take VM volume snapshot~~ | |
| Assign VM to backup offering | |
| Destroy instance | Destroy instance |
| Reinstall VM | Reinstall VM |
| Change affinity | Change affinity |
| Edit | Update VM |
| Attach ISO | Attach ISO |
| Reset password | Reset instance password |
| Migrate instance to another host | Migrate instance to another host |
| Change service offering | Change service offering |
| Reset SSH Key Pair | Reset SSH Key |
| Assign instance to another account | Assign instance to another account |
| | Scale VM | 

I'm not sure if some of these differences are intended but I do feel like there's something wrong here.

**To Reproduce**
1. Go to 'Compute > Instances > selected instance'
2. Look at the action buttons and compare with the old UI for running and stopped VM.

**Expected behavior**
There should be no missing actions in the Primate UI - only improvements if any.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by shwstppr** [comment]
Looking into this one

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please re-test against master. I've removed the `VM volume snapshot` action on purpose, this button shouldn't exist for VM view; if we need that please log another ticket that we can target for GA/1.0. Thanks.

**Comment by rhtyd** [comment]
ping @vladimirpetrov

**Comment by vladimirpetrov** [comment]
Two actions are still missing in Primate UI, compared to the old UI (running instance):
- Reset password (could be hidden because my VM was created without password enabled, which would be different behavior than the old UI)
- Reset SSH Key pair

**Comment by shwstppr** [comment]
@vladimirpetrov looking at them cc @rhtyd

**Comment by rhtyd** [comment]
@vladimirpetrov please re-test latest master and close this.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
