### ISSUE TITLE
[BUG] Network > Security groups: Search not working properly

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#174]
**Describe the bug**
Search is not working for some strings, will investigate further

**To Reproduce**
1. Go to 'Network > Security groups'
2. Create a new security group called 'TestSecGroup'
3. Now try to search by string 'Sec'
4. See the result

**Expected behavior**
Only groups containing the string 'Sec' must be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/74951725-aef53b00-5408-11ea-9c94-2f98845a8aec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
I guess it's not related to the current page, needs more investigation.

**Comment by rhtyd** [comment]
@vladimirpetrov it's because the search string searches both the name and description, if you try to search only 'Test' you'll get one item in the list. The 'Group' and 'Sec' are in the description of other security groups.

**Comment by vladimirpetrov** [comment]
@rhtyd Ok, I agree about the previous example, but what could be the reason for this:

![image](https://user-images.githubusercontent.com/12384665/75028005-27f79f80-54a8-11ea-88f9-710bb0416ac0.png)
