### ISSUE TITLE
[BUG] Identify and access > Users > Add user - duplicated password field

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#175]
**Describe the bug**
There are two equal password fields in the 'Identify and access > Users > Add user' dialog - the second one simply mirrors the keystrokes from the first. 

**To Reproduce**
1. Go to 'Identify and access > Users' and click 'Add user'
2. Enter something in the first password field - the keystrokes are mirrored in both password fields.

**Expected behavior**
There must be another independent 'Confirm password' field.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75016794-7307b780-5494-11ea-81ba-1d2937b89c9c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by borisstoyanov** [comment]
Duplicated by #292

**Comment by rhtyd** [comment]
Tested, merged the PR
