### ISSUE TITLE
[BUG] Identify and access > Users > selected user > copy secret key not working properly

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#176]
**Describe the bug**
When you click on the button 'Copy secret key' in 'Identify and access > Users > selected user' screen, it actually copies the API key.

**To Reproduce**
1. Go to 'Identify and access > Users > selected user' 
2. Make sure you have generated API and secret keys and click on the 'Copy secret key' icon.
3. Now paste is somewhere and take a look - it's actually the API key, not the secret.

**Expected behavior**
Correct behavior is to copy the secret key in the clipboard, not the API key.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75017726-58364280-5496-11ea-8a45-ef5571f885a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov please confirm and close against latest master

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
