### ISSUE TITLE
[BUG] Identify and access > Users > selected user > Change password does not verify the old password

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#177]
**Describe the bug**
'Identify and access > Users > selected user > Change password' dialog has a 'Current password' field but it's not mandatory nor it's ever verified if that's really the current password.

**To Reproduce**
1. Go to 'Identify and access > Users > selected user'
2. Click on 'Change password'
3. Enter a new password in the 'Password' field and a wrong password in the 'Current password' field.
4. The password has been changed even though the current password was wrong.

**Expected behavior**
The password change should not be allowed without entering correct current password.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by borisstoyanov** [comment]
ouch

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close against latest master, thanks. cc @borisstoyanov

**Comment by vladimirpetrov** [comment]
No more 'old password' field so the fix is confirmed. Closing the issue.
