### ISSUE TITLE
[BUG] Identify and access > Accounts - first and last name are not shown in the grid

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#178]
**Describe the bug**
Identify and access > Accounts - first and last name are not shown in the grid

**To Reproduce**
1. Go to 'Identify and access > Accounts' and create a new account, entering first/last name.
2. Click on 'Refresh' and look at the newly created account

**Expected behavior**
First and last name should be visible in the grid.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
I see in the JSON response that the backend is sending this information, we need to show it on the screen.

**Comment by rhtyd** [comment]
According to old UI, we should not show first/last name for accounts but only for users:
![Screenshot from 2020-03-05 13-51-08](https://user-images.githubusercontent.com/95203/75961646-651c5280-5ee8-11ea-8498-fbc16b176947.png)

@vladimirpetrov can you test latest master and verify/close this?

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
