### ISSUE TITLE
[BUG] Identify and access > Accounts > selected account - update account button not working

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#179]
**Describe the bug**
Identify and access > Accounts > selected account - 'update account' button not working

**To Reproduce**
1. Go to 'Identify and access > Accounts' and select an account.
2. Click on the 'Update account' icon - it's not working and messes up the UI, the same page stays no matter what you're clicking.

**Expected behavior**
The 'Edit account' dialog must be shown.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov please test/close this one as well. There was a missing feature I found for which I created a new ticket.

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
