### ISSUE TITLE
Large number of errors from eslint

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#18]
When building primate with eslint installed, a large number of errors are thrown.

Related: #17 

Full log: https://gist.github.com/onitake/d81c435697c023463865e8581d968e11

Excerpt:
```
Module Error (from ./node_modules/eslint-loader/index.js):

/build/src/components/header/HeaderNotice.vue
   64:9   error  Unnecessarily quoted property 'done' found      quote-props
   64:19  error  Unnecessarily quoted property 'icon' found      quote-props
   64:43  error  Unnecessarily quoted property 'style' found     quote-props
   65:9   error  Unnecessarily quoted property 'progress' found  quote-props
   65:23  error  Unnecessarily quoted property 'icon' found      quote-props
   65:42  error  Unnecessarily quoted property 'style' found     quote-props
   66:9   error  Unnecessarily quoted property 'failed' found    quote-props
   66:21  error  Unnecessarily quoted property 'icon' found      quote-props
   66:45  error  Unnecessarily quoted property 'style' found     quote-props
   88:46  error  Unnecessarily quoted property 'jobid' found     quote-props
   92:34  error  ["success"] is better written in dot notation   dot-notation
  103:34  error  ["error"] is better written in dot notation     dot-notation

✖ 12 problems (12 errors, 0 warnings)
  12 errors and 0 warnings potentially fixable with the `--fix` option.
```

These should be addressed.

**Comment by rhtyd** [comment]
Send a PR @onitake or advise how you fixed those errors?

**Comment by onitake** [comment]
I see two ways to "fix" these errors:

1. Apply the suggested fixes - which I'm not sure are safe. JS is a bit outside my domain.
2. Disable eslint.

**Comment by onitake** [comment]
The errors are triggered by the `"@vue/standard"` extension in the `eslintConfig` section in package.json
If I remove that, Primate will build and run fine.

While I think that fixing the errors is better, it shouldn't be necessary to have the build fail because of them.

**Comment by rhtyd** [comment]
I'm unable to reproduce them on latest master @onitake - does it fix to use the eslint4.x version?
```
> npm run lint

> primate@0.1.0 lint /home/rohit/lab/apache/primate
> vue-cli-service lint

 DONE  No lint errors found!
```

**Comment by onitake** [comment]
I tried with eslint 4.0, but it still reported errors. Not sure if this was caused by leftovers or something else. I also did so in a fresh container, so I don't think it was on my host system...

Also, I noticed that when I ran `npm run lint`, it autofixed all minor issues. I only had to change two lines manually.

Also, if you check the previous Travis log for #19 , you can see that it threw the reported lint errors after I added the required dependencies.

**Comment by onitake** [comment]
See https://travis-ci.org/apache/cloudstack-primate/builds/614182897

**Comment by onitake** [comment]
The way I see it, this needs to be fixed either by removing the standard vue rules, or by adopting their coding style.
Even if it works with current modules, the lint errors will come back eventually and cause problems.

**Comment by rhtyd** [comment]
@onitake but latest master seems to be passing lint checks: https://travis-ci.org/apache/cloudstack-primate/builds/614449601

I'll have a look at your PRs this weekend or next week

**Comment by onitake** [comment]
That's correct - because I applied all the fixes that were suggested by the vue/standard lint rules.

It's up to you to decide if you want to adopt the vue.js coding style or simply go with only the essential rules.

So: Please merge either merge #19 or #20 , depending on your preference.

**Comment by onitake** [comment]
Thanks, @rhtyd !
