### ISSUE TITLE
[BUG] Identify and access > Domains > delete domain does not remove it from the tree

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#180]
**Describe the bug**
When you delete a domain in 'Identify and access > Domains' it does not remove it from the tree even though it's actually deleted.

**To Reproduce**
1. Go to 'Identify and access > Domains' and select a domain
2. Click on 'Delete domain' icon and confirm the operations. 
3. Look at the domain tree - it's still there. If you try to click on the deleted domain, it's not shown though.

**Expected behavior**
The deleted domain should be removed from the domain tree.

**Screenshots**
None

**Desktop (please complete the following information):**
- OS: Windows 10 Pro x64
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Bigger refactoring needed, confirmed issue.

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please re-test the domain view tree and list views against old UI, confirm and close this against latest master.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
