### ISSUE TITLE
[BUG] Identify and access > Roles - searching does not work.

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#181]
**Describe the bug**
The search field in 'Identify and access > Roles' does not work.

**To Reproduce**
1. Go to 'Identify and access > Roles'
2. Enter a search string and press the search icon - nothing happens.

**Expected behavior**
The search results should be filtered according to the entered criteria.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75028772-8bce9800-54a9-11ea-8a41-37cdabeef67b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov thanks the issue was inconsistent param used for searching, fixed in master. Please re-test.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
