### ISSUE TITLE
[BUG] Identify and access > Roles > selected role > Rules - unnecessary scroll bars

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#182]
**Describe the bug**
There are scroll bars that are not necessary on the 'Identify and access > Roles > selected role > Rules' screen.

**To Reproduce**
1. Go to 'Identify and access > Roles'
2. Click on a role, then on the 'Rules' tab.

**Expected behavior**
There's no need for scroll bars on this page.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75037437-d6a5db00-54bc-11ea-9c06-6df8d044a506.png)

![image](https://user-images.githubusercontent.com/12384665/75037447-dc032580-54bc-11ea-97b9-0e56b348c243.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov made them automatic now, not show if not necessary. Please retest master.

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
