### ISSUE TITLE
[BUG] Infrastructure > Pods > selected Pod - cannot enable a Pod

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#183]
**Describe the bug**
The button 'Enable Pod' in 'Infrastructure > Pods > selected Pod' doesn't do anything.

**To Reproduce**
1. Go to 'Infrastructure > Pods' and click on a disabled pod.
2. Click the 'Enable Pod' icon - nothing happens.

**Expected behavior**
The 'Enable Pod' button should enable the disabled pod.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by GabrielBrascher** [comment]
@vladimirpetrov what is the CloudStack version that you noticed this issue?

**Comment by vladimirpetrov** [comment]
@GabrielBrascher This is the new CloudStack UI - Primate, which is not released yet, don't worry.

**Comment by rhtyd** [comment]
Fixed now, please review and close @vladimirpetrov master branch.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
