### ISSUE TITLE
[BUG] Identify and access > Accounts > Add Account

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#184]
**Describe the bug**

It is not possible to add the required account name in the Account field
Add Account 'Account' field is a dropdown of existing Accounts - should be plain text entry.

**To Reproduce**
1. Go to _Identify and access > Accounts_
2. Click on '+'
3. Attempt to add a NEW account name

**Expected behavior**
I should be able to type a new account name

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/75111481-3e316700-5632-11ea-9027-bc81a3f0faff.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
@borisstoyanov please test and close if it's confirmed on latest master. Thanks.

**Comment by borisstoyanov** [comment]
Is this add account or add user? 
if it's add account it's looking good now, but the tooltip from the screenshot suggest this is add user under which account, where a drop down sound reasonable. By the way both looking good to me now.

**Comment by borisstoyanov** [comment]
ping @PaulAngus, @rhtyd

**Comment by borisstoyanov** [comment]
Just double-checked with Vladi and it seems good now.
