### ISSUE TITLE
[BUG] Offerings > Disk offerings - invalid zone link if multiple zones are used

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#185]
**Describe the bug**
When a disk offering is assigned to more than one zone, the zone link in the selected offering contains both zone IDs, rendering it invalid.

**To Reproduce**
1. Go to 'Offerings > Disk offerings' and select an offering.
2. Update the offering, adding multiple zones.
3. Now click on the 'Zone' link and see what happens.

**Expected behavior**
Not really sure what's the proper behavior here, probably we don't need this link at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75160560-e45c9a00-5722-11ea-9c1a-6c3bfb6a9ff0.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
It's the same for network offerings.

**Comment by rhtyd** [comment]
@vladimirpetrov please test latest master.

**Comment by vladimirpetrov** [comment]
Zones are names (not IDs) now and non-clickable so the issue is resolved. Closing it.
