### ISSUE TITLE
[BUG] Offerings > Network offerings - the searching is broken

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#186]
**Describe the bug**
An internal server error (500) is generated when trying to search something in 'Offerings > Network offerings'.

**To Reproduce**
1. Go to 'Offerings > Network offerings'
2. Enter a search string and click on the search icon. Here is what happens:

500 Internal server error.
Request Failed
DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT network_offering_view.id, network_offering_view.uuid, network_offering_view.name, network_offering_view.unique_name,
...

**Expected behavior**
The search functionality should work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75169161-c007ba00-5730-11ea-9d37-c5850ca2eb7c.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
This is related to backend env, I'll need to rebuild+deploy DB on the primate-qa server @vladimirpetrov can you verify against other env, where I see working. I can update primate-qa by tomorrow.

**Comment by rhtyd** [comment]
(error seen in the old UI as well, which suppresses it)

**Comment by rhtyd** [comment]
@vladimirpetrov there was a backend bug that I've fixed and sent a PR for ^^, the primate-qa server is now rebuilt with the fix. Please test and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
