### ISSUE TITLE
[BUG] Offerings > Network offerings - change order option is missing 

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#187]
**Describe the bug**
We have an option to change the offerings order in the old UI which we don't have in Primate.

**To Reproduce**
1. Go to 'Offerings > Network offerings' - there is no way to change the offerings order, like in the old UI.

**Expected behavior**
The user should be able to change the network offerings order.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75170177-656f5d80-5732-11ea-8709-78f9a2a83198.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov fixed please re-test master

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
