### ISSUE TITLE
[BUG] Offerings > Network offerings - unclear text field in the 'Edit offering' dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#188]
**Describe the bug**
There is a text field, called 'Availability' in the 'Edit offering' screen (Offerings > Network offerings). It's unclear what should be filled there - it's a drop-down menu in the old UI and it's much better. 

**To Reproduce**
1. Go to 'Offerings > Network offerings', select an offering and click on 'Edit offering'. Look on the 'Availability' text field.

**Expected behavior**
It would be much better if we had a drop-down menu, as in the old UI.

**Screenshots**
Look at the old UI:
![image](https://user-images.githubusercontent.com/12384665/75171508-64d7c680-5734-11ea-89a5-1c9fc8f9be4c.png)

... and the Primate UI:
![image](https://user-images.githubusercontent.com/12384665/75171553-76b96980-5734-11ea-8f59-95e3c1ada7f8.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov please verify master, thanks.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
