### ISSUE TITLE
[BUG] Offerings > VPC offerings - not human-readable service capabilities

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#189]
**Describe the bug**
The service capabilities description is not really human-readable in "Offerings > VPC offerings" - it's just a JSON object.

**To Reproduce**
1. Go to 'Offerings > VPC offerings' and click on a VPC offering. Look at the 'service' label.

**Expected behavior**
The information about the service capabilities should be easy to understand.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75173430-84242300-5737-11ea-8343-52d08281c23b.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
Fixed in master now please re-test and close @vladimirpetrov

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
