### ISSUE TITLE
[BUG] Problems with pagination and search

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#190]
**Describe the bug**
After searching for a string on a n-th page requires additional click to page 1 in order to see the results.

**To Reproduce**
1. Go to 'Configuration > Global settings' and find a settings page, containing the word 'backup'.
2. Type 'backup' in the search field and click on the search icon - the results are empty, even though we have 4 items found. The reason is that we are not moved to the first page of the results.

**Expected behavior**
After a search is performed, the current page in the results must be set to 1.

**Screenshots**
Here is a screen before clicking on 'search':
![image](https://user-images.githubusercontent.com/12384665/75174329-10831580-5739-11ea-8f94-d1168a2ea519.png)

And this is the screen after clicking it:
![image](https://user-images.githubusercontent.com/12384665/75174385-2abcf380-5739-11ea-89a0-1b5f457c8d3b.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
This is valid for all screens which have searching and pagination functionalities.

**Comment by rhtyd** [comment]
@vladimirpetrov thanks good find, please re-test master.

**Comment by vladimirpetrov** [comment]
Confirmed as fixed, closing the issue.
