### ISSUE TITLE
[BUG] Ugly screen after archiving an event

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#191]
**Describe the bug**
After archiving an event the screen is left in undefined state.

**To Reproduce**
1. Go to 'Events' and click on an event
2. Click on 'Archive' and confirm the operation. After it's completed, the screen is left in an undefined state.

**Expected behavior**
After archiving an event, the user should be redirected back to the Events grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75255263-51873280-57ea-11ea-9f5a-1bbd09c8c7d3.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
Deleting event works as expected.

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
