### ISSUE TITLE
[BUG] Projects > Enter token - cancel button is not working properly

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#192]
**Describe the bug**
The cancel button in the 'Enter token' dialog is acting like a browser back button, instead of closing the dialog.

**To Reproduce**
1. Go to 'Projects' and click on the 'Enter token' icon. 
2. Click on the 'Cancel' button - the dialog is not closed, a 'browser back' operation is executed instead.

**Expected behavior**
The dialog must be closed and the operation should be cancelled.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Fixed, @vladimirpetrov please re-test

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
