### ISSUE TITLE
[BUG] Network > VPN Customer Gateway - cannot add tags

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#193]
**Describe the bug**
Nothing happens when you try to add a tag to a selected VPN Customer Gateway.

**To Reproduce**
1. Go to 'Network > VPN Customer Gateway' and click on a gateway
2. Try to add a tag - it's not saved.

**Expected behavior**
It should be possible to add and delete tags.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
The old UI doesnot allow tags on vpn customer gateway so Primate shouldn't either as it's not supported.
@vladimirpetrov please test and close against latest master.

**Comment by vladimirpetrov** [comment]
Confirmed, closing the issue.
