### ISSUE TITLE
[BUG] Missing functionality - search in settings

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#194]
**Describe the bug**
There is a search functionality in the old UI for all the settings tabs, which is not present in Primate UI.

**To Reproduce**
1. Go to 'Compute > Instances' and select an instance (or in Images > Templates, for example)
2. Click on 'Settings' tab - there is no way to search there, as in the old UI

**Expected behavior**
It's good to have this functionality in Primate as well - wherever we have a 'Settings' tab.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
This is valid for all 'Settings' tabs.

**Comment by rhtyd** [comment]
@vladimirpetrov in old UI the search bar does not work, that's why the search bar for settings for VMs and templates was not implemented. Kindly confirm and close this.

**Comment by vladimirpetrov** [comment]
Ok, I can confirm this, closing the issue.
