### ISSUE TITLE
[FEATURE] Domain Admins Should be able to see the usage of resources vs limits

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#195]
**Is your feature request related to a problem? Please describe.**

A domain admin should be able to see how much of their 'allocation' their users have consumed so that they know when to 'purchase' more.

**Describe the solution you'd like**

Probably this should be in the dashboard view like infra for admins, but scoped only to their own domain(s)

**Describe alternatives you've considered**

**Additional context**

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/pull/203

**Comment by rhtyd** [comment]
Fixed by https://github.com/apache/cloudstack-primate/pull/203
