### ISSUE TITLE
[BUG] Missing data in Storage > volumes > selected volume

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#196]
**Describe the bug**
The data presented in Storage > volumes > selected volume is less than in the old UI.

**To Reproduce**
1. Go to 'Storage > volumes', look at the data and then click on a volume
2. Compare the volume information with the old UI
The following details are missing in the Primate UI:
- Storage type
- Cluster (ID)
- Cluster name
- VM ID
- Storage (name). This grid column is always empty in Primate UI.

**Expected behavior**
At least the same details should be present in the Primate UI as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75697531-e63fd380-5cb5-11ea-9586-41e640ba92f2.png)

![image](https://user-images.githubusercontent.com/12384665/75697591-fd7ec100-5cb5-11ea-99d6-eb858f3e7f0c.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov this needs a backend fix, thanks for finding. I'll raise a PR upstream today.
The VM ID is indeed returned and the VM is shown on the left side.

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack/issues/3938

**Comment by rhtyd** [comment]
cc @shwstppr this may require changes in the backend if the listVolumesMetrics apis does not returnt the required keys

**Comment by shwstppr** [comment]
Latest master shows details for cluster, storage, zone, etc for volumes attached to a VM
![Screenshot from 2020-03-27 16-23-44](https://user-images.githubusercontent.com/153340/77749387-f4300c80-7047-11ea-9660-69d7dfe63a70.png)
![Screenshot from 2020-03-27 16-23-58](https://user-images.githubusercontent.com/153340/77749128-81bf2c80-7047-11ea-91e3-75bbc2368dc4.png)
Some missing fields added with PR: #268 
cc @vladimirpetrov

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
