### ISSUE TITLE
Missing feature: Not way to update resource limits for account and domains.

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#197]
Missing feature:
- Go to IAM->account -> no way to edit/update the resource count/limits (as root admin).
- Go to IAM->domain -> no way to edit/update the resource count/limits (as root admin).
Note: the feature is only for the root admin, similar to the resource limits tab for projects. On updation it calls the `updateResourceLimit` API.

Here's what is looks in old UI:
![Screenshot from 2020-03-06 13-46-48](https://user-images.githubusercontent.com/95203/76065117-fb1bb000-5fb0-11ea-9a8c-de9dc769e86d.png)

Example for the same in old UI for domains:
![Screenshot from 2020-03-06 13-53-56](https://user-images.githubusercontent.com/95203/76065617-fa374e00-5fb1-11ea-80d6-73361b823585.png)

The similar feature wrt Projects looks like this in Primate:
![Screenshot from 2020-03-06 13-50-29](https://user-images.githubusercontent.com/95203/76065341-78dfbb80-5fb1-11ea-8321-ed707a5a0627.png)

One way to implement this could be to refactor views/project/ResourcesTab.vue and make this tab component re-usable for both projects, accounts and domains.

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel can you pick this as the next task?
It's a similar feature you had implemented for projects which allowed admins to specify the resource count/limits for a project. We want the same feature as a tab for accounts and domains.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I've completed this task in PR https://github.com/apache/cloudstack-primate/pull/203. Please assign a new task to me.

**Comment by rhtyd** [comment]
Duplicate.
