### ISSUE TITLE
[BUG] Edit VPN Customer Gateway - current values must be populated in the fields

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#198]
**Describe the bug**
The current values are not populated in the 'Edit VPN Customer Gateway' dialog making it almost unusable. 

**To Reproduce**
1. Go to 'Network > VPN Customer Gateway'
2. Click on a gateway and then on the icon 'Edit VPN Customer Gateway' - the current values are not populated and most fields are mandatory so you have to enter almost each parameter by hand.

**Expected behavior**
Current values must be populated in the fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/75994684-ff3dc400-5f03-11ea-8cda-cf91abd8cf46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close, this is now done system wide for all auto-generated edit forms.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
