### ISSUE TITLE
[BUG] Different list of template images in old and new UI

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#199]
**Describe the bug**
The old and the Primate UI show different list of template images.

**To Reproduce**
1. Go to 'Images > Templates' in the old UI and then in the Primate UI. Note the differences.

**Expected behavior**
Both old and new UI must show equal number of template images.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76000137-efc27900-5f0b-11ea-863b-c3f75b9c6aeb.png)

Primate UI:
![image](https://user-images.githubusercontent.com/12384665/76000195-0799fd00-5f0c-11ea-8a55-5fa3006592e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Not really sure when this happens, will investigate further.

**Comment by borisstoyanov** [comment]
Looks like templates of type SYSTEM are filtered out.

**Comment by rhtyd** [comment]
Template filtering options will be added in 1.0/GA

**Comment by rhtyd** [comment]
Related issue; https://github.com/apache/cloudstack/issues/4041

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
