### ISSUE TITLE
[BUG] Infrastructure > Hosts: Missing functionality - configure HA

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#200]
**Describe the bug**
There must be an option to configure HA from Infrastructure > Hosts, as in the old UI.

**To Reproduce**
1. Go to 'Infrastructure > Hosts' and click on a host.
2. Look at the possible actions - there is no 'Configure HA', as in the old UI.

**Expected behavior**
There must be a 'Configure HA' button there.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76066815-fb0eb680-5f96-11ea-9eaf-3d9e377dd567.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close

**Comment by vladimirpetrov** [comment]
It's not working properly, the given choice in the 'HA Provider' drop-box seems wrong and the operation fails, see the difference between the old and the Primate UI:

Old UI:
![image](https://user-images.githubusercontent.com/12384665/77771715-bafb9a80-704f-11ea-94b6-f949d5b8bae9.png)

Primate UI:
![image](https://user-images.githubusercontent.com/12384665/77771811-dcf51d00-704f-11ea-99cd-28624ae3fa34.png)

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
