### ISSUE TITLE
[BUG] Missing functionality - Infrastructure > System VMs > Get diagnostic data

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#201]
**Describe the bug**
The action 'Get diagnostic data' from the System VMs screen is missing in Primate UI.

**To Reproduce**
1. Go to 'Infrastructure > System VMs' and click on a system VM
2. Look at the possible actions - there's no 'Get diagnostic data'.

**Expected behavior**
There should be a button 'Get diagnostic data' as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76098145-9ae93600-5fd1-11ea-8d75-371823458e81.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Probably related to #202

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please test and close against master, thanks.

**Comment by vladimirpetrov** [comment]
There is a button now and it says it completes the task successfully but does not show the URL to download the diagnostic data.

![image](https://user-images.githubusercontent.com/12384665/79841881-b6ad6d80-83c0-11ea-9828-27eac25df4a1.png)

as it did in the old UI, for example:

![image](https://user-images.githubusercontent.com/12384665/79841835-aa291500-83c0-11ea-9e55-c3d922919477.png)

**Comment by rhtyd** [comment]
@shwstppr please see ^^ did you use a `response` param?

**Comment by shwstppr** [comment]
@rhtyd please have look on new PR when possible

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov PR merged, please re-test against master. This will require a real env (say kvm etc), we may get unexpected results for simulator.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
