### ISSUE TITLE
[BUG] Missing functionality - Infrastructure > Virtual routers > Get diagnostic data

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#202]
**Describe the bug**
The action 'Get diagnostic data' from the Virtual routers screen is missing in Primate UI.

**To Reproduce**
1. Go to 'Infrastructure > Virtual routers' and click on a virtual router
2. Look at the possible actions - there's no 'Get diagnostic data'.

**Expected behavior**
There should be a button 'Get diagnostic data' as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76098842-df290600-5fd2-11ea-90fc-bf4886267bb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Probably related to #201

**Comment by borisstoyanov** [comment]
@rhtyd What is the cloudstack version we're aiming to be feature parity with?

**Comment by rhtyd** [comment]
@borisstoyanov we started with 4.13, we'll try and see if we can support 4.14 as well.

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please test and close against master, thanks.

**Comment by vladimirpetrov** [comment]
There is a button now and it says it completes the task successfully but does not show the URL to download the diagnostic data:

![image](https://user-images.githubusercontent.com/12384665/79842242-31768880-83c1-11ea-9d74-b1278e6ba1f6.png)

like it did in the old UI, for example:

![image](https://user-images.githubusercontent.com/12384665/79842319-51a64780-83c1-11ea-8cc8-ea9c70dbc1e0.png)

**Comment by rhtyd** [comment]
@shwstppr please see ^^

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
