### ISSUE TITLE
[BUG] Missing functionality - Offerings > Backup offerings

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#205]
**Describe the bug**
The functionality we had in the old UI is missing in Primate UI - Offerings > Backup offerings.

**To Reproduce**
1. Go to 'Offerings' and look at the sub-sections. There is no 'Backup offerings' there.

**Expected behavior**
Offerings > Backup offerings functionality must be present, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76199187-16c4c780-61f8-11ea-8ee0-3c113f416cb2.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
I'll reopen another one listing all missing features around backup feature.

**Comment by rhtyd** [comment]
Moved here: https://github.com/apache/cloudstack-primate/issues/253
