### ISSUE TITLE
[BUG] Missing functionality - Global Settings > Baremetal Rack Configuration

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#206]
**Describe the bug**
The functionality we had in the old UI is missing in Primate UI - Global Settings > Baremetal Rack Configuration.

**To Reproduce**
1. Go to 'Global Settings' and look at the sub-sections. There is no 'Baremetal Rack Configuration' there.

**Expected behavior**
Global Settings > Baremetal Rack Configuration functionality must be present, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76204886-e2560900-6201-11ea-9d0d-e24e9770ed6b.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Known limitation, https://github.com/apache/cloudstack-primate/projects/1
We'll do this after the tech preview - you may keep this open or close it as we're already aware of this.

**Comment by vladimirpetrov** [comment]
Since it's a known limitation, let's close this to avoid confusion.
