### ISSUE TITLE
[BUG] Configuration > Hypervisor capabilities - missing Max guest limit data

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#207]
**Describe the bug**
The values for Max guest limit are missing in the 'Global Settings > Hypervisor capabilities' grid.

**To Reproduce**
1. Go to 'Configuration > Hypervisor capabilities' and look the data presented there.

**Expected behavior**
The values for 'Max guest limit' must be present in the grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76205739-85f3e900-6203-11ea-8bb6-5eac72fe91cf.png)

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 18.04 LTS
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close; fixed in https://github.com/apache/cloudstack-primate/pull/234

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
