### ISSUE TITLE
[BUG] Clicking on Quota > Summary > selected account does not open the account quota

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#209]
**Describe the bug**
You have no way to add credits to the account's quota.

**To Reproduce**
1. Go to 'Quota > Summary', then click on some of the accounts - you are redirected to the 'Identity and Access > Accounts' page.

**Expected behavior**
An account quota screen should be opened.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Consolidated here: https://github.com/apache/cloudstack-primate/issues/295
