### ISSUE TITLE
[BUG] Missing calendar functionality in Quota > Tariff

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#210]
**Describe the bug**
On the 'Quota > Tariff' page, we have a calendar picker functionality in the old UI which is missing in Primate UI. This picker allows to check the tariff values for a particular date.

**To Reproduce**
1. Go to 'Quota > Tariff' - there is no date picker functionality.

**Expected behavior**
There must be a date picker, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76306088-f61b7100-62ce-11ea-8d6f-67124e9ba77c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Consolidated here: https://github.com/apache/cloudstack-primate/issues/295
