### ISSUE TITLE
[BUG] Quota > Tariff - value cannot be changed

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#211]
**Describe the bug**
There's no way to change a tariff value in Primate UI.

**To Reproduce**
1. Go to 'Quota > Tariff' - no way to change the tariff value.

**Expected behavior**
There must be a button for changing a tariff's value.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76306771-2adbf800-62d0-11ea-9ce5-2202125e9127.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by borisstoyanov** [comment]
@vladimirpetrov is there a way to change that in the old UI? Sorry I'm not aware.

**Comment by rhtyd** [comment]
Consolidated here: https://github.com/apache/cloudstack-primate/issues/295
