### ISSUE TITLE
[BUG] Quota > Email template - search is not working

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#212]
**Describe the bug**
The search functionality in 'Quota > Email template' is not working.

**To Reproduce**
1. Go to 'Quota > Email template' and search for some string.

**Expected behavior**
The search should filter the results according to the criteria.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76307304-41cf1a00-62d1-11ea-86c1-8d25251cae3f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
This functionality doesn't seem to work in the old UI as well - but it's still a bug.

**Comment by rhtyd** [comment]
Consolidated here: https://github.com/apache/cloudstack-primate/issues/295
