### ISSUE TITLE
[BUG] Missing Instance/VM 'Filter by' functionality

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#213]
**Describe the bug**
It's impossible to filter by owned, running, stopped or destroyed instances, as in the old UI.

**To Reproduce**
1. Go to 'Compute > Instances' - the 'Filter by' functionality is missing.

**Expected behavior**
There should be a way to filter by owned, running, stopped or destroyed instances, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76321501-c7ab8f00-62ea-11ea-9feb-11ab4d36df48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
This filtering is missing also in the following pages:
- Templates

**Comment by rhtyd** [comment]
Add filter by state in the state column for vm etc. cc @shwstppr (ListView component)
