### ISSUE TITLE
[BUG] Compute > Instances - Missing extended search functionality

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#214]
**Describe the bug**
There is an extended search functionality in the old UI which is missing in the Primate UI.

**To Reproduce**
1. Go to 'Compute > Instances' - the extended search functionality is missing.

**Expected behavior**
There must be extended search option, like in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76322600-4523cf00-62ec-11ea-84f0-f87a4b11e4f3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
The same is valid for the following screens:
- Storage > Volumes
- Storage > Snapshots
- Storage > VM Snapshots
- Network > Guest networks
- Network > VPC
- Network > VPN Customer Gateway
- Templates 
- Templates - ISO
- Events
- Projects

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/pull/235

**Comment by rhtyd** [comment]
PR received
