### ISSUE TITLE
[BUG] Missing functionality - Storage > Backups

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#215]
**Describe the bug**
The functionality we had in the old UI is missing in Primate UI - Storage > Backups

**To Reproduce**
1. Go to 'Storage' and look at the sub-sections in the drop-down - there's no 'Backups' there.

**Expected behavior**
Storage > Backups functionality must be present, as in the old UI.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76429102-3f46f000-63b7-11ea-8aee-fea30cc6e2b4.png)

Primate UI:
![image](https://user-images.githubusercontent.com/12384665/76429357-99e04c00-63b7-11ea-9742-65413bbb34d6.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
More issues logged https://github.com/apache/cloudstack-primate/issues/253
