### ISSUE TITLE
[BUG] Missing functionality - Templates > ISO - change order

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#216]
**Describe the bug**
In the old UI there is the option to change the order in 'Template > ISO' page, which is missing in Primate UI.

**To Reproduce**
1. Go to 'Template > ISO' and look at the grid - no way to change the list order.

**Expected behavior**
There must be an option to change the order of the items, as in the old UI.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76432345-86cf7b00-63bb-11ea-9d85-ceeae4184310.png)

New UI:
![image](https://user-images.githubusercontent.com/12384665/76432243-5e478100-63bb-11ea-80e3-c1449e804c71.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov back with you, the feature is not supported in old UI ( you can try to move things up and down, then refresh order will not be changed).

**Comment by vladimirpetrov** [comment]
Ok, it really doesn't work, closing the issue.
