### ISSUE TITLE
[BUG] Missing functionality - View event timeline

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#218]
**Describe the bug**
There is a functionality showing the timeline (all related events) for a particular event, which is not present in Primate UI.

**To Reproduce**
1. Go to 'Events' - no way to see the timeline for a particular event.

**Expected behavior**
There should be a way to see the timeline for a particular event.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76503998-7ec11b00-644f-11ea-8a4e-ae0ca4d8b023.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
