### ISSUE TITLE
[BUG] In project: Infrastructure > Virtual routers - all routers are shown

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#222]
**Describe the bug**
When a project is selected, all routers are shown, instead of only these belonging to it.

**To Reproduce**
1. Select a project that have only some of the virtual routers attached to it.
1. Go to 'Infrastructure > Virtual routers' and look at the results - all vitrual routers are shown, even these not attached to the current project.

**Expected behavior**
Only routers that belong to the current project must be shown .

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76642284-94236b80-655b-11ea-97ea-7529a0474d7a.png)

New UI:
![image](https://user-images.githubusercontent.com/12384665/76642341-b2896700-655b-11ea-8920-1f75722a86c7.png)

**Desktop:**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
The infrastructure page should show all the routers, for project's network specific routers one can go to (in a project) -> Network -> VRs.

**Comment by vladimirpetrov** [comment]
After a discussion with @rhtyd we agreed that this is actually a planned change in the functionality so it's not a bug and I'll close the issue now.
