### ISSUE TITLE
[BUG] Infrastructure > CPU sockets - hypervisors are not properly shown

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#223]
**Describe the bug**
In Infrastructure > CPU sockets screen, all the hypervisors are shown as 'simulator'.

**To Reproduce**
1. Go to 'Infrastructure > CPU sockets' and look at the data grid.

**Expected behavior**
Different supported hypervisors must be shown here.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76642790-8e7a5580-655c-11ea-8f29-bbb2df7b698f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
cc @shwstppr - please see

**Comment by rhtyd** [comment]
New listview only component needed for this
