### ISSUE TITLE
[BUG] Missing functionality - Service offerings > VPC offerings - change order

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#224]
**Describe the bug**
In the old UI there is the option to change the order in 'Template > ISO' page, which is missing in Primate UI.

**To Reproduce**
1. Go to 'Service offerings > VPC offerings' and look at the grid - no way to change the list order.

**Expected behavior**
There must be an option to change the order of the items, as in the old UI.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76644012-d8fcd180-655e-11ea-8275-bbb2f7860ea7.png)

New UI:
![image](https://user-images.githubusercontent.com/12384665/76644041-e7e38400-655e-11ea-8578-d6cce949081b.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Fixed now https://github.com/apache/cloudstack-primate/commit/c9c7cc3cf40e88c631252cc1971f1c10516989a0

**Comment by rhtyd** [comment]
@vladimirpetrov please review latest master

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
