### ISSUE TITLE
[BUG] Storage > Volumes > selected volume showing more actions than old UI

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#225]
**Describe the bug**
The Primate UI has more actions in 'Storage > Volumes > selected volume' than the old UI. Here are the actions that are present only in Primate:
- Detach volume
- Migrate volume
- Download volume
- Create template from volume
- Delete volume

**To Reproduce**
1. Go to 'Storage > Volumes' and click on a volume. Look at the possible actions.

**Expected behavior**
The Primate UI should have the same actions as in the old UI.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/76778970-53be2a80-67b3-11ea-8735-41c82cb57b09.png)

New UI:
![image](https://user-images.githubusercontent.com/12384665/76779030-66d0fa80-67b3-11ea-8c6c-890042ca0b02.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test and close against master, thanks.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
