### ISSUE TITLE
[BUG] Storage > VM Snapshots - display name

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#229]
**Describe the bug**
VM Snapshot's 'Name' attribute is shown instead of 'Display name', as it is in the old UI.

**To Reproduce**
1. Go to 'Storage > VM Snapshots', look at a snapshot, then click on it to see the details.

**Expected behavior**
'Display name' must be shown in the Storage > VM Snapshots screen, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76834109-421d6700-6835-11ea-9e6a-07f69d009b1f.png)

![image](https://user-images.githubusercontent.com/12384665/76834295-932d5b00-6835-11ea-9f12-d892a57f8aa4.png)

Old UI:
![image](https://user-images.githubusercontent.com/12384665/76834384-c2dc6300-6835-11ea-98a8-b83b55629dae.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by shwstppr** [comment]
Working on this cc @rhtyd

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close
Fixed in https://github.com/apache/cloudstack-primate/pull/232

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
