### ISSUE TITLE
[BUG] Storage > VM Snapshots - parent name

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#230]
**Describe the bug**
The parent name in 'Storage > VM Snapshots' is shown as id, instead of human-readable name.

**To Reproduce**
1. Go to 'Storage > VM Snapshots' and click on a snapshot, which have a parent. Look at the details.

**Expected behavior**
Parent name must be human-readable, not id.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76843510-8f550500-6844-11ea-8d8a-b553d2b213b5.png)

Old UI:
![image](https://user-images.githubusercontent.com/12384665/76843567-a98ee300-6844-11ea-8927-a2e9001f226c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None.

**Comment by shwstppr** [comment]
Looking into this, cc @rhtyd

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close
Fixed in https://github.com/apache/cloudstack-primate/pull/232

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
