### ISSUE TITLE
[BUG] Domain admin: non-working links (insufficient rights)

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#233]
**Describe the bug**
The following links could generate (if the domain admin lacks the required permissions) a 404 (not found) or 500 (Internal server error) errors - template, zone, host, cluster, pod, domain, account, compute offering, storage pool.

**To Reproduce**
1. Log in as domain admin, go to 'Network > Guest networks' and click on a network. Then try the 'Zone' and 'Domain' links - first returns '404' (Not found) error and the second - '500' (Internal server error).

**Expected behavior**
All links should work or be hidden (if the permissions are insufficient).

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76876043-09ec4780-687a-11ea-8200-1f9434366a64.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Affected areas:
> Instances > selected instance - 
- template - 404
- host - 404
- zone - 404

> Volumes - selected
- compute offering - 404
- storage pool - 404
- cluster - 404
- pod - 404
- zone - 404

> Snapshots - selected
- zone - 404

> VM Snapshots - selected
- zone - 404

> Guest networks
- zone - 404
- domain - 500

> Images > Templates - selected
- Zone 404
- account - 500
- domain - 500

> Images > ISOs - selected
- account - 500
- domain - 500

> Offerings > System Offerings - 404

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test and close against latest master.
