### ISSUE TITLE
[BUG] Domain admin: Accounts > selected - settings should not be visible

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#237]
**Describe the bug**
When logged as domain admin, clicking on 'Identify and Access > Accounts > selected - settings' generates an error message. The same is with Domains settings.

**To Reproduce**
1. Log in as domain admin, go to 'Identify and Access > Accounts', click on account and then on the 'Settings' tab.
2. Go to 'Identify and Access > Domains', click on the 'Settings' tab.

**Expected behavior**
'Settings' tab should not be visible when logged as domain admin, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76967910-b8eb5a80-6930-11ea-8c18-4672c7a384c4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Even simple click on a domain generates an error message.

**Comment by rhtyd** [comment]
cc @shwstppr review/test against old UI for cases when domain admin is logged in vs root admin vs normal user login

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please test and close against master, thanks.
Please also test as root admin, domain admin and normal account against old UI to see if the settings tab is visible or editable for these accounts; against Primate implementation.

**Comment by borisstoyanov** [comment]
LGTM
