### ISSUE TITLE
Implement groupable actions in List View

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#24]
Groupable actions on list views such as on instances (start,stop,destroy, takesnapshot), events (archive, delete), alerts (archive, delete)

**Comment by shwstppr** [comment]
#289 fixes this partially. Actions with input parameters other than `ids` needs to be tested

**Comment by rhtyd** [comment]
Dupes https://github.com/apache/cloudstack-primate/issues/162
