### ISSUE TITLE
[BUG] Domain admin: Identify and access > Roles should not be visible

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#240]
**Describe the bug**
'Identify and access > Roles' screen is visible but the domain admin has no access there so it doesn't make sense.

**To Reproduce**
1. Log in as domain admin, go to 'Identify and access > Roles'

**Expected behavior**
'Identify and access > Roles' should not be visible when logged as domain admin.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77050456-79754a80-69d2-11ea-9bd3-0baac7d71721.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
cc @shwstppr we probably need a show method for the tab that can check if API is available for the user to see the rules tab `api in store.getters.apis...`

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test latest master and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
