### ISSUE TITLE
[BUG] Domain admin: Offerings - more options than in the old UI

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#241]
**Describe the bug**
No Offerings menu options are hidden, as they are in the old UI.

**To Reproduce**
1. Log in as domain admin, go to 'Offerings' - all options are visible there.

**Expected behavior**
Only two options should be visible, as in the old UI - compute and disk offerings.

**Screenshots**
New UI:
![image](https://user-images.githubusercontent.com/12384665/77053228-b2afb980-69d6-11ea-8367-b6b810305706.png)

Old UI:
![image](https://user-images.githubusercontent.com/12384665/77053280-c9561080-69d6-11ea-8a15-9405af851b03.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Offerings > System Offerings generates a 404 error, as mentioned in #233.

**Comment by shwstppr** [comment]
Looking into this. cc @rhtyd

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test latest master and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
