### ISSUE TITLE
[BUG] 'Create SSH Key Pair' differences

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#243]
**Describe the bug**
The dialogs for 'Create SSH Key Pair' are different in Primate and the old UI.

**To Reproduce**
1. Go to 'Compute > SSH Key Pairs' and click the 'Create SSH Key Pair' icon. Look at the dialog.

**Expected behavior**
The dialog in Primate UI must be the same as in the old UI.

**Screenshots**
Primate UI:
![image](https://user-images.githubusercontent.com/12384665/77072326-3036f200-69f6-11ea-993c-5884d90f9924.png)

Old UI:
![image](https://user-images.githubusercontent.com/12384665/77072375-40e76800-69f6-11ea-8cf3-0c0d5ffd81f5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test latest master and close. Thanks.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
