### ISSUE TITLE
[BUG] Normal user: the whole Offerings section should not be visible

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#244]
**Describe the bug**
The 'Offerings' section is visible, but mostly unusable, due to missing permissions. 

**To Reproduce**
1. Go to 'Offerings', try some of the sub-sections.

**Expected behavior**
The whole 'Offerings' section must be hidden, like in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77084406-9a0bc780-6a07-11ea-9daf-b00f350a28ec.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None.

**Comment by shwstppr** [comment]
@rhtyd Are we changing this behaviour? As you mentioned these submenus are dependent on permissions of their respected API but some of the ACS APIs does not have authorized tag defined for them.
Also, when multiple APIs are passed for `permission` param (https://github.com/apache/cloudstack-primate/blob/master/src/config/section/offering.js#L68) the handling of visibility seems to falter

**Comment by shwstppr** [comment]
And related to #241

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test latest master and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
