### ISSUE TITLE
[BUG] Normal user: non-working links (insufficient rights)

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#245]
**Describe the bug**
The following links could generate (if the normal user lacks the required permissions) a 404 (not found) or 500 (Internal server error) errors - template, zone, host, domain, account, compute offering.

**To Reproduce**
1. Log in as normal user, go to 'Network > Guest networks' and click on a network. Then try the 'Zone' and 'Domain' links - they returns '404' (Not found) error.

**Expected behavior**
All links should work or be hidden (if the permissions are insufficient).

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Affected areas:
> Instances
- compute offering - 404
- template - 404
- host - 404
- zone - 404
- domain - 404

> Instance groups
- domain - 404

> SSH Key Pairs
- domain - 404

> Affinity groups
- domain - 404

> Storage > Volumes
- compute offering - 404
- zone - 404
- domain - 404

> Storage > Snapshots
- zone - 404
- domain - 404

> Storage > VM Snapshots
- zone - 404
- domain - 404

> Network - Guest networks
- zone - 404
- domain - 404

> Network - VPC
- zone - 404
- domain - 404

> Network - Security groups
- domain - 404

> Network - Public IP Addresses
- zone - 404
- domain - 404

> Network - VPN Users
- domain - 404

> Images > Templates - selected
- Zone - 404
- account - 500
- domain - 404

> Images > ISOs - selected
- Zone 404
- account - 500
- domain - 404

> Projects
- domain - 404

> Identify and access
- domain - 404

> Quota
- domain - 404

**Comment by rhtyd** [comment]
@vladimirpetrov cc @borisstoyanov please test and close against latest master.

**Comment by rhtyd** [comment]
Verifed
