### ISSUE TITLE
[FEATURE] Add support to manage network service providers

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#250]
For technical preview, only limited network service providers are supported. We list all the available providers but don't allow other features such as to manage/add/edit/update and perform other operations on network service providers that use APIs that have keywords:
 cisco, nicira, baremetal, srx, f5, brocade, palo, ucs, netscaler, bigswitch, ovs, globalloadbalancer, opendaylight etc.

For example the list of NSPs (network service providers) can be seen in old UI -> Infra -> Zone -> Physical network -> select a physical network -> network service providers:
![Screenshot from 2020-03-23 22-23-27](https://user-images.githubusercontent.com/95203/77342027-95bc1300-6d55-11ea-9c11-7680beffb127.png)

When we click on any of the service providers we can see some new buttons and link to list the devices etc. For example this is what we see for Netscalar:
![Screenshot from 2020-03-23 22-23-44](https://user-images.githubusercontent.com/95203/77342031-9785d680-6d55-11ea-858e-4df1d1729e89.png)

The requirements of this task are:
- Add support for all the network service providers which are not already supported
- Each NSP must be implemented in its separate component and imported and used here: https://github.com/apache/cloudstack-primate/blob/master/src/views/infra/network/ServiceProvidersTab.vue
- For each NSP component, add buttons and their forms in a modal and display a list of such NSP devices/resources in a table with pagination

For this task the following APIs (and few more) may need to be supported:
```
addBaremetalDhcp
addBaremetalPxeKickStartServer
addBaremetalRct
addCiscoAsa1000vResource
addCiscoVnmcResource
addNetscalerLoadBalancer
configureOvsElement
deleteBaremetalRct
deleteBigSwitchBcfDevice
deleteBrocadeVcsDevice
deleteCiscoAsa1000vResource
deleteCiscoNexusVSM
deleteCiscoVnmcResource
deleteF5LoadBalancer
deleteNetscalerControlCenter
deleteNetscalerLoadBalancer
deleteNiciraNvpDevice
deleteOpenDaylightController
deletePaloAltoFirewall
deleteSrxFirewall
disableCiscoNexusVSM
enableCiscoNexusVSM
listBaremetalDhcp
listBaremetalPxeServers
listBaremetalRct
listBigSwitchBcfDevices
listBrocadeVcsDevices
listCiscoAsa1000vResources
listCiscoNexusVSMs
listCiscoVnmcResources
listF5LoadBalancers
listNetscalerControlCenter
listNetscalerLoadBalancers
listNiciraNvpDevices
listOpenDaylightControllers
listOvsElements
listPaloAltoFirewalls
listSrxFirewalls
registerNetscalerControlCenter
```

**Comment by rhtyd** [comment]
Hi @utchoang cc @svenvogel can you pick this work as the next major feature work. Let me know if you've any questions. Thanks.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I would like to confirm:
1. Does this task mean that I should enable all network service providers that are not supported now?
2. The component of each NSP should be imported instead of being redirected to. Correct?

**Comment by rhtyd** [comment]
@utchoang :
1. Yes, well we want to be able to show all the buttons and list views for each NSP
2. Yes, in the NSPTab component we've an array of all the NSPs; there you can import and simply show/load the specific component using `<component :is="importedComponent...`
We may redirect but I don't think we need to make it complex enough; we can discuss if you think redirection makes more sense.

**Comment by rhtyd** [comment]
@utchoang this is a rough layout of a component I mocked (poorly with my mouse):
![Screenshot from 2020-03-24 14-26-17](https://user-images.githubusercontent.com/95203/77407251-dfe7d780-6ddb-11ea-97bb-73372f781237.png)

**Comment by utchoang** [comment]
@rhtyd I found that enabling nsp is done while creating zone. It means that I will add changes to the zone wizard. Is that correct?

**Comment by rhtyd** [comment]
@utchoang perhaps, in the first pass just work on the add/other (other than enable/disable) buttons and list views in a separate NSP component. Usually yes, we would enable the NSP based on what isolation mode/setting was used. You may reference the old UI to see what/how the NSPs look, for example http://primate-qa.cloudstack.cloud:8080/client/ (simulator based).

**Comment by utchoang** [comment]
@rhtyd How could we identify which NSP to be enabled based on their mode/setting?

**Comment by rhtyd** [comment]
@utchoang we can call the list API and see the status, if they are not returned we can assume they're disabled/unavailable.

**Comment by rhtyd** [comment]
We've a PR
