### ISSUE TITLE
[BUG] Project view: Network > VPN users should not be visible

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#251]
**Describe the bug**
Network > VPN users is visible when a project is selected in Primate UI. It is not in the old UI.

**To Reproduce**
1. Select a project
1. Go to the 'Network' section

**Expected behavior**
It doesn't make sense to have this in the UI since nothing is shown there anyway and we cannot create new VPN users.

**Screenshots**
New UI:
![image](https://user-images.githubusercontent.com/12384665/77416234-5086f800-6dcc-11ea-9707-4793e2151f3f.png)

Old UI:
![image](https://user-images.githubusercontent.com/12384665/77416488-90e67600-6dcc-11ea-9a14-7f183fede21d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
Possibly related to #236.

**Comment by rhtyd** [comment]
@vladimirpetrov I think it should be because a project's network could have remote VPN enabled, I think it's a non-issue. Please review and close.
