### ISSUE TITLE
[BUG] VM Deployment Wizard Issues

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#254]
Known issues to be checked/fixed:

- Pod, cluster, host should be hidden for normal and domain admin user
- Listing of all items are not done by passing account/domainid, or zoneid (for example listing of networks, template, isos for zone; keypair, affiinity groups etc for account/domain)
- Add a way to filter templates by featured, community, shared, mine?
- Multiple listing of templates for the same zone? (multiple radios button)
- Add button to add network that can open the add network popup or add a router-link?
- User data not properly base64 encoded (check encoding?)
- Add support for processing min/max cpu/ram based on type of compute offering selected (cc @shwstppr) and custom disk offering

**Comment by rhtyd** [comment]
Ping @utchoang @svenvogel - can you have a look at this ticket if you've time, and if not please advise me so I'll ask @shwstppr to look into it instead. For testing please use the http://primate-qa.cloudstack.cloud:8080 env in the .env.local as this env has many mocked zones etc to test against.

**Comment by utchoang** [comment]
Hi @rhtyd cc @svenvogel - I'm working with https://github.com/apache/cloudstack-primate/issues/250. But if this task is more important, I would prioritize doing it first instead of https://github.com/apache/cloudstack-primate/issues/250.

**Comment by rhtyd** [comment]
Yes @utchoang, treat #250 as a new feature task, and so any bugs/issues on 0.5.0-technical-preview will have more priority as those are the things we want to fix before the technical preview release candidate is cut. Kindly prioritise accordingly. Thanks.
