### ISSUE TITLE
[BUG] Events: Some searches have strange outcome

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#258]
**Describe the bug**
Some search strings generate multiple pages of "no data".

**To Reproduce**
1. Go to 'Events' and search by 'deploy'. You'll see 'No data' message, but a lot of pages. You can even navigate through them.

**Expected behavior**
There must be either filtered data or no data and pagination shown. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77663120-61c73480-6f85-11ea-8ce4-d8524d73cce7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov please test and close.

**Comment by rhtyd** [comment]
Manually tested master LGTM, closing on this test
![Screenshot from 2020-04-17 13-29-37](https://user-images.githubusercontent.com/95203/79546136-83f93180-80af-11ea-9d15-e376831abd2c.png)
