### ISSUE TITLE
[BUG] Useless table scrollers on 'New instance' dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#262]
**Describe the bug**
In the 'New instance' dialog there are scrollers in some tables which do not make sense.

**To Reproduce**
1. Go to 'Compute > Instances' and click on the 'Add instance' icon.

**Expected behavior**
There is no need for data grid title scrollers and grid scrollers when the data fits in the available space.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77736546-12c8e000-7015-11ea-8f6e-117c908794e2.png)

![image](https://user-images.githubusercontent.com/12384665/77740540-20ce2f00-701c-11ea-9b4e-720d13057a37.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
None

**Comment by shwstppr** [comment]
This seems inherent behaviour of ANT table element when scrolling is allowed but the content is less
@rhtyd

**Comment by rhtyd** [comment]
@shwstppr it should be possible to hide them with `  overflow-y: hidden;`?

**Comment by shwstppr** [comment]
@rhtyd  not working for me,
```
.ant-table-header, .ant-table-content, .ant-table-scroll {
    overflow-y: hidden;
}
```

**Comment by rhtyd** [comment]
I cannot reproduce this on Ubuntu 19.10 with latest Chrome, on master we updates Ant Design dependency which may have addressed it.

It looks like this now:
![Screenshot from 2020-06-04 13-31-15](https://user-images.githubusercontent.com/95203/83731179-b4992880-a667-11ea-90e5-159dd045f292.png)

![Screenshot from 2020-06-04 13-31-08](https://user-images.githubusercontent.com/95203/83731175-b367fb80-a667-11ea-855c-c33ea4ea5c8e.png)
