### ISSUE TITLE
[BUG] Missing hypervisor parameter in the 'New instance' dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#265]
**Describe the bug**
It's impossible to create a new VM instance due to missing hypervisor parameter - even when everything is properly filled, the following error is shown when 'Launch VM' button is pressed:

> Request Failed
> hypervisor parameter is needed to deploy VM or the hypervisor parameter value passed is invalid

**To Reproduce**
1. Go to 'Compute > Instances' and click on the 'Add instance' icon.
2. Enter all required parameters in the dialog (make sure you select ISO, not template) and press the 'Launch VM' button.

**Expected behavior**
There must be a way to set the hypervisor parameter somewhere in the dialog.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov can you test master again, I think this was fixed. When ISO is selected it asks hypervisor dropdown below it.

**Comment by borisstoyanov** [comment]
LGTM
