### ISSUE TITLE
[BUG] Images > Templates > Upload Local Template - Zone cannot be changed in the dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#269]
**Describe the bug**
The zone cannot be changed when uploading a local template - it stays on the first entry no matter what you select from the drop-down list.

**To Reproduce**
1. Go to 'Images > Templates' and click 'Upload Local Template'. Now try to change the zone - whatever you select, the top entry stays selected.

**Expected behavior**
You should be able to change the zone.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77769330-5d198380-704c-11ea-910c-5b32d7d30513.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please test and close, thanks.

**Comment by rhtyd** [comment]
Manually tested:

Before selection:
![Screenshot from 2020-04-17 13-36-51](https://user-images.githubusercontent.com/95203/79546744-8d36ce00-80b0-11ea-9be0-cb46ce6a725c.png)

During selection:
![Screenshot from 2020-04-17 13-37-00](https://user-images.githubusercontent.com/95203/79546768-9758cc80-80b0-11ea-9786-39877a1b2aa3.png)

After change:
![Screenshot from 2020-04-17 13-37-02](https://user-images.githubusercontent.com/95203/79546782-9aec5380-80b0-11ea-890b-1f59e2bcdd07.png)

**Comment by rhtyd** [comment]
Closing on manual testing.

**Comment by borisstoyanov** [comment]
LGTM
