### ISSUE TITLE
Implement Tree-view based Domain List View

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#27]
Implement a tree based domain list view, or discuss alternative approaches. (ref listDomainChildren)

The suggested component that can be used:
https://www.antdv.com/components/tree/
Or,
A table with a tree based navigation like: 
https://www.antdv.com/components/table/#components-table-demo-tree-data

Screenshot of how it looks in the old UI:
![Screenshot from 2019-11-25 23-26-36](https://user-images.githubusercontent.com/95203/69565495-156de700-0fdb-11ea-8bf3-caf3d21a1452.png)

This is how the domain list view looks in Primate:
![Screenshot from 2019-11-25 23-28-21](https://user-images.githubusercontent.com/95203/69565587-4e0dc080-0fdb-11ea-954f-237e99d0a4ae.png)

**Comment by svenvogel** [comment]
Hi @rhtyd, my college Hoang Nguyen @utchoang will look in this task. Give him some time to come into the  topic.

**Comment by rhtyd** [comment]
Sure, thanks for sharing @svenvogel let me know if you or @utchoang needs any assistance. I'll update tickets with details in coming days.
