### ISSUE TITLE
[BUG] Download template/iso missing 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#277]
**Describe the bug**
User cannot download iso or tempplate

**To Reproduce**
1. Go to images/templates/isos
2. select one 

**Expected behavior**
I'd exepct to see the button there to download the template/iso

**Screenshots**

**Comment by rhtyd** [comment]
@borisstoyanov @vladimirpetrov - can you specify in your bug reports where you're testing it - either on primate-qa or in a trillian/valid env?

**Comment by borisstoyanov** [comment]
Tested on Trillian env with KVM hosts.

**Comment by shwstppr** [comment]
![Screenshot from 2020-04-09 18-54-17](https://user-images.githubusercontent.com/153340/78899840-93ff8880-7a93-11ea-9c1f-e291a66b262c.png)
@borisstoyanov Download option is shown for templates and isos registered with extractable=true param.
Old UI allowed download option for all ISOs but this has been changed with https://github.com/apache/cloudstack/pull/4017
here https://github.com/apache/cloudstack/pull/4017/files#diff-cf05785fddf22f1b1e1723a9d27db572R4189-R4191

**Comment by borisstoyanov** [comment]
True that, not a bug.
