### ISSUE TITLE
[BUG] ISO - Update permissions form does not autodiscover operation, accounts and projects

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#278]
**Describe the bug**
Update permissions form does not autodiscover operation, accounts and projects

**To Reproduce**
1. Go to ISOs
2. Select an iso
3. Click on Update permissioins
4. See that fields are not autodiscovering operation/account/project

**Expected behavior**
There should be dropdown option for the fields 

**Screenshots**
![Screenshot 2020-04-02 at 16 38 52](https://user-images.githubusercontent.com/13551960/78256061-c1cb5700-7500-11ea-9648-e929f345b543.png)

**Comment by rhtyd** [comment]
cc @shwstppr likely a missing feature

**Comment by rhtyd** [comment]
@borisstoyanov @vladimirpetrov please test latest master and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
