### ISSUE TITLE
[BUG] Copy ISO Form does not discover values in fields. Also they seem to be displayed as API attributes

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#279]
**Describe the bug**
Fields are not populated when selecting copy iso

**To Reproduce**
1. Go to ISOs
2. Select an iso
3. Click on Copy ISO
4. See that fields are not autodiscovering Source and destination and fields are displayed and api call attributes names 

![Screenshot 2020-04-02 at 16 50 53](https://user-images.githubusercontent.com/13551960/78257494-96e20280-7502-11ea-9c4f-2320a234edda.png)

**Comment by rhtyd** [comment]
cc @shwstppr missing feature, can you explore if instead of the button on the resource view, we can move it to the iso zones tab which allows for delete I think, so copy could be moved there as well?

**Comment by rhtyd** [comment]
@shwstppr remark - please move the copy and delete button to the iso and template zone components listed in front of each zone item/row.

**Comment by rhtyd** [comment]
@borisstoyanov @vladimirpetrov please test latest master and close. The UX is changed slightly as follows:
- the copy and delete buttons are now part of the zones tab for template/iso similar to old UI
- there's a new template/iso filter drop down near search bar for template/iso list views
- Kindly test template/iso register and upload features as well

**Comment by rhtyd** [comment]
ping @vladimirpetrov

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
