### ISSUE TITLE
[BUG] Kubernetes ISO are not searchable

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#280]
**Describe the bug**
when entering search term user cannot filter the isos
**To Reproduce**

**Screenshots**
![Screenshot 2020-04-02 at 17 00 59](https://user-images.githubusercontent.com/13551960/78258322-bb8aaa00-7503-11ea-82bb-1d17542a5260.png)

**Comment by rhtyd** [comment]
cc @shwstppr - likely the backend API does not support that? I've moved it to 1.0-GA instead as this is not a major issue.

**Comment by shwstppr** [comment]
@rhtyd yes this will require some backend changes. It would be better to handle this in next milestone as suggested

**Comment by rhtyd** [comment]
This needs fixing in backend and Primate will automatically support that, closing this one as I've opened https://github.com/apache/cloudstack/issues/4056 cc @borisstoyanov
