### ISSUE TITLE
[BUG] Add zone -> Add primary storage -> Scope Zone option is a label 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#281]
**Describe the bug**

**To Reproduce**
1. Go to Add zone 
2. Navigate to Add primary storage and select scope

**Expected behavior**
Option should not be displayed as label 

**Screenshots**
![Screenshot 2020-04-03 at 15 24 57](https://user-images.githubusercontent.com/13551960/78360463-817ede00-75bf-11ea-8cee-05931a44df24.png)

**Desktop (please complete the following information):**
 - OS: Mac, Trillian env
 - Browser: Chrome
 - Version 80

**Comment by rhtyd** [comment]
@borisstoyanov please test and close. PR merged on master.

**Comment by borisstoyanov** [comment]
![Screenshot 2020-04-15 at 15 32 19](https://user-images.githubusercontent.com/13551960/79337514-4e790a80-7f2e-11ea-9d7f-1c7bc3d51b0f.png)
LGTM now
