### ISSUE TITLE
[BUG] Enable/Disable maintenance mode in UI prompts error, but host is set properly

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#282]
**Describe the bug**
When trying to set host to maintenance or disable maintenance there's the following error displayed in UI, but in background the call seems to be made, because host is set to maintenance. 
```
Request Failed
Cannot read property 'push' of null
```
**To Reproduce**
1. Go to a Host 
2. Click on Enable Maintenance mode

**Screenshots**
![Screenshot 2020-04-03 at 16 07 21](https://user-images.githubusercontent.com/13551960/78364127-a0806e80-75c5-11ea-8dea-a4c7b6bb50c2.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 80
 - Tested with trillian env with KVM host

**Comment by shwstppr** [comment]
@borisstoyanov I'm not able to reproduce this one with the latest master. Are there any specific steps?
cc @rhtyd

**Comment by borisstoyanov** [comment]
I've also tried @shwstppr and I cannot as well. Lets ignore it for now and reopen if needed
