### ISSUE TITLE
[BUG] As root admin cannot see instances in Kubernetes cluster created as user

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#286]
**Describe the bug**
Root admin is not displayed with instances of a kub cluster created by user

**To Reproduce**
1. Create a cluster as user 
2. Login as root and list the instances of the cluster

**Expected behavior**
Instances listed

**Screenshots**
As root admin 
![Screenshot 2020-04-06 at 16 26 26](https://user-images.githubusercontent.com/13551960/78563459-ab383f00-7823-11ea-9931-253bc296aaef.png)

As User 
![Screenshot 2020-04-06 at 16 26 06](https://user-images.githubusercontent.com/13551960/78563478-b2f7e380-7823-11ea-871a-fc7cee46eedf.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 80
 - Tested in a trillian env

**Comment by rhtyd** [comment]
@borisstoyanov please test and close. PR merged on master.

**Comment by rhtyd** [comment]
ping @vladimirpetrov  @borisstoyanov

**Comment by rhtyd** [comment]
I've confirmed this, closing.
