### ISSUE TITLE
[BUG] Infrastructure > System VMs > Run Diagnostics does not show the command output

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#293]
**Describe the bug**
The action 'Run Diagnostics' from the System VMs screen is not showing the result of the command.

**To Reproduce**
1. Go to 'Infrastructure > System VMs' and click on a system VM
2. Click on the 'Run Diagnostics' button, then choose 'ping' operation with some argument - '8.8.8.8' for example.

**Expected behavior**
The result of the command must be shown, as in the old UI. Currently only a 'Network error' is shown instead and it's not clear where exactly is the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/79353274-82aaf600-7f43-11ea-975b-f2b4a73330d4.png)

![image](https://user-images.githubusercontent.com/12384665/79353566-e6cdba00-7f43-11ea-9f89-42983c0606f4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.92 (Official Build) (64-bit)

**Additional context**
I'm not sure if this functionality even works.

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by rhtyd** [comment]
This was probably tested on simulator and the error makes sense; perhaps we need to test against a kvm/real env.

**Comment by shwstppr** [comment]
API runs on real env but no optput is shown, looking into it @rhtyd @vladimirpetrov

**Comment by vladimirpetrov** [comment]
This was tested on a Trillian environment, not simulator @rhtyd .

**Comment by shwstppr** [comment]
@vladimirpetrov I've fixed the display issue for both systemvm and VR. cc @rhtyd

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please retest against latest master, against a real env otherwise output will be missing against qa server/simulator.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
