### ISSUE TITLE
[BUG] Can't add load balancer

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#294]
**Describe the bug**
When trying to add a new load balancer, the VM selection popup doesn't load.
It's impossible to add a load balancer via the UI because of this.

button, 
**To Reproduce**
1. Go to an allocated IP address
2. Select the "Load Balancing" tab
3. Enter values into the Name, Public Port, Private Port, Algorithm, Protocol fields
4. Click on the "Add" button

**Expected behavior**
The VM selection dialogue should pop up.

**Screenshots**
![Screenshot_20200416_144147](https://user-images.githubusercontent.com/371687/79458750-8fd2ee00-7ff2-11ea-9690-3ec661a04ba6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 74.0.1

**Additional context**
The issue seems to happen when the listVirtualMachines call sent by the "Add VMs" handler returns an empty list, like this:
```json
{"listvirtualmachinesresponse":{}}
```

The console log prints the message:
```
TypeError: t.response is undefined           LoadBalancing.vue:935:10
```

This is with the latest HEAD (commit bcf86f450d6aede6bad5d556a1cf81fe00ccfd2c )

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by shwstppr** [comment]
@onitake is it possible for you to checkout PR #296 
I've tried fix error handling on API failure

**Comment by onitake** [comment]
@shwstppr Awesome, that seems to have fixed the problem. I get a proper list of VMs now, and no error message in the console.
