### ISSUE TITLE
[FEATURE] Complete Quota UI Feature

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#295]
Refer to old UI (for example: http://primate-qa.cloudstack.cloud:8080/client/) and complete the quota UI feature in Primate. Also see following related tickets:
https://github.com/apache/cloudstack-primate/issues/209
https://github.com/apache/cloudstack-primate/issues/210
https://github.com/apache/cloudstack-primate/issues/211
https://github.com/apache/cloudstack-primate/issues/212

**Comment by rhtyd** [comment]
@utchoang can you pick this one next, after your current work. Thanks. cc @svenvogel

**Comment by utchoang** [comment]
@rhtyd I got it. Thanks.

**Comment by rhtyd** [comment]
Have PR
