### ISSUE TITLE
[BUG] Upload local template - empty Hypervisor drop-down after selecting incomplete zone

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#300]
**Describe the bug**
While uploading a local template, if you cycle through the zones list and go through one that's not complete (missing storage for example), Primate UI properly shows empty drop-down for Hypervisor. The problem is that after selecting a functional zone, the drop-down still says empty so the only workaround is to close the dialog and start from scratch.

**To Reproduce**
1. Make sure you have at least one working and one incomplete (missing storages) zone.
2. Go to 'Images > Templates' then click on 'Upload local template' icon.
3. Select the incomplete zone from the 'Zone' drop-down, then select again the working one
4. Open the 'Hypervisor' drop-down - it's empty.

**Expected behavior**
The dynamic content should be reloaded after each zone selection.

**Screenshots**
When the proper zone has been selected:
![image](https://user-images.githubusercontent.com/12384665/79860369-39432680-83db-11ea-9721-8176017dd054.png)

And after the invalid zone has been selected and then again the working one:
![image](https://user-images.githubusercontent.com/12384665/79860444-57a92200-83db-11ea-93ca-9a4ddf9190ad.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.92 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by rhtyd** [comment]
@vladimirpetrov please re-test and close against latest master.

**Comment by rhtyd** [comment]
ping @vladimirpetrov  @borisstoyanov

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
