### ISSUE TITLE
[BUG] Missing domain parameter when updating compute offering access

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#301]
**Describe the bug**
When updating compute offering access, there is a 'Domain' setting in the old UI which is missing in the Primate UI.

**To Reproduce**
1. Go to 'Offerings > Compute offerings', click on an offering.
2. Now click on the 'Update offering access' icon and make sure the 'Public' checkbox is unchecked - the 'Domain' selection from the old UI is missing.

**Expected behavior**
There must be a 'Domain' selection element, in case of non-public access, like in the old UI.

**Screenshots**
Old UI:
![image](https://user-images.githubusercontent.com/12384665/79883464-a1563480-83fc-11ea-9661-0d48e828b81a.png)

Primate UI:
![image](https://user-images.githubusercontent.com/12384665/79883531-b29f4100-83fc-11ea-82d2-be51e891084b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.92 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by rhtyd** [comment]
@vladimirpetrov please test against latest master and close.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
