### ISSUE TITLE
[BUG] The 'Public' checkbox in 'Update compute offering access' is not working

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#302]
**Describe the bug**
When updating compute offering access, there is a 'Public' checkbox that doesn't change anything in Primate UI. It doesn't even load the current state of the parameter - just always opens as 'disabled'.

**To Reproduce**
1. Go to 'Offerings > Compute offerings', click on an offering.
2. Now click on the 'Update offering access' icon and look at the 'Public' checkbox - it is always unchecked, even if you have checked it in the old UI. It doesn't change anything either.

**Expected behavior**
The 'Public' checkbox should work as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/79884914-943a4500-83fe-11ea-9c45-cd702fe3204d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.92 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by rhtyd** [comment]
@vladimirpetrov please test against latest master and close.

**Comment by vladimirpetrov** [comment]
Somehow I got confused and logged this bug twice. Closing it as duplicate of #302.

**Comment by vladimirpetrov** [comment]
Somehow I got confused and logged this bug twice. Closing it as duplicate of #303.
