### ISSUE TITLE
[BUG] Apply threshold logic to colour pie-progress red if threshold exceeds 80%

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#308]
On the dashboard, check and enforce that progress bar is shown red if value exceeds 80% (see code in src/view/dashboard/). This is for the admin dasboard.

cc @shwstppr

**Comment by rhtyd** [comment]
I could confirm for 100+%: but not for values 75, 80, 85...
![Screenshot from 2020-04-23 15-40-07](https://user-images.githubusercontent.com/95203/80088194-c9b76d80-8579-11ea-8f96-18e20ebf6436.png)

**Comment by shwstppr** [comment]
@rhtyd Currently there are some auto-defined thresholds,
![Screenshot from 2020-04-24 11-34-39](https://user-images.githubusercontent.com/153340/80181663-e360bf80-8622-11ea-8290-46f5133d4246.png)
![Screenshot from 2020-04-24 11-33-52](https://user-images.githubusercontent.com/153340/80181670-e52a8300-8622-11ea-9060-6041803e9114.png)
![Screenshot from 2020-04-24 11-33-05](https://user-images.githubusercontent.com/153340/80181682-e9ef3700-8622-11ea-94d4-02f7a59e0ed4.png)
![Screenshot from 2020-04-24 11-33-30](https://user-images.githubusercontent.com/153340/80181675-e5c31980-8622-11ea-8548-9e5ba335ecc1.png)

I've raised a PR to set thresholds for 100+, 85+, 75+, 25+, if needed

**Comment by rhtyd** [comment]
@shwstppr can you change it like this: below 80% a fixed colour (blue as per the theme); and >= 80% just use 'red' (this is behaviour of the old UI).

**Comment by shwstppr** [comment]
![Screenshot from 2020-04-24 16-22-58](https://user-images.githubusercontent.com/153340/80205416-35680c00-8648-11ea-9c1a-58330f9ab4d3.png)
Changes made to PR #309 
Just red for >=80% and the default for rest

**Comment by rhtyd** [comment]
Verified and tested manually.
