### ISSUE TITLE
[BUG] defaults selection in deploy wizard are missing

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#311]
**Describe the bug**
In the old UI while going through the deployment wizard, the fields for "Compute Offering" and "network" are filled with (reasonable) defaults. In Primate those do not contain selections, resulting in an extra few clicks needed by the user.

**To Reproduce**
1. Go to 'compute > instances > add instance'
2. Select a zone
3. Scroll down to 'Compute offering' and/or 'Network'
4. See error; no pre-selection made

**Expected behavior**
a "compute offering" selected, and a "network" selected if the user has any.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**
This has been added to #158 as well, but will not be experienced as a enhancement by users of the  old UI.

**Comment by DaanHoogland** [comment]
@utchoang I think you did the most work on the deployment wizard, can you give a quick assesment of the issue I describe. I will improve the description if needed, but i want to first now if this had been omitted on purpose.

**Comment by rhtyd** [comment]
I think we simply need to auto-select the first item in the list (if the item is not empty) - @utchoang can you fix this whenever you get time, thanks.

**Comment by utchoang** [comment]
@rhtyd OK. I'll fix it on  my PR https://github.com/apache/cloudstack-primate/pull/307

**Comment by rhtyd** [comment]
Moved here https://github.com/apache/cloudstack-primate/issues/306
