### ISSUE TITLE
[BUG] Updatе compute offering access dialog does not get current state on loading

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#322]
**Describe the bug**
The 'Updatе compute offering access' dialog does not read current state of variables when loaded. This is visible when using two different browsers with the same user - if you change a setting in the first browser, the second does not see it until the 'Refresh' button is clicked.

**To Reproduce**
1. Log in as same user in two different browsers (not tabs in the same browser).
2. Using browser 1 go to 'Offerings > Compute offerings', click on an offering and change some parameter there in the 'Update offering access' dialog.
2. Using browser 2 open the same dialog - you'll see the old state, not the modified parameter.

**Expected behavior**
The dialog should read its current state when loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/80978215-6efdfb80-8e2e-11ea-9e28-7952c31a45a3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
Related to #303.

**Comment by rhtyd** [comment]
@shwstppr pl see

**Comment by shwstppr** [comment]
@rhtyd this is because offering item is not refreshed in second window after it is updated in the first window. Should we fetch offering's new details when the form is opened (I originally added this but it was removed during code review https://github.com/apache/cloudstack-primate/pull/94/commits/845d0e9e2b317937f435be5c33a56f2a071f5952#diff-a341f854d0c3be2321235491b26f7075L158-L171). Moreover this behaviour will be seen across all update actions in UI. cc @vladimirpetrov

**Comment by rhtyd** [comment]
@shwstppr Isn't it available in this.resource? That's why I removed it, you can $emit the refresh event so you don't need to call the list API. Check the best option and send a PR as necessary.

**Comment by shwstppr** [comment]
@rhtyd @vladimirpetrov Following action/APIs might show similar behaviour,

- updateVirtualMachine
- updateInstanceGroup
- updateUser
- updateRole
- updateTemplate
- updateIso
- updateKubernetesVersion
- updateNetwork
- updateVPC
- updateNetworkACLList
- updateVpnCustomerGateway
- enable/disable*Offering
- updateHost
- updatePod
- updateZone

should I change it for them as well?

**Comment by rhtyd** [comment]
limit them to this bug wrt offerings only for now @shwstppr just send a PR with the changes I had removed not considering this case from the original PR

For other update APIs, when form is created we use this.resource to populate the options.

**Comment by rhtyd** [comment]
PR merged, please test against latest master and close this @vladimirpetrov

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
