### ISSUE TITLE
[FEATURE] Cache API discovery list

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#332]
**Is your feature request related to a problem? Please describe.**
Everytime a user logs in, or opens a new tab for a logged in session the API discovery is fired that causes the UI to load slow.

**Describe the solution you'd like**
Explore ways to speedup API discovery or caching mechanism by use of local storage.

**Comment by onitake** [comment]
Good idea.

There needs to be some mechanism to ensure the API list is up to date, there are at least three scenarios where it may change:

* CloudStack is upgraded
* The user's role changes
* The user's role's permissions change

Is it possible to calculate some sort of "API hash" server-side?
A cache timeout may also be a good idea, and a manual "clear API cache" action.

**Comment by rhtyd** [comment]
@onitake please check/test latest master and give your feedback, I've tried to implement client side caching for:
- Load Primate early and let API discovery add dynamic routes without completely blocking the view
- After login, the APIs are cached in local storage in case Primate is refreshed or a link is opened in another tab

**Comment by onitake** [comment]
Sounds good!
Does that mean that the cache is cleared when you log out?

**Comment by rhtyd** [comment]
Yes @onitake API cache stored in browser local storage will reset on logout, login and session expiry.

**Comment by onitake** [comment]
I have to admit, I didn't see a big difference.

My test was as follows:

1. Login
2. Wait for discovery completion
3. Access list of VMs
4. Close browser tab
5. Open primate in a new browser tab
6. Observe message "Login detected, using cached APIs" in the console

I assume that the old behaviour was that a new API discovery task would be launched in the new tab, correct? In this case, this is definitely an improvement.
