### ISSUE TITLE
Add support for tiers in PF, LB rules for a VPC

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#333]
**Is your feature request related to a problem? Please describe.**

- Add support for tiers dropdown in PF, LB tabs for a VPC (ip address, not SNAT-ed) (see IP address of any VPC)
- Add pagination/searching in add VMs modal for the PF, LB, FW tabs.

**Comment by rhtyd** [comment]
Hi @utchoang - can you have a look at this whenever you want to work on the next item. Thanks.

**Comment by utchoang** [comment]
Thanks, @rhtyd.
But at the request, can you describe it in more detail?
* Add support for tiers dropdown in PF, LB tabs
  - PF, LB tabs are the tabs in the picture below.
  - Is it going to add a Select Tier for the remaining tabs?
![image](https://user-images.githubusercontent.com/13766648/83371459-b7d4b000-a3ec-11ea-9916-351859bb2a4a.png)

* Add pagination/searching in add VMs modal for the PF, LB, FW tabs.
  - I tried 1 round of testing but could not find VMs modal. Can you specify the help?

cc @svenvogel

**Comment by svenvogel** [comment]
@utchoang maybe i dont have them in my mind. tiers means?

**Comment by rhtyd** [comment]
@utchoang @svenvogel sorry I did not explain the issue clearly, let me try with some screenshots.
In the old UI (we can refer http://primate-qa.cloudstack.cloud:8080/client/), go to Network -> VPC -> pick any (say AdminVPC-RR) -> Configure -> Public IP and select an IP that's not on a tier we see the LB and PF options:
![Screenshot from 2020-06-04 08-35-50](https://user-images.githubusercontent.com/95203/83710464-691e5480-a63e-11ea-9a47-207521cab246.png)

Next if we go to either the LB or the PF views, we see it gives us a drop to select for which tier we're adding a LB or PF rule:
![Screenshot from 2020-06-04 08-36-34](https://user-images.githubusercontent.com/95203/83710663-dfbb5200-a63e-11ea-9672-314e2024b90e.png)

For LB for example:
![Screenshot from 2020-06-04 08-39-32](https://user-images.githubusercontent.com/95203/83710718-fc578a00-a63e-11ea-8a5e-11a13b56ab6d.png)

For the select tier, it shows only VMs on that tier in the wizard. But once we add a PF or LB rule for a tier, then the form does not show the tier option. So I propose we can address this issue as follows:
- In the PF and LB add VM form, display tiers if the IP address longs to a VPC (i.e has a vpcid) but it does not belong to a tier (i.e. public IP allocated but not attached to a tier yet). The VMs also get listed by the selected tier, or if the IP already is associated with a VPC tier/network.
- We need to check and hide the firewall tab if the IP belong to a VPC, as ACL is used instead of firewall rules.

I'm open to further discussions and any other way to fix this. Thanks.

**Comment by rhtyd** [comment]
We've a PR now, dupes https://github.com/apache/cloudstack-primate/issues/438
