### ISSUE TITLE
Primate UI Smoke test plan

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#334]
## Primate UI smoke test

| Functionality | Tester | Result | Related issues |
|---------------|--------|--------|----------------|
| **Instances** | | | |
| Create instance using template | Vladimir | PASSED | |
| Create instance using ISO image and different parameters than the previous one | Vladimir | PASSED | |
| Test all VM actions - Start/Stop/Reboot/Reinstall/Update, etc | Vladimir | PASSED | |
| Add/modify/delete VM setting | Vladimir | PASSED | |
| Add network to VM, change IP address, make it default, delete | Vladimir | PASSED | |
| Add/delete secondary IP address | Vladimir | PASSED | |
| | | | |
| **Add Instance groups** | | | |
| Add/modify/delete instance group| Vladimir | PASSED | |
| | | | |
| **SSH Key Pairs**| | | |
| Add/delete SSH key pair| Vladimir | FIXED | #335 |
| | | | |
| **Affinity Groups**| | | |
| Add/delete host affinity group | Vladimir | PASSED | |
| Add/delete host anti-affinity group | Vladimir | PASSED | |
| | | | |
| **Volumes** | | | |
| Create volume | Vladimir | PASSED | |
| Upload local volume | Vladimir | PASSED | |
| Upload volume from URL | Vladimir | PASSED | |
| Volume actions - snapshots, resize, migrate, download, create template | Vladimir | PASSED | |
| | | | |
| **Snapshots** | | | |
| Snapshot actions - create template/volume, revert, delete | Vladimir | PASSED | |
| | | | |
| **VM Snapshots** | | | |
| VM Snapshot actions - revert, delete | Vladimir | PASSED | |
| | | | |
| **Guest networks** | | | |
| Add isolated network | Vladimir | PASSED | |
| Add L2 network | Vladimir | PASSED | |
| Add shared network | Vladimir | PASSED | |
| Network actions - update, restart, delete | Vladimir | PASSED | |
| Add/delete egress rules | Vladimir | PASSED | |
| Acquire IP address | Vladimir | PASSED | |
| | | | |
| **VPC**| | | |
| Add VPC | Vladimir | PASSED | |
| VPC actions - update, restart, delete | Vladimir | PASSED | |
| | | | |
| **Security Groups** | | | |
| Add security group | Vladimir | PASSED | |
| Add/delete ingress/egress rule | Vladimir | PASSED | |
| | | | |
| **Public IP Addresses** | | | |
| Acquire new IP | Vladimir | PASSED | |
| Actions - enable/disable static NAT, release IP, enable VPN | Vladimir | PASSED | |
|  | | | |
| | | | |
| **Templates**| | | |
| Register template | Vladimir | PASSED | |
| Upload local template | Vladimir | PASSED | |
| Template actions - edit, download, update permissions, copy, delete | Vladimir | FAILED | #341 |
| | | | |
| **ISOs**| | | |
| Register ISO | Vladimir | PASSED | |
| Upload local ISO | Vladimir | PASSED | |
| ISO actions - edit, download update permissions, copy, delete | Vladimir | FAILED | #341 |
| | | | |
| **Events**| | | |
| Search, archive, delete | Vladimir | PASSED | |
| | | | |
| **Projects** | | | |
| Add project | Vladimir | FAILED | #336 |
| Project actions - edit, suspend, delete | Vladimir | PASSED | |
| Add/remove account, make account project owner | Vladimir | PASSED | |
| Different projects | Vladimir | FAILED | #342 |
| | | | |
| **Accounts, users, roles** | | | |
| Create/modify/check role/delete regular user account | Vladimir | PASSED | |
| Create/modify/check role/delete domain admin account | Vladimir | PASSED | |
| Create/modify/check role/delete admin user | Vladimir | PASSED | |
| Account actions - edit, disable, lock, delete | Vladimir | PASSED | |
| | | | |
| **Domains** | | | |
| Create new domain | Vladimir | PASSED | |
| Create subdomain in the new domain | Vladimir | PASSED | |
| Delete the first domain (2nd, not 3rd level) | Vladimir | PASSED | |
| Edit/delete domain | Vladimir | PASSED | |
| Modify domain limits/settings | Vladimir | PASSED | |
| | | | |
| **Roles** | | | |
| Add new role | Vladimir | PASSED | |
| Role actions - edit, delete, add/delete rules | Vladimir | PASSED | |
| | | | |
| **Zones**| | | |
| Add zone | Vladimir | PASSED | |
| Zone actions - edit, enable/disable, enable/disable HA, delete, etc. | Vladimir | PASSED | |
| Modify settings | Vladimir | PASSED | |
| | | | |
| **Pods** | | | |
| Add pod | Vladimir | PASSED | |
| Pod actions - edit, enable/disable, delete | Vladimir | PASSED | |
| | | | |
| **Clusters** | | | |
| Add cluster | Vladimir | PASSED | |
| Cluster actions - enable/disable, unmanage, enable/disable HA, delete, etc| Vladimir | PASSED | |
| | | | |
| **Hosts** | | | |
| Add host | | | |
| Host actions - edit, enable/disable, maintenance mode, enable/disable/configure HA, etc. | Vladimir | PASSED | |
| | | | |
| **Primary storage** | | | |
| Add primary storage | Vladimir | PASSED | |
| Primary storage actions - edit, enable/disable maintenance mode | Vladimir | PASSED | |
| Settings - modify | Vladimir | PASSED | |
| | | | |
| **Secondary storage** | | | |
| Add secondary storage | Vladimir | FIXED | #344 |
| Delete secondary storage | Vladimir | PASSED | |
| | | | |
| **Compute offering** | | | |
| Add shared thin compute offering | Vladimir | PASSED | |
| Add local fat compute offering | Vladimir | PASSED | |
| Offering actions - edit, access, delete | Vladimir | PASSED | |
| | | | |
| **System offering** | | | |
| Add shared thin system offering for domain router | Vladimir | PASSED | |
| Add local sparse system offering for console proxy | Vladimir | PASSED | |
| Offering actions - edit, delete | Vladimir | PASSED | |
| | | | |
| **Disk offering** | | | |
| Add shared thin disk offering | Vladimir | PASSED | |
| Add local fat disk offering | Vladimir | PASSED | |
| Offering actions - edit, access, delete | Vladimir | PASSED | |
| | | | |
| **Network offering** | | | |
| Add isolated network with some supported services | Vladimir | PASSED | |
| Add L2 network | Vladimir | PASSED | |
| Add shared network with some supported services | Vladimir | PASSED | |
| Network actions - edit, enable/disable, access, delete | Vladimir | PASSED | |
| | | | |
| **VPC offering** | | | |
| Change VPC offerings order | Vladimir | PASSED | |
| Add new VPC offering with some supported services | Vladimir | PASSED | |
| VPC offering actions - edit, enable/disable, access, delete | Vladimir | PASSED | |
| | | | |
| **Global settings** | | | |
| Search setting | Vladimir | PASSED | |
| Modify setting | Vladimir | PASSED | |
| | | | |
| **Common functionality** | | | |
| Sorting | Vladimir | PASSED | |
| Pagination | Vladimir | PASSED | |
| Searching | Vladimir | PASSED | |
| Add/remove tags | Vladimir | PASSED | |
| Add/remove comments | Vladimir | PASSED | |
| Refresh | Vladimir | PASSED | |
| Links | Vladimir | PASSED | |

**Comment by rhtyd** [comment]
Thanks @vladimirpetrov - however this ticket must be assigned to you that I'm unable to assign to execute.

**Comment by rhtyd** [comment]
Milestone reached.
