### ISSUE TITLE
[BUG] Create SSH key pair - interconnected fields when creating new SSH key pair

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#335]
**Describe the bug**
The 'Name' and 'Account' fields in 'Create SSH Key Pair' dialog are interconnected - whatever you write in one of the fields, goes into the other as well.

**To Reproduce**
1. Go to 'Compute > SSH Key Pair' and click 'Create SSH Key Pair'
2. Select a domain and try to enter different name and account - they are duplicated, whatever you write in one of the fields, goes into the other as well.

**Expected behavior**
Both fields must be independent.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/81825848-ccd1c800-953f-11ea-8077-6f537e2361ce.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@shwstppr can you advise if this is a quick one? I'll check tomorrow.

**Comment by rhtyd** [comment]
Please test master and close @vladimirpetrov

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
