### ISSUE TITLE
[BUG] New project name notification shows actually the previous name

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#336]
**Describe the bug**
When you create a new project, the name in the notification box is actually the previously created project's name.

**To Reproduce**
1. Make sure you have at least one project created. Add a new one and look at the notification box - the name is from the old one

**Expected behavior**
The notification box must show the name of the newly created project.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/81830606-f3dec880-9544-11ea-811b-b47a59921933.png)

![image](https://user-images.githubusercontent.com/12384665/81831084-98f9a100-9545-11ea-9ce2-b27d5143d876.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
I've found this to be a system-wide issue for any action that happens via the list/table view, it uses the `this.resource.name` which is the first item of the table. Needs some plumbing. cc @vladimirpetrov

**Comment by rhtyd** [comment]
@vladimirpetrov please test

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
