### ISSUE TITLE
[FEATURE] Boot type and boot mode dropdowns in the deploy wizzard

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#339]
**Is your feature request related to a problem? Please describe.**
In 4.14 the ability to deploy with a specified boot type and boot mode, i.e. UEFI/secure, is possible. This should be reflected in the primate UI.
 
**Describe the solution you'd like**
extra dropdowns with the possible options for boot type and boot mode should be available in the overview (top level) step of the deploy wizard.

**Describe alternatives you've considered**
Other places could be with the template and hardware dimnesions choices but these does not seem better locations.

**Additional context**
Boot type can be 'BIOS' or 'UEFI' and mode can be 'legacy' or 'secure'.

**Comment by rhtyd** [comment]
@utchoang can you pick this up next. Please check the old uI (http://primate-qa.cloudstack.cloud:8080/client/) to see the boot type/mode options in the VM deployment wizard - we want that for Primate's vm deployment wizard as well.

Thanks.
