### ISSUE TITLE
[BUG] UI locks when editing template or ISO properties

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#341]
**Describe the bug**
When you try to change most of the template properties, the UI locks in never-ending rotating circle.

**To Reproduce**
1. Go to 'Images > Templates' and click on a template. (Or go to 'Images > ISOs' and click on ISO)
2. Click on the 'Edit' icon. Now try to change anything but OS Type - the UI will show the waiting rotating circle forever.

**Expected behavior**
No UI locks, whatever the reason.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82042087-f3b00b80-96b1-11ea-9e9a-ee62d232346b.png)

![image](https://user-images.githubusercontent.com/12384665/82059264-73e46a00-96ce-11ea-84dd-6eb5398c6d6e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome, Version: 81.0.4044.138 (Official Build) (64-bit)
 - Browser: Firefox, Version: 76.0.1 (64-bit)

**Additional context**
It locks even when you don't change anything in the dialog.

**Comment by rhtyd** [comment]
@vladimirpetrov please re-test against master and close, thanks.

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
