### ISSUE TITLE
[BUG] Changing the project by using the project list icon doesn't change its name in the top of the screen

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#342]
**Describe the bug**
If you change the current project by using the icon in the project list (not the drop-down list at the top), it doesn't change the name there.

**To Reproduce**
1. Make sure you have more than one project. Go to Projects and use the icon at the first column of the table to change the project. Now look at the top drop-down box - it hasn't changed there

**Expected behavior**
The name of the project must be shown according to the current one.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82062030-2a961980-96d2-11ea-82cd-2a592e7d07c6.png)

![image](https://user-images.githubusercontent.com/12384665/82062202-6fba4b80-96d2-11ea-9add-b381b3c9d150.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov please re-test and close

**Comment by vladimirpetrov** [comment]
Fix confirmed, closing the issue.
