### ISSUE TITLE
[BUG] Read-only admin: Kubernetes ISOs are not forbidden

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#347]
**Describe the bug**
Even when logged in as read-only admin (with allowed only list* actions in the role), you're still able to enable/disable a Kubernetes ISO.

**To Reproduce**
1. Login as read-only admin user (admin role with only list* actions allowed).
2. Go to Images > Kubernetes ISOs. Now you can add a new ISO.
3. Click on ISO. The 'Update' and 'Delete' operations are also allowed.

**Expected behavior**
Read-only admin should not be allowed to add, edit or delete Kubernetes ISOs.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
Not reproducible

**Comment by rhtyd** [comment]
Ideally, the readonly admin rules must be :
![Screenshot from 2020-06-14 06-02-17](https://user-images.githubusercontent.com/95203/84582058-a1731f00-ae04-11ea-8e9f-b529953fe5c0.png)

The issue can come if there is no default deny all rule \*
