### ISSUE TITLE
 [BUG] Wrong tooltips on 'Kubernetes ISOs > selected ISO' screen

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#348]
**Describe the bug**
Both tooltips on Kubernetes ISOs > selected ISO are wrong.

**To Reproduce**
1. Go to 'Images > Kubernetes ISOs', then click on ISO and look at the action buttons' tooltips - both are 'Update Kubernetes Version', which is incorrect.

**Expected behavior**
Button should have proper tooltips, something like 'Edit' and 'Delete'.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82427087-4bbf8700-9a91-11ea-8aa8-e0c587d4db10.png)

![image](https://user-images.githubusercontent.com/12384665/82426960-27fc4100-9a91-11ea-948c-fce0982a13c7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
Fixed
