### ISSUE TITLE
[BUG] Read-only admin: delete Kubernetes ISO icon is still working

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#349]
**Describe the bug**
When logged in as read-only admin (with allowed only list* actions in the role), the delete Kubernetes ISO icon is active and working. 

**To Reproduce**
1. Login as read-only admin user (admin role with only list* actions allowed).
2. Go to Images > Kubernetes ISOs, then click on a volume and press the 'Destroy' icon. There will be an error message in a pop-up notification but the volume is removed from the list.

**Expected behavior**
The 'Delete' icon should be hidden and the operation forbidden when the user has no rights for this operation.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82430195-b07ce080-9a95-11ea-9847-eace31078cc5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
Similar to #346

**Comment by rhtyd** [comment]
not reproducible
