### ISSUE TITLE
[BUG] Read-only admin: domain operations are allowed

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#350]
**Describe the bug**
Even when logged in as read-only admin (with allowed only list* actions in the role), you're still able to add/delete domains.

**To Reproduce**
1. Login as read-only admin user (admin role with only list* actions allowed).
2. Go to Domains. Now you can create and delete domains even though you shouldn't be allowed. The domain is removed from the list and there is a neverending 'in progress' circle in the notification box.

**Expected behavior**
Read-only admin should not be allowed to add and delete domains.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82447241-b16f3b80-9ab0-11ea-99b3-b475fb6c3e02.png)

![image](https://user-images.githubusercontent.com/12384665/82447631-365a5500-9ab1-11ea-975b-2480e1c534a7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
We have the same behavior in the old UI.

**Comment by rhtyd** [comment]
Not reproducible
