### ISSUE TITLE
[BUG] Read-only admin can access VM consoles

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#352]
**Describe the bug**
Even when logged in as read-only admin (with allowed only list* actions in the role), you're still able to access VM consoles (VMs, system VMs, virtual router VMs ....) which might be dangerous.

**To Reproduce**
1. Login as read-only admin user (admin role with only list* actions allowed).
2. Go to some VM and click on 'View console' - you're able to see and even interact with all the consoles.

**Expected behavior**
I think read-only admin should not be allowed to interact with the consoles.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/82552204-5a2da180-9b6a-11ea-8514-df787116e812.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
@vladimirpetrov the console access is given; could be debated whether console access should be granted or not; this is not controlled by roles feature but if resource has any access for the logged in account.

**Comment by vladimirpetrov** [comment]
I raised this issue to start a discussion - @DaanHoogland also agreed with me that this doesn't look good from a security point of view.

**Comment by rhtyd** [comment]
@vladimirpetrov @borisstoyanov please discuss on dev ML, this is really a backend issue. Once backend has fix this, the frontend can follow (depending on listCapabilities or some other API response to show/hide console access).
