### ISSUE TITLE
[FEATURE] Add support for UI customisation

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#359]
- [ ] Add supporton branding the UI: logos, and theme (refer: https://www.antdv.com/docs/vue/customize-theme/)
- [ ]  Add user documentation on branding
- TBD - Introduce/use a config.js or config.json file for high level custom options (such as keyboards, configs etc.)

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel can you have a look at the issue of adding a theme for Primate. Ideally a json file that (1) Primate loads and applies, (2) the json/theme file does not get packed/bundled with rest of the code and is available say similar to index.html on the root `dist` directory. Same for any other branding logos/images.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel  In primate, the logo is a component. But under this mission, I will change it to custom, right?

**Comment by rhtyd** [comment]
I think what we can do is to move the logo (png and svgs) such that users can simply replace the files with their chose png/svg files after they use the dist/archive/deb/rpm used to install Primate

**Comment by rhtyd** [comment]
Related legacy UI for tracking - https://github.com/apache/cloudstack/pull/3258

**Comment by rhtyd** [comment]
Got a PR
