### ISSUE TITLE
[BUG] apt install fails to cleanup some files after installation due to permissions

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#367]
**Describe the bug**
Although installation is successful there's a warning message which indicates some files could not be deleted after install due to permissions. This is quite cosmetic issue and can be ignored to sunny days :) 

**To Reproduce**
1. Install primate of ubuntu as root

**Expected behavior**
installation succeeds without any error/warning

**Management server  (please complete the following information):**
 - OS: Ubuntu18.04

**Additional context**
```
root@ref-trl-977-v-Mu18-boris-stoyanov-mgmt1:~# apt install ./cloudstack-primate_0.5.0-20200528_all.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'cloudstack-primate' instead of './cloudstack-primate_0.5.0-20200528_all.deb'
The following NEW packages will be installed:
  cloudstack-primate
0 upgraded, 1 newly installed, 0 to remove and 96 not upgraded.
Need to get 0 B/3,674 kB of archives.
After this operation, 20.9 MB of additional disk space will be used.
Get:1 /root/cloudstack-primate_0.5.0-20200528_all.deb cloudstack-primate all 0.5.0-20200528 [3,674 kB]
Selecting previously unselected package cloudstack-primate.
(Reading database ... 106221 files and directories currently installed.)
Preparing to unpack .../cloudstack-primate_0.5.0-20200528_all.deb ...
Unpacking cloudstack-primate (0.5.0-20200528) ...
Setting up cloudstack-primate (0.5.0-20200528) ...
N: Download is performed unsandboxed as root as file '/root/cloudstack-primate_0.5.0-20200528_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

**Comment by rhtyd** [comment]
@borisstoyanov can you advise where and how did you test this? I couldn't reproduce it. Instead of direct deb, can you try installation after configuring a repo?

The error seems env specific, see similar https://askubuntu.com/questions/908800/what-does-this-synaptic-error-message-mean
