### ISSUE TITLE
[BUG] Fix translation usage across config and components and fix doclinks

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#369]
Translations from legacy UI (as of master, after 4.14.0.0 release) were migrated to Primate completely in: https://github.com/apache/cloudstack-primate/pull/368 (PR can be used for reference and audit purpose)

As part of the above PR, the translation keys were standardized and renamed as follows:
- Use a `label.` prefix (same as legacy UI to save devs from learning new conventions)
- If an API parameter is zoneid, then the translation key would be `label.zoneid` for auto-generated widgets/views to work - but this is not completely consistent as there are many custom components
- The keys were renamed, and the map of old-new keys are here: https://github.com/apache/cloudstack-primate/blob/master/src/locales/remove-after-tr-migration/primate-key-renames.json

The task for this effort are:
- [x] Search and fix usage of `$t(...` to use the correct keys as per the current en.json across components (git grep est. ~1400 lines)
- [x] Fix the `title` (~100 occurrences) in config/...
- [x] Fix the `label` (~250 occurrences) in the `config/...` to use the `label.xxx` keys instead of English strings
- [x] Fix English strings use in `:title`, `:label`, `:placeholder`, `message`, `description` with keys from en.json (these list of keywords can be searched using `git grep ... | grep -v locales`)
- [x] For action messages, introduce a new message in configs and use suitable translation key (see en.json for keys with `message...` key names, for example see https://github.com/apache/cloudstack-primate/commit/3b9ee63e836120dbaab0185689d46585dc7a8471)
- [x] Add doc links for all sections and actions in the config (refer http://docs.cloudstack.apache.org)
- [x] Some new components have introduced their own translation keys (see https://github.com/apache/cloudstack-primate/blob/master/src/locales/remove-after-tr-migration/new-keys-list.txt), find and replace usage with keys which are from old translation files and remove these new keys from en.json wherever possible

**Comment by rhtyd** [comment]
Refer: most migrated with some automation https://github.com/apache/cloudstack-primate/pull/370

**Comment by rhtyd** [comment]
Assigned to @davidjumani

**Comment by davidjumani** [comment]
Fixing in #371

**Comment by rhtyd** [comment]
Ref
https://github.com/apache/cloudstack-primate/blob/master/src/locales/new-locale-keys.txt

**Comment by davidjumani** [comment]
docHelp in #435

**Comment by rhtyd** [comment]
Only effort remaining is to check and fix the diff between locales/en.json and legacy UI's l10n/en.js

**Comment by rhtyd** [comment]
Largely work completed, review/verification would be user-led (with @rhtyd to do one round)
