### ISSUE TITLE
[FEATURE] a query component for text driven questions to a user

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#374]
**Is your feature request related to a problem? Please describe.**
When a user uploads an OVA template it might contain properties that require answering when deploying a VM based on that template. This is a concrete example but there might be others where the UI needs to query the user based on a text input. in the OVA deployment case we have
- a query
- a name
- a default value
- a type and
- a constraints field (called "qualifiers" internally)
I think a component might have more use than the OVA deployment. It can be used for cmdline parameters or more specific control of user-data input. Maybe for some plugins it could be used to control hardware specific configuration. I think it could even be useful for more static parts of the UI interaction.

**Describe the solution you'd like**
I would like a vue.js component that takes above input and can return the user choice or input (depending on type and constraints).

**Describe alternatives you've considered**
An alternative would be javascript methods as implemented in the old UI's instanceWizard. The amount of work would be the same but it would not be usable in multiple location but as boilerplate code.

**Additional context**
In the old UI a step 7.5 of sorts was put between step 7 and 8 of the deploy wizard in case an OVA would contain ovf properties. in the new UI this would be part of the deployment form (mistakenly called a wizard still).

**Comment by rhtyd** [comment]
The form AntD component can be used for this use-case to implement a component for the DeployVM component
https://antdv.com/components/form/

**Comment by rhtyd** [comment]
(we still call it a wizard as it has steps, the only difference in UX is that all the steps are visible and editable at once after a zone is selected)

**Comment by rhtyd** [comment]
Related: https://github.com/apache/cloudstack-primate/issues/358

**Comment by rhtyd** [comment]
Related: https://github.com/apache/cloudstack/pull/3271

**Comment by rhtyd** [comment]
With @shwstppr

**Comment by rhtyd** [comment]
Have PR #436 - let's track it there
