### ISSUE TITLE
[BUG] Can't "un-choose" the Zone/Pod/Host for the VM deployment

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#375]
**Describe the bug**

Once a specific Zone/Pod/Cluster/Host has been selected, there is no way to "unselect it" i.e. to make sure no specific is selected/chosen for the VM deployment.

![image](https://user-images.githubusercontent.com/45762285/83665042-28392800-a5cb-11ea-8f7e-bf88c4c4df0b.png)

**Comment by rhtyd** [comment]
@utchoang can you add a fix to display an empty/default option (say 'Default' or label.default?) for the zone, pod, cluster and host dropdown whose internal zone/pod/cluster/host ID is null (so effectively saying no zone/pod/cluster/host is selected). Old UI it looks like this:
![Screenshot from 2020-06-04 13-18-01](https://user-images.githubusercontent.com/95203/83729912-f3c67a00-a665-11ea-963e-4e3c9cef37bd.png)
