### ISSUE TITLE
[BUG] list of hosts not filtered based on the selected Cluster (during VM deployment)

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#376]
**Describe the bug**

Once a cluster is chosen for the VM deployment, when further selecting a destination host, only the hosts from the chosen cluster should be shown (but atm all hosts from all clusters are shown).

Probably same goes for listing other child entities (list of Pods from a Zone, list of Clusters from a Pod, etc)

![image](https://user-images.githubusercontent.com/45762285/83665364-9c73cb80-a5cb-11ea-9fb2-bf4426e431e4.png)

**Comment by rhtyd** [comment]
@utchoang can fix this, thanks.
