### ISSUE TITLE
[BUG] Rename "Disk Size" to "Root Disk Size" on the new Instance wizard

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#377]
A minor improvement request:

![image](https://user-images.githubusercontent.com/45762285/83665810-39ceff80-a5cc-11ea-91fa-1d7025928b46.png)

**Comment by rhtyd** [comment]
Simple label fix, @utchoang please fix this as well using `$t('label.root.disk.size')`
