### ISSUE TITLE
Add LDAP Account Form

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#39]
Add custom form under IAM->Account->Add LDAP account (in old UI, this is at: UI->Account->Add Ldap account button).

- Call the `listLdapUsers` with listtype=new to get list of LDAP accounts and show in the action form
- Call the `ldapCreateAccount` to create account based on listed account (see screenshot), if LDAP group is specified call the `importLdapUsers` API instead of `ldapCreateAccount`
- Old code reference: https://github.com/apache/cloudstack/blob/master/ui/scripts/accountsWizard.js#L250

![Screenshot from 2020-01-15 13-19-28](https://user-images.githubusercontent.com/95203/72415200-f6e5ca00-3799-11ea-9b90-58b383a1b373.png)
![Screenshot from 2020-01-15 13-20-19](https://user-images.githubusercontent.com/95203/72415202-f6e5ca00-3799-11ea-9fd9-1dacb1c5c750.png)

**Comment by DaanHoogland** [comment]
@rhtyd you need/want my involvement on these?

**Comment by rhtyd** [comment]
Hi @DaanHoogland yes it would be great, let's discuss tomorrow?

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel - I've added documentation on this task and configured LDAP server/config on the acs.shapeblue.com server that you can use to build this feature now. Let me know if you've any questions.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel As I can see from https://github.com/apache/cloudstack/blob/master/ui/scripts/accountsWizard.js#L171 there are two fields named samIEnable and samIEntity. But there is none of them on the UI. Is there any special condition for these two fields?

**Comment by rhtyd** [comment]
@utchoang yes, there is a SAML (a single-sign on feature) integration in the old UI. Maybe ignore/hold those logic/porting changes for now, let's revisit adding SAML support in future, for now you may keep it specific to LDAP only.

**Comment by rhtyd** [comment]
PR opened https://github.com/apache/cloudstack-primate/pull/116
