### ISSUE TITLE
Project View and Actions

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#41]
Projects:
- [x] Project view and Project dashboard 
- [x] Projects: delete/list project accounts etc.
- [x] Project invitations: list/delete/update

**Comment by rhtyd** [comment]
I'll update the requirements/screenshots and details on this issue this week soon.

**Comment by svenvogel** [comment]
@rhtyd @utchoang will proceed with this task. do you have some more information?

**Comment by rhtyd** [comment]
I can more details in the next 1-2 hours, basically we want all the project tabs/features as in the old UI @svenvogel

**Comment by utchoang** [comment]
1. Please find my suggested UI for Project Accounts and Project Invitations. I'd like to have your comments.
![project_1](https://user-images.githubusercontent.com/13766648/70879100-b8bc8580-1ff6-11ea-843e-17a3dda57aee.png)
![project_2](https://user-images.githubusercontent.com/13766648/70879101-bb1edf80-1ff6-11ea-96e3-c20ed09433b9.png)

2. Could you please explain how permissions to view Project Accounts and Project Invitations are granted?

3. For the list of Project | Invitations as below, there are two options when selecting view:
![project_old_ui](https://user-images.githubusercontent.com/13766648/70879141-df7abc00-1ff6-11ea-8bf3-a9b07254a059.png)

- Add "Select view" UI similar to the old UI
- Add new tab in listview
What would you think is the better option? Or if you have other idea, please let me know

**Comment by rhtyd** [comment]
Hi @utchoang cc @svenvogel - thanks for the screenshots. 

1. The accounts tab looks good to me and the pagination as well. The project level action/button to add user to a project also looks good. However, the invitation needs to be implemented as a different top-level view (or maybe in additional to the tab) because a user who will get a project invitation won't be able to see the tab or invitation. Therefore, please implement a button in the main project list view which when clicked can show a modal/pop-up which can show this tab, i.e. list all the project invitations and allow a user to list/delete/update the project invitation.

2. Only the project admin maybe shown the tab/ability to add/remove and become the project owner. A project admin can add other accounts using the addAccountToProject API, and similarly can list and delete accounts from a project. For this, the best way would be to see how's it's done in the old UI (see for reference if this helps - https://github.com/apache/cloudstack/blob/master/ui/scripts/projects.js#L469). The API permission, i.e. which user type is allowed to calls the API is granted via CloudStack roles where we define a role to have rules/permissions that says which APIs are allowed or not. All accounts belong to a role. Let me know if you've further questions or have I confused you already?

3. See (1.), the project invitations can be shown and implemented as a action component (modal/pop-up) that simply lists all the invitations for the user/account and allow user/account to delete and update an invitation.

Other requests - maybe if we can show a badge (similar to global notifications) to show number of available/pending invitations for a user.

Let me know if you've any questions or need any further clarification.

**Comment by utchoang** [comment]
Hi @rhtyd 
Regarding to (1), I understand that there is no Invitation tab in project. Am I correct? In the old UI, I noticed that this tab is available to show users who are invited to a project
![project_invitations](https://user-images.githubusercontent.com/13766648/70971142-d7904a00-20d2-11ea-84bd-ba4ea9ce7d0c.png)
