### ISSUE TITLE
[BUG] Create guest networks, network types displayed as labels 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#414]
**Describe the bug**

**To Reproduce**
1. Go to Networks
2. Click on Create Guest networks

**Expected behavior**
We see labels instead of Network types

**Screenshots**
![Screenshot 2020-06-11 at 15 56 06](https://user-images.githubusercontent.com/13551960/84387690-11fb1f80-abfc-11ea-9012-30ff845306c4.png)

**Additional context**
Same as shared, isolated and L2 should not be displayed with labels

**Comment by borisstoyanov** [comment]
![Screenshot 2020-06-11 at 15 57 20](https://user-images.githubusercontent.com/13551960/84387835-4a9af900-abfc-11ea-8485-6b983a5474ca.png)
Further down there seems to be more labels to be fixed

**Comment by rhtyd** [comment]
We've a general code-base wide PR for fixing the translation keys @borisstoyanov - I'll ask you to retest after those PRs are merged. Thanks.

**Comment by rhtyd** [comment]
Fixed on latest
