### ISSUE TITLE
[BUG] Missing User project invitations

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack-primate#415]
**Describe the bug**
Project Invitations are missing in Primate

**To Reproduce**
1. As admin create a new project
2. Add a user account to the new project
3. Login as user account
4. No info dialog for project invitation is shown and Inviations option is missing form Projects page/section

**Expected behavior**
Project invitation should be visible as old UI. Screenshots added in the description

**Screenshots**
Old UI
![Screenshot from 2020-06-12 16-43-57](https://user-images.githubusercontent.com/153340/84497298-23136180-accc-11ea-957e-33548f846fcc.png)

![Screenshot from 2020-06-12 16-43-21](https://user-images.githubusercontent.com/153340/84497301-23abf800-accc-11ea-94ef-2e6072ef5bb4.png)

**Desktop (please complete the following information):**
Master on QA server

**Comment by Pearl1594** [comment]
@shwstppr I believe the project invitations feature exists. Created a user account and added account to project. On logging into the user account I do see the list of invitations. There however is no indication(such as a badge - or something along those lines indicating pending invitations)

![image](https://user-images.githubusercontent.com/10495417/84498076-8ea9fe80-accd-11ea-85a1-98df5182cf89.png)

**Comment by shwstppr** [comment]
@Pearl1594 my bad! Closing the issue
