### ISSUE TITLE
[BUG] Links not found

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack-primate#420]
**Describe the bug**
All the links under https://github.com/apache/cloudstack-primate#primate-development are not accessible

**To Reproduce**
1. Click on any of the link under the section https://github.com/apache/cloudstack-primate#primate-development

**Expected behavior**
A nice documentation :)

**Comment by rhtyd** [comment]
@ravening intentional, need to update the docs; the best place to start is vuejs v2 guide.
They are here, I'll update links
https://github.com/apache/cloudstack-primate/tree/master/docs
