### ISSUE TITLE
[FEATURE] VM deployment suggestion: ask for #num of VMs

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#427]
Gist - user report is asking for:
~- Quick view actions in list view~ See #458 
- Ability to specify number of VMs in VM deployment form

Original report:
~1) Allow to create a site to site vpn to a regular isolated network instead of just a vpc. right now site-to-site vpn is only allowed to a vpc.~ Not a UI issue
2) action buttons on virtual machines from the instance tab. right now users are only allow to take actions(shutdown, delete, etc) on virtual machines after clicking on the virtual machine.
3) create multiple virtual machines from the VM creation form. ask me how many virtual machines I want to create from a single virtual machine creation form.

apologies if this isnt clear enough. not very good at putting my thoughts in writing.

**Comment by rhtyd** [comment]
@gaaray2k thanks for reporting;
1. you're asking for a new backend feature, Primate is UI only. You can raise a ticket here https://github.com/apache/cloudstack/issues and discuss your proposal on the dev mailing list.
2. The group action feature is already created towards the 1.0/GA milestone - https://github.com/apache/cloudstack-primate/issues/162
Or, are you suggesting a quick/action overview feature like the legacy UI?
3. I think I get the last one, you're asking something to ask number of VMs in the form to deploy.

**Comment by gaaray2k** [comment]
I would like to see action buttons next to the virtual machine in the instance tab instead of having to click on The VM to turn off, reboot, etc.

**Comment by gaaray2k** [comment]
Also when creating the vm, the form should ask for the name and then append a number depending on how many VMs I choose to create from a template. That feature is in openstack.

**Comment by rhtyd** [comment]
@gaaray2k for the last suggestion, if you need more than one VM - why not use API (use cmk) to automate large VM deployment? Do you by chance know any such use-case (asking out of curiosity) in cloud providers such as aws, gcp, azure etc where they give such an option? Lastly, in case we allow number of VMs to be specified should we ask for numbering pattern (like VM-name$counter) ?

**Comment by rhtyd** [comment]
For #2 we're exploring a quick-view like feature to allow users to take action without getting into the VM view in https://github.com/apache/cloudstack-primate/pull/458

**Comment by gaaray2k** [comment]
I could use cmk but I think UI option would be useful too. I know openstack has it. The way I see it in openstack is you provide a name and then a number is attached at the end of that name. No big deal. I just think it is a nice feature.
