### ISSUE TITLE
Assign a public IP to a VPC guess network

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#438]
I havent been able to assign a public IP to a vpc guest network in the new UI. in the old UI when creating a new load balancer, I would get the option to assign the ip to a tier. I dont see that option in the new UI so when creating a load balancer on the public IP, I get the error 

'IP address ID=236 is not associated with any network'

how do I accomplish this in the new UI?

**Comment by rhtyd** [comment]
@gaaray2k can you list the exact steps you use on the old UI?
In Primate, in the VPC there's a public IP address tab which can be used to acquire IP address and then used for doing PF/LB or snat. Are you not seeing them?

**Comment by gaaray2k** [comment]
I am able to acquire a public IP. But can't create a load balancer because the VIP cannot be assign to a tier in the new UI. In the old UI the user acquires an IP, select the tier the LB will belong to and then select the VMs from that tier to be part of the load balancer. There is no tier option in the new UI when creating a load balancer on a VPC

**Comment by rhtyd** [comment]
@gaaray2k is your issue not being able to select a tier while adding PF/LB rules, like https://github.com/apache/cloudstack-primate/issues/333 ?

With @shwstppr

**Comment by gaaray2k** [comment]
Yes

**Comment by rhtyd** [comment]
@gaaray2k fixed on master, please test/review latest master. Thanks.
