### ISSUE TITLE
[BUG] role id displayed as label when creating an account

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#447]
**Describe the bug**
Label for role id displayed, should be just Role I believe

**To Reproduce**
1. Go to accounts
2. Click on Add account 

**Expected behavior**
label should not be displayed

**Screenshots**
![Screenshot 2020-06-23 at 12 31 31](https://user-images.githubusercontent.com/13551960/85387586-ac892600-b54d-11ea-8bc6-642d316c3d70.png)

**Additional context**

**Comment by rhtyd** [comment]
Thanks bobby, we have a PR already to fix the accounts form for ldap/saml etc with proper labels and help docs (the (i) icon to show help doc)
https://github.com/apache/cloudstack-primate/pull/170

**Comment by rhtyd** [comment]
Abhishek's PR fixed it, closing.
