### ISSUE TITLE
[BUG] After session expire, upon new login user is given 403

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#456]
**Describe the bug**
After session expire and following log, user is being displayed with 403 instead of the resource he had just authenticated to. 

**To Reproduce**
1. Let the session expire while on a page
2. Click anywhere on the screen
3. You're being redirected to login, login to CS
4. Instead of the page you've clicked before login you've been displayed with 403

**Expected behavior**
User should be redirected to the page where he was last

**Comment by rhtyd** [comment]
@borisstoyanov can you test latest master (or latest build of PR where you saw this). This has been fixed now; so after a fresh login users are always taken to the dashboard.

**Comment by rhtyd** [comment]
Limitation - because we rely on API autodiscovery, after re-login we cannot directly take to the view before the API discovery finishes. For now, we direct the page to dashboard. If you change the request of the issue, we can make it as a potential usability enhancement for 1.1.

**Comment by rhtyd** [comment]
With @davidjumani - send a PR to fix or close on test confirmation.

**Comment by davidjumani** [comment]
On logout / session expired, post login, user lands on the dashboard

**Comment by borisstoyanov** [comment]
but if you have a URL leading you to some particular page you should be landing on that page when login, right ?

**Comment by Pearl1594** [comment]
with autodiscovery, there are some paths that get discovered after a delay, as a result of which the instant the user logs in that path doesn't exist and hence leads to a 403. So to overcome that, the user is now redirected to the dashboard page.

**Comment by rhtyd** [comment]
I'll explore a fix but this is not priority for GA

**Comment by rhtyd** [comment]
Let's continue the discussion on https://github.com/apache/cloudstack-primate/pull/460 @borisstoyanov I've reviewed, tested and verified the fix by @davidjumani under a few scenarios - need you feedback on the UX/usability. Thanks.
