### ISSUE TITLE
Account Certs Tab

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#46]
Add a new Certificates tab in the account detail view, it should support apis to list/add/delete (listSslCerts, uploadSslCert, deleteSslCert)

Reference screenshot from old UI:

![Screenshot from 2019-12-03 22-34-45](https://user-images.githubusercontent.com/95203/70072589-4a9eb880-161d-11ea-98f7-c49caaa4e68f.png)
![Screenshot from 2019-12-03 22-34-52](https://user-images.githubusercontent.com/95203/70072592-4a9eb880-161d-11ea-9c71-9ebc4d87765b.png)

Also check and compare and implement any missing detail or action by comparing the old UI vs the new UI, except for the settings tab which is done in #26

**Comment by rhtyd** [comment]
I'll update the requirements/screenshots and details on this issue this week soon.

**Comment by svenvogel** [comment]
old view

![image](https://user-images.githubusercontent.com/5433844/70060676-4b1a5d80-15e3-11ea-9e9a-4854420ae345.png)

**Comment by rhtyd** [comment]
@svenvogel no, not that. The SSH keypair is already implemented and is under the compute navigation group now. I've updated the ticket with details now.

**Comment by rhtyd** [comment]
Once this issue's PR is up, I'll add details on https://github.com/apache/cloudstack-primate/issues/41

**Comment by utchoang** [comment]
@rhtyd @svenvogel 
This is the UI I sketched for accounts. 
Could you please review and give me your comments, especially for the group of domains
![account_tree](https://user-images.githubusercontent.com/13766648/70402010-7d551080-1a64-11ea-94b4-6f20b7f585d5.png)

**Comment by svenvogel** [comment]
@rhtyd do you mean your pictures? we need to add the new certs tab right?

**Comment by rhtyd** [comment]
@utchoang - no need for this as we've got your tree-based domain PR merged. What we want with this ticket is to allow users to upload certificates to their accounts. See the original issue description: https://github.com/apache/cloudstack-primate/issues/46#issue-528894680

**Comment by utchoang** [comment]
@rhtyd I got it, then I will move to the cert tab

**Comment by utchoang** [comment]
@rhtyd @svenvogel 
- Please review the UI for certificate tab and let me know your comments.
![certificate](https://user-images.githubusercontent.com/13766648/70502884-9b01a300-1b54-11ea-929b-2a8208a55e18.png)

- In the form for adding certificate, I cannot add a new one and show the list as there are some info missing such as Certificate and Private Key 
![add_cert](https://user-images.githubusercontent.com/13766648/70502912-b5d41780-1b54-11ea-988c-bc8052d35113.png)

**Comment by rhtyd** [comment]
Send a PR @utchoang I can see/review what the issue is
