### ISSUE TITLE
Complete user and dev documentation for 1.0/GA

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#464]
- Write user doc wrt installation, upgrade, basic and adv. customisation; send WIP release notes doc PR
- Write developer docs for:
  - Document core Primate architecture (router configs, store, locales, autogenview, list/resource view)
  - Tutorial-led on how to write a new UI feature (action, tab component; list/resource view) for Primate

**Comment by rhtyd** [comment]
With @rhtyd

**Comment by rhtyd** [comment]
Added blocker as GA/1.0 release cannot go without docs

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/blob/master/docs/customize.md
config.json in repo/public path

**Comment by rhtyd** [comment]
docs page: https://github.com/apache/cloudstack-documentation/blob/master/source/installguide/primate.rst

**Comment by rhtyd** [comment]
Scope of adv customisation:
- Change the router/config sections/js files with columns, name, icons, etc.
- Build/package

**Comment by rhtyd** [comment]
User docs with @Pearl1594

**Comment by davidjumani** [comment]
Write user doc wrt installation, upgrade, basic and adv. customisation; send WIP release notes doc PR - https://github.com/apache/cloudstack-documentation/pull/142

**Comment by rhtyd** [comment]
Let's continue on respective PRs
