### ISSUE TITLE
Logged in from event to use x-forward ip 

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#471]
When I log into primate an event is recorded saying "user USER logged in from IPADDRESS". this is a problem for users that use a proxy or load balancer because the ip will always be the the ip of the load balancer or proxy. can a system config option be added to use the IP address of the x-forward header so the real ip of the user is shown instead when using a proxy or load balancer?.

**Comment by rhtyd** [comment]
@gaaray2k this is not a UI issue, please log against apache/cloudstack repo; I think X-Forwarded-Host is already supported
