### ISSUE TITLE
[BUG] Template Status data not relevant to non admin users

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#476]
**Describe the bug**

**To Reproduce**
1. Log in as non-admin user
2. Go to Images -> Templates
3. see that the status column is either BLANK (created by others) or showing status from DB.

**Expected behavior**

The status is not relevant once there are multiple storage pools, there is no reason to show it.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/86151363-8be54100-baf6-11ea-895c-27c27ec33021.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
Make sense, @davidjumani please check legacy UI for "Domain Admin" and "User" accounts, and remove status column from the listviews of both template and ISOs and the zonetemplate/zoneiso tab components. I did a quick check as a normal User role/account and I see no status information being returned, so it's safe to remove this column at least for the "User" roletype.

With @davidjumani

**Comment by rhtyd** [comment]
With @Pearl1594
