### ISSUE TITLE
[BUG] Prompt regarding Data Volumes shown when destroying a VM is misleading

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#477]
**Describe the bug**

When destroying an instance the user should be shown any data disks attached and given the option to delete them.

**To Reproduce**
1. Create a VM (without a data disk)
2. Click on 'Destroy' the VM 
3. See the prompt (compare to Legacy UI)

**Expected behavior**

The prompt should read 'Data Volumes to be deleted:'  (incorrect mapping used - should be "label.delete.volumes")
When there are no Data volumes attached, the label "label.volume.empty" should be used ("No data volumes attached to this VM")

**Screenshots**

Primate:
![image](https://user-images.githubusercontent.com/4810220/86153240-44ac7f80-baf9-11ea-9a4b-6fc4edc2828e.png)
Legacy:
![image](https://user-images.githubusercontent.com/4810220/86153335-6c034c80-baf9-11ea-923e-c1d8a27fb2f2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
@davidjumani please create a new custom component for this action; the autogenerated widget will limit the UX which users may not like, like @PaulAngus 's expected behaviour.

**Comment by rhtyd** [comment]
With @davidjumani
