### ISSUE TITLE
[BUG] Backup tab is shown when Backup Framework is not enabled

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#487]
**Describe the bug**

A 'Backup' tab is shown under storage when the Backup Framework has not been enabled.  This will cause many 'support calls' when users want try to create backups.

**To Reproduce**
1. Ensure backup framework is not enabled
2. Click on 'Storage' tab

**Expected behavior**

The backup tab should not be visible as the backup framework is not enabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/86508620-68ade080-bdd9-11ea-8296-356b1c32797f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
With @davidjumani 
- Remove the view backup and vmsnapshot button via config::related for compute.js
- Instead add tabs to the VM instance/detail component to show/hide both backup and vm snapshots (similar to the volumes, nics etc tabs) depending on user-role access and availability of feature

@PaulAngus Lowering severity to Major, we'll fix the issue for 1.0/GA but let's use blocker limited to issues where a feature is broken (i.e. does not work, than a visibility/usabilty issue)

**Comment by PaulAngus** [comment]
A release blocker is an issue that must be fixed prior to a release.  therefore blocker is the correct category.

Requiring the operator to hide the feature is not acceptable.  the kubernetes plugin tab is only visible when the kubernetes plugin is enabled.  The same should be true for the backup plugin.  The operator should not have to fix inadequacies in ACS code.

**Comment by rhtyd** [comment]
@PaulAngus I've already said show/hide "depending on user-role access" and "availability of feature" so why is that unacceptable? Why is this a release blocker?

**Comment by rhtyd** [comment]
Legacy UI also show the backups view and offering even when the feature is disabled globally and for all zones
![Screenshot from 2020-07-06 14-09-25](https://user-images.githubusercontent.com/95203/86573648-53c87d00-bf92-11ea-9548-7c72a7d7a54d.png)

Using http://docs.cloudstack.apache.org/en/latest/adminguide/backup_and_recovery.html as a reference, if the feature is not globally enabled (backup.framework.enabled) then it must not be considered enabled; therefore the feature is considered enabled for a zone when it's globally enabled and enabled for a zone https://github.com/apache/cloudstack/pull/4202
This will fix exporting the APIs, if feature is disabled it won't export APIs and clients such as cmk, Primate won't show APIs or views.

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by PaulAngus** [comment]
Viewed PR on-screen with DJ - fix LGTM
