### ISSUE TITLE
[BUG] 'Expunging' VM Snapshots show in the UI

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#488]
**Describe the bug**

**To Reproduce**

Pre-req:
VM snaphot in expunging state must exist.

1. Go to 'storage' > 'VM Snapshots'
2. See error

**Expected behavior**

VMs in 'Expunging' state are not expected to be seen.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/86508715-2f29a500-bdda-11ea-8db7-9bf791bd0c19.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
I tested this is not a UI issue but a potential cleanup/GC issue, I've logged an issue here instead https://github.com/apache/cloudstack/issues/4201
Legacy UI shows the same:
![Screenshot from 2020-07-05 07-26-37](https://user-images.githubusercontent.com/95203/86523916-2ea01580-be91-11ea-9935-3686b62023f1.png)

Primate screenshots as admin and normal user:
![Screenshot from 2020-07-05 07-25-39](https://user-images.githubusercontent.com/95203/86523914-2cd65200-be91-11ea-87be-4f4bec07f1c1.png)
![Screenshot from 2020-07-05 07-26-18](https://user-images.githubusercontent.com/95203/86523915-2e077f00-be91-11ea-9909-b81c83e70ed0.png)
