### ISSUE TITLE
[BUG] The default number of entries in the data/table view (10) is a waste of screen space and frustrating

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#489]
**Describe the bug**

[Ack: as much usability as a bug]

EVERYTIME i use primate I have to change the number of items displayed to make reasonable use of screen space.
It quickly becomes frustating.

Some experiementation shows that a default around 17 suits most display screens.   15 is 'safe' but still often leaves quite a bit of empty screen space.

**To Reproduce**
Log in and goto any screen where you have more than 10 entities.

**Expected behavior**

'Better' use of available screen area.

dynamically setting the initial number of items to match the screen size would be most awesome, but failing that, a better default is desirable.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/86509626-41f3a800-bde1-11ea-86f7-44d38e3b4bbe.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
We had this initially set to 20 to match old UI, then 15 previously and we set this to 10 after getting complains from laptop users which may not have FHD/4K displays. The best strategy I can come up with is to set the default pagesize based on screen types; for mobile/table users keep it to 10 by default and for desktop users keep it to 20 by default.

Screenshots:
FHD (1920x1020)
![Screenshot from 2020-07-05 07-15-58](https://user-images.githubusercontent.com/95203/86523823-cdc40d80-be8f-11ea-8d5b-d17bdfbe97ed.png)
Laptop/tablet user:
![Screenshot from 2020-07-05 07-16-54](https://user-images.githubusercontent.com/95203/86523824-cf8dd100-be8f-11ea-8d39-8f45676b0b5b.png)
