### ISSUE TITLE
[BUG] Create VM Form - root disk size dialog is misleading

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#490]
**Describe the bug**

The implementation of the root disk slider suggests that the user MUST set a root disk size. This has two problems:

1. This is not the case and setting a root disk size is conpletely optional and not always possible.
2. User will not know the original root disk size, and setting a root disk size smaller than the original disk will fail the deployment.

**To Reproduce**

1. Log in as: User
2. Go to 'Create Instance'
3. Select any zone
4. See Root disk slider

**Expected behavior**

A clear indication that this is optional is required.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/86509967-deb74500-bde3-11ea-81b7-69ea9f5f1aa5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
With @davidjumani 
- listTemplates returns `size` check and use that to validate root disk size (must be equal to or greater than template size/physical size)
- Remove slider, keep it simply a number input
- Perhaps discuss and add a switch to say override root disk size and then show the label/input (i.e. don't show it by default, a toggle/switch shows the input)

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by PaulAngus** [comment]
reviewed on-screen with DJ - fix  LGTM
