### ISSUE TITLE
[BUG] The Create Instance wizard should have an 'Advanced section' to make requirements clear

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#491]
**Describe the bug**

The Create Instance wizard should have a number of options moved to an optional 'Advanced' section, their existence in the 'main flow' is confusing even to experienced users, deployment would be near impossible for new users.

**To Reproduce**

 Example:  What should a user enter for 'root disk size'  (link to #490 )

**Expected behavior**

The following should be in a clearly optional advanced section.
'root disk size'
'Affinity groups'
'Boot type'
'boot into hardware setup'
'boot mode'
'keyboard language' (as redundant with novnc console)
'userdata'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
Needs further discussion: cc @davidjumani 

- 'Affinity groups' is already in its own step, the sequence/step is same as old UI's wizard after compute and disk offering, we probably can move it at the end?
![Screenshot from 2020-07-05 07-42-14](https://user-images.githubusercontent.com/95203/86524053-395baa00-be93-11ea-88b1-14e149890150.png)

- 'root disk size': already tracked by another ticket, best case we may h is still used in backend while setting the 
 is still used in backend while setting the 
ide it if not applicable and perform size related validation; hide it by default (i.e. ask user for explicit override option by providing a switch)

- The following are same as in the legacy UI asked at the last step. The keyboard option is still used to set the default keymap for VMware/vnc config for VM (https://github.com/apache/cloudstack/blob/master/vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java#L576) if not in CloudStack console proxy/popup. Possibly we can add a 2nd last step to say 'Advanced Configuration' for the following? However, userdata has been there for years and may not be an advanced setting? Should the advanced step be visible to normal users?
```
'Boot type'
'boot into hardware setup'
'boot mode'
'keyboard language' (as redundant with novnc console)
'userdata'
```

- For each step we probably want to add an information (a (i) icon) that shows popover help doc (like other forms) to either explain the step or a specific form-item in the step using translation keys `$tr(...`

Screenshots for reference:
![Screenshot from 2020-07-05 07-49-24](https://user-images.githubusercontent.com/95203/86524121-21d0f100-be94-11ea-9c64-083ccdd465f0.png)
![Screenshot from 2020-07-05 07-49-38](https://user-images.githubusercontent.com/95203/86524123-239ab480-be94-11ea-803a-72a5fe66a830.png)

We'll fix this for 1.0, but given the VM deployment feature/functionality is not broken but is the steps/form items are same as old UI I've lowered severity to Major.

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by PaulAngus** [comment]
My thoughts:
We are past the point that simply being able to see a parameter in the UI is enough.  At GA, the new UI needs to be 'great/good/acceptable' in its own right.  Part of Primate's purpose is to improve the user's experience; And in some cases (the create VM instance wizard) it makes the experience worse.

**Comment by PaulAngus** [comment]
Viewed PR with DJ on-screen - LGTM
