### ISSUE TITLE
Error when renaming a template

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#492]
I get the error message below when I try to rename a template from a non admin account. I guess the UI is trying to set the routing parameter although I am not selecting it. just wanted to let you guys know in case you didnt know already.

request failed(531)
Parameter isrouting can only be specified by a Root Admin, permission denied

**Comment by rhtyd** [comment]
Thanks for reporting @gaaray2k I could reproduce and fix the issue
