### ISSUE TITLE
Resource update isnt working

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#495]
found another issue. When updating the limit count for an account and click on the update resource count button, nothing happens. for example, I tried to change snapshot limit for an account to 2, but when I press the update resource count button, the snapshot count stays at 20. I did it with the old UI and it works, but not in primate.

**Comment by rhtyd** [comment]
Hi @gaaray2k thanks for reporting, but I'm unable to reproduce. Which CloudStack version were you testing this against? Can you try with latest 4.14 version or branch build and with latest Primate master?

![Screenshot from 2020-07-06 14-02-12](https://user-images.githubusercontent.com/95203/86573100-845be700-bf91-11ea-903c-a59cecc34483.png)
![Screenshot from 2020-07-06 14-02-25](https://user-images.githubusercontent.com/95203/86573103-86be4100-bf91-11ea-8838-4086aebc653f.png)
![Screenshot from 2020-07-06 14-03-00](https://user-images.githubusercontent.com/95203/86573105-8756d780-bf91-11ea-9de6-75bd8c7fb321.png)

**Comment by rhtyd** [comment]
@gaaray2k were you in a project (i.e. you've selected a project from top menu) when you tried this?

**Comment by gaaray2k** [comment]
No I wasn't. I went to account and was trying to set the limit from there. I will try again and report back.

**Comment by Pearl1594** [comment]
@gaaray2k update resource count merely refreshes the count of resources (used) for the corresponding resource types in that account. I believe what you trying to achieve - i.e., update resource limit can is done by hitting the submit button at the bottom of that page -> that updates the resource __limits__
