### ISSUE TITLE
Register ISO Action

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#50]
- [x] ISO register with multi-zone by URL

![Screenshot from 2019-12-24 14-43-57](https://user-images.githubusercontent.com/95203/71405612-fb680880-265b-11ea-8110-2d6502dc805f.png)

**Comment by rhtyd** [comment]
@utchoang /cc @svenvogel could you pick this one up as the next task. Let me know if you've any question.

**Comment by rhtyd** [comment]
For example on how to add a custom action form, you can see: https://github.com/apache/cloudstack-primate/pull/69/files

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I would like to have clarification for "multi-zone". Is it to either:
1. Select multiple options? 
![zone1](https://user-images.githubusercontent.com/13766648/71467027-05bd0a80-27f4-11ea-903c-c4c6ea545e55.png)

Or
2. Select option "All zones"?
![zone2](https://user-images.githubusercontent.com/13766648/71467037-0a81be80-27f4-11ea-8734-1f982e2b3f6c.png)

As far as I can see, api registerIso only accepts parameter 'zoneid', so I suspect (1) may not be correct

**Comment by svenvogel** [comment]
@utchoang @rhtyd what do you think?

i would prefer this one?

![image](https://user-images.githubusercontent.com/5433844/71475894-a3a7d980-27e2-11ea-8898-d368228a3ced.png)

Question: if we select "like the old ui" "All Zone" and an additional zone whats happen?

**Comment by rhtyd** [comment]
For multi-zone select, that looks good. We'll need to check if for this zone multi zone should be allowed, check the API?

**Comment by svenvogel** [comment]
@rhtyd what i see is that we only have a zoneid which is required.
![image](https://user-images.githubusercontent.com/5433844/71478476-2e430580-27f0-11ea-9541-3e4432090ee8.png)
you mean we need to check if more than one selected or "All Zones" we have different API calls. Right?

**Comment by rhtyd** [comment]
Okay, so in case of ISOs we only take a single zoneid or for all zones pass some magic number (like zoneid=-1, this can be checked against old UI).

**Comment by svenvogel** [comment]
@rhtyd okay sounds good. @utchoang should that help you?

**Comment by utchoang** [comment]
@rhtyd @svenvogel OK. I understood
