### ISSUE TITLE
[BUG] Unable to view project tags in the project details for User account

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack-primate#500]
**Describe the bug**
Unable to view project tags in the project details for User account. In Old UI, can view and add tags for the project, the same is not available for the same account in Primate.

**To Reproduce**

1. Log in as a User
2. Change project from Default View
2. Go to 'Projects'
3. Click on any project to see project details and check tags.

**Screenshots**

Primate UI =>
![Primate-UI](https://user-images.githubusercontent.com/12028987/86761749-cfdec580-c063-11ea-9a80-bfd765bb7b98.png)

Old CloudStack UI =>
![OldCS-UI](https://user-images.githubusercontent.com/12028987/86761802-da995a80-c063-11ea-992b-391403c6f9e1.png)

**Expected behavior**
Project tags should be shown and provision to add tags based on the permission.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari / Chrome
 - Version 13.1.1 / 83.0

**Comment by rhtyd** [comment]
@sureshanaparti were you an account added to the project, I couldn't reproduce the error. For project where you've access you'll be able to add/remove/list tags.

**Comment by sureshanaparti** [comment]
> @sureshanaparti were you an account added to the project, I couldn't reproduce the error. For project where you've access you'll be able to add/remove/list tags.

@rhtyd I checked in Chrome browser as well, changed project to other than Default View and tried to access projects and couldn't see the tags in the Primate UI. Able to see tags for the same project in Old UI, with same user in the same project view.
