### ISSUE TITLE
[BUG] Detail settings (for templates and instances) lets you create settings with null values

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack-primate#502]
**Describe the bug**

- [x] Detail settings (for templates and instances) lets you create settings with null values. (make fields mandatory)
- [x] Edit template lets you set / unset if the template is ssh key enabled, but this information doesn't seem to be exposed as part of the details (Legacy UI didn't expose modification of this property , hence it wasn't displayed)
- [x] In list templates view, Domain Admin doesn't have an 'All' templates view filter

**Comment by rhtyd** [comment]
With @davidjumani
