### ISSUE TITLE
Show Password after deploying VM

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#51]
On VM deployment show message with new password. This works for VM start and VM reset already.

**Comment by DaanHoogland** [comment]
I'd like to reopen @rhtyd . I fix was merged in December but I encountered this missing on a branch I created from master in april.

**Comment by DaanHoogland** [comment]
![Screenshot from 2020-04-24 13-11-31](https://user-images.githubusercontent.com/2486961/80217654-946d5700-862f-11ea-9dec-6edc094db930.png)

That is the old UI. The new one only briefly shows succes on the same installation with the same parameters. It show to short a period to even capture it.

**Comment by rhtyd** [comment]
@utchoang can you check/fix the deployment wizard to show the VM password if VM has a password enabled template. The password is returned by the VM response `json.virtualmachine.password`. This is already fixed for start VM and reset VM actions.

**Comment by rhtyd** [comment]
PR is there for tracking, closing this.

**Comment by vladimirpetrov** [comment]
Fix confirmed, working fine.

![image](https://user-images.githubusercontent.com/12384665/81391522-e4671600-9125-11ea-8c1e-f284652866b9.png)
