### ISSUE TITLE
New list resource tab does not do pagination and refresh on parent resource refresh

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#512]
@davidjumani please address for the new list resource tab used in vmsnapshots/backups tabs for VM instance:
- Add a watch on resource, refresh the view if parent resource changes (i.e. refresh button)
- Add pagination option for the API (see rick account in primate-QA which has over 35 backups for testing)

**Comment by Pearl1594** [comment]
@blueorangutan package
