### ISSUE TITLE
[TESTPLAN] Full Test Plan for 1.0/GA for USER/Domain Admin, ESXi 67u3, ACS 4.14/latest

### ISSUE THREAD

**Issue by alexandremattioli** [apache/cloudstack-primate#519]
Note: for User role test exclude after Account/User feature, for DomainAdmin role exclude after Infrastructure (except for Offerings)

**Common**
- [x] Project selector
- [x] Language selector
- [x] Notifications / clear notifications
- [x] Paginations
- [x] Profile
- [x] Help
- [x] Logout
- [x] Context-sensitive help

**Dashboard**
- [x] Fetch latest
- [x] View hosts in alert state
- [x] View alerts
- [x] View events

**Compute > Instances**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Filter by
- [x] Create new instance

**Compute > Kubernetes**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Filter by
- [x] Add Kubernetes cluster
- [x] Start/stop a Kubernetes cluster
- [x] Scale Kubernetes cluster
- [x] Upgrade Kubernetes cluster
- [x] Delete Kubernetes cluster

**Compute > Instances > selected instance**
- [x] View console
- [x] Reboot instance
- [x] Update instance
- [x] Start/Stop instance
- [x] Reinstall instance
- [x] Take snapshot
- [ ] Assign VM to backup offering
- [x] Attach ISO
- [x] Scale VM
- [x] Migrate instance to another host
- [x] Change affinity
- [x] Change service offering
- [x] Reset Instance Password
- [x] Assign Instance to Another Account
- [x] Network adapters
- [x] 	- Add network to VM
- [x] 	- Set default NIC
- [x] 	- Add/delete secondary IP address
- [x] 	- Delete VM network
- [x] Settings
- [x] 	- Add setting
- [x] 	- Update setting
- [x] 	- Delete setting
- [x] Add / delete comment
- [x] Add / delete tags
- [x] Links

**Compute > Instance groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] New instance group

**Compute > Instance groups > selected instance group**
- [x] Links
- [x] Update instance group
- [x] Delete instance group

**Compute > SSH Key Pairs**
- [x] Search
- [x] Sorting
- [x] Links
- [x] New SSH key pair

**Compute > SSH Key Pairs > selected SSH key pair**
- [x] Links
- [x] Delete SSH key pair

**Compute > Affinity Groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] New affinity group

**Compute > Affinity Groups > selected affinity group**
- [x] Links
- [x] Delete affinity group

**Storage > Volumes**
- [x] Basic earch
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Create volume
- [x] Upload local volume
- [x] Upload volume from URL

**Storage > Volumes > selected volume**
- [x] Detach volume
- [x] Take snapshot
- [x] Recurring snapshot
- [x] Resize volume
- [x] Migrate volume
- [x] Download volume
- [x] Delete volume
- [x] Links
- [x] Add/delete tags

**Storage > Snapshots**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links

**Storage > Snapshots > selected snapshot**
- [x] Links
- [x] Add/delete tags
- [x] Create template
- [x] Create volume
- [x] Revert snapshot
- [x] Delete snapshot

**Storage > VM Snapshots**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links

**Storage > VM Snapshots > selected snapshot**
- [x] Links
- [x] Add/delete tags
- [x] Revert VM snapshot
- [x] Delete VM snapshot

**Storage > Backups**
- [ ] Import offering
- [ ] Configure backup provider (Veeam)
- [ ] Create backup offering
- [ ] Assign VM to backup offering
- [ ] Revert to backup
- [ ] Delete backup

**Network > Guest networks**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Add network

**Network > Guest networks > selected network**
- [x] Links
- [x] Add/delete tags
- [x] Update network
- [x] Restart network
- [x] Delete network
- [x] Acquire new IP (only for isolated networks)
- [x] Replace ACL list(only for isolated networks)
- [x] Delete public IP address (only for isolated networks)
- [x] Add/delete egress rule (only for isolated networks)
- [x] Add/delete egress tags (only for isolated networks)

**Network > VPC **
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Add VPC

**Network > VPC > selected VPC**
- [x] Links
- [x] Update VPC
- [x] Restart VPC
- [x] Delete VPC
- [x] Networks
- [x] - Links
- [x] - Paginations
- [x] - Add network
- [x] - Add internal LB
- [x] Public IP addresses
- [x] - Links
- [x] - Pagination
- [x] - Select tier
- [x] - Acquire new IP
- [x] - Delete IP address
- [x] Network ACL Lists
- [x] - Links
- [x] - Pagination
- [x] - Add network ACL list
- [x] Private Gateways
- [x] - Links
- [x] - Pagination
- [x] - Add private gateway
- [x] VPN Gateway
- [x] - Links
- [x] VPN Connections
- [x] - Links
- [x] - Pagination
- [x] - Create Site-to-site VPN connection
- [x] Virtual routers
- [x] - Links
- [x] Add/delete tags

**Network > Security groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] Add security group

**Network > Security groups > selected security group**
- [x] Links
- [x] Add/delete tags
- [x] Add ingress rule by CIDR
- [x] Add ingress rule by Account
- [x] Ingress rule - add/delete tags
- [x] Ingress rule - delete
- [x] Add egress rule by CIDR
- [x] Add egress rule by Account
- [x] Egress rule - add/delete tags
- [x] Egress rule - delete
- [x] Ingress/egress rules pagination

**Network > Public IP Addresses**
- [x] Search
- [x] Sort
- [x] Links
- [x] Acquire new IP

**Network > Public IP Addresses > selected IP address**
- [x] Links
- [x] Add/delete tags
- [x] Enable/Disable static NAT
- [x] Release IP
- [x] Firewall - add rule
- [x] Firewall rule - add/delete tags
- [x] Firewall rule - delete
- [x] VPN - Enable/Disable VPN
- [x] VPN - Manage VPN Users

**Network > VPN Users**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add VPN user

**Network > VPN Users > selected VPN user**
- [x] Links
- [x] Delete VPN User

**Network > VPN Customer Gateway**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Add VPN Customer Gateway

**Network > VPN Customer Gateway > selected gateway**
- [x] Links
- [x] Edit VPN Customer Gateway
- [x] Delete VPN Customer Gateway
- [x] Add/delete tags

**Images > Templates**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Register template
- [x] Upload local template

**Images > Templates > selected template**
- [x] Links
- [x] Add/delete tags
- [x] Edit template
- [ ] Copy template
- [x] Update template permissions
- [x] Delete template
- [x] Download template
- [ ] Zones pagination
- [x] Settings - add/edit/remove setting

**Images > ISOs**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Register ISO
- [x] Upload local ISO

**Images > ISOs > selected ISO**
- [x] Links
- [x] Add/delete tags
- [x] Edit ISO
- [x] Download ISO
- [x] Update ISO permissions
- [x] Copy ISO
- [x] Delete ISO
- [x] Zones - pagination

**Images > Kubernetes ISOs**
- [x] Links
- [x] Basic search
- [x] Sort
- [x] Refresh
- [x] Pagination
- [x] Enable/Disable
- [x] Add Kubernetes Version

**Projects**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Switch to project
- [x] New project
- [ ] Enter token
- [ ] Project invitations

**Projects > selected project**
- [x] Links
- [x] Add/delete tags
- [x] Edit project
- [x] Suspend/Activate project
- [x] Add account to project
- [x] Accounts - Make account project owner
- [x] Accounts - Remove account from project
- [x] Delete project
- [x] Accounts - pagination
- [x] Resources - edit

**Events**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Archive event
- [x] Delete event

**Events > selected event**
- [x] Links
- [x] Archive event
- [x] View event timeline
- [x] Delete event

**Users**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add user

**Accounts**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add account
- [x] Add LDAP account

**Accounts > selected account**
- [x] Links
- [x] Update account
- [x] Update resource count
- [x] Disable/enable account
- [x] Lock/unlock account
- [x] Add certificate
- [x] Delete account
- [x] Settings

**Users > selected user**
- [x] Links
- [x] Edit user
- [x] Change password
- [x] Generate keys
- [x] Disable/enable user
- [x] Delete user
- [x] Copy API Key
- [x] Copy Secret Key

**Domains**
- [x] Search
- [x] Expand/collapse
- [x] Add/delete note
- [x] Add domain
- [x] Edit domain
- [x] Delete domain
- [x] Update resource count
- [ ] Link domain to LDAP Group/OU
- [x] Settings

**Roles**
- [x] Links
- [x] Search
- [x] Sort
- [x] Create role

**Roles > selected role**
- [x] Edit role
- [x] Delete role
- [x] Rules - add new rule
- [x] Rules - modify rule
- [x] Rules - delete rule
- [x] Rules - change rules order

**Infrastructure > Summary**
- [ ] Links
- [ ] Setup SSL certificate

**Infrastructure > Zones**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Pagination
- [ ] Add zone

**Infrastructure > Zones > selected zone**
- [ ] Links
- [ ] Edit zone
- [ ] Enable/disable zone
- [ ] Enable/disable out-of-band management
- [ ] Enable HA (disable?)
- [ ] Add VMWare datacenter
- [ ] Delete zone
- [ ] Settings - edit

**Infrastructure > Pods**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Add Pod

**Infrastructure > Pods > selected Pod**
- [ ] Links
- [ ] Dedicate/Release Pod
- [ ] Edit Pod
- [ ] Disable/enable Pod
- [ ] Delete Pod

**Infrastructure > Clusters**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Add Cluster

**Infrastructure > Clusters > selected cluster**
- [ ] Links
- [ ] Dedicate/Release cluster
- [ ] Enable/disable cluster
- [ ] Manage/unmanage cluster
- [ ] Enable/disable out-of-band management
- [ ] Enable/disable HA
- [ ] Configure HA
- [ ] Delete cluster
- [ ] Settings - edit

**Infrastructure > Hosts**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Add host

**Infrastructure > Hosts > selected host**
- [ ] Links
- [ ] Add/delete notes
- [ ] Dedicate/release host
- [ ] Edit host
- [ ] Force reconnect
- [ ] Disable/enable host
- [ ] Enable/cancel maintenance mode
- [ ] Enable/disable out-of-band management
- [ ] Enable/disale HA
- [ ] Delete host (only if disabled)

**Infrastructure > Primary Storage**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Add Primary storage

**Infrastructure > Primary Storage > selected primary storage**
- [ ] Links
- [ ] Edit primary storage
- [ ] Enable/cancel maintenance mode
- [ ] Delete primary storage
- [ ] Settings - edit

**Infrastructure > Secondary Storage**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Add Secondary storage

**Infrastructure > Secondary Storage > selected secondary storage**
- [ ] Links
- [ ] Delete secondary storage
- [ ] Settings - edit

**Infrastructure > System VMs**
- [ ] Links
- [ ] Search
- [ ] Sort

**Infrastructure > System VMs > selected system VM**
- [ ] Links
- [ ] View console
- [ ] Start/Stop system VM
- [ ] Reboot system VM
- [ ] Change service offering
- [ ] Migrate system VM
- [ ] Run diagnostics
- [ ] Get diagnostics data
- [ ] Destroy system VM

**Infrastructure > Virtual routers**
- [ ] Links
- [ ] Search
- [ ] Sort

**Infrastructure > Virtual routers > selected virtual router**
- [ ] Links
- [ ] View console (running)
- [ ] Start/Stop router
- [ ] Reboot router
- [ ] Change service offering
- [ ] Migrate router (running)
- [ ] Run diagnostics (running)
- [ ] Get diagnostics data
- [ ] Destroy router

**Infrastructure > Internal LB VMs**
- [ ] Links
- [ ] Search
- [ ] Sort

**Infrastructure > Internal LB VMs > selected internal LB VM**
- [ ] Links
- [ ] View console
- [ ] Stop router
- [ ] Migrate router

**Infrastructure > CPU Sockets**
- [ ] Search
- [ ] Sort

**Infrastructure > Management servers**
- [ ] Links
- [ ] Search
- [ ] Sort

**Infrastructure > Management servers > selected management server**

**Infrastructure > Alerts**
- [ ] Links
- [ ] Search
- [ ] Sort

**Infrastructure > Alerts > selected alert**
- [ ] Archive alert
- [ ] Delete alert

**Offerings > Compute offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add offering

**Offerings > Compute offerings > selected offering**
- [ ] Links
- [x] Edit offering
- [x] Update offering access
- [x] Delete offering

**Offerings > System offerings**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Change order (move to the top/bottom, move one row up/down)
- [ ] Add offering

**Offerings > System offerings > selected offering**
- [ ] Edit offering
- [ ] Delete offering

**Offerings > Disk offerings**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Change order (move to the top/bottom, move one row up/down)
- [ ] Add offering

**Offerings > Disk offerings > selected offering**
- [x] Links
- [x] Edit offering
- [x] Update offering access
- [x] Delete offering

**Offerings > Backup offerings**

**Offerings > Network offerings**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Change order (move to the top/bottom, move one row up/down)
- [ ] Add offering

**Offerings > Network offerings > selected offering**
- [ ] Edit offering
- [ ] Enable/Disable offering
- [ ] Update offering access
- [ ] Delete offering

**Offerings > VPC offerings**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Change order
- [ ] Add offering

**Offerings > VPC offerings > selected offering**
- [ ] Links
- [ ] Add / delete tags
- [ ] Edit offering
- [ ] Enable/Disable offering
- [ ] Update offering access
- [ ] Delete offering

**Configuration > Global settings**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Edit value

**Configuration > LDAP Configuration**
- [ ] Links
- [ ] Search
- [ ] Sort
- [ ] Configure LDAP

**Configuration > LDAP Configuration > selected LDAP configuration**
- [ ] TBD

**Configuration > Hypervisor capabilities**
- [ ] Data
- [ ] Search
- [ ] Sort

**Comment by rhtyd** [comment]
Executed, closing.
