### ISSUE TITLE
[BUG] DeployVM Wizard does not properly search for templates

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#520]
**Describe the bug**
In the deploy VM wizard, the search only searches the current selection of templates and does not query the backend

**To Reproduce**

1. Log in as a User or an Admin
2. Go to Create new VM
3. Search for a template

**Expected behavior**
An api call with the keyword should be called

**Comment by rhtyd** [comment]
@utchoang can you have a look at this, we want:
- The search to actually search the template/iso API
- Render the results on their own specific tabs (i.e. filtered tabs of features, public, mine... etc)
- On clicking the radio button we see an oval animation (minor issue, probably flex or css related)

**Comment by ravening** [comment]
@rhtyd @davidjumani 

I tried adding

```
@handle-search-filter="($event) => handleSearchFilter('templates', $event)"
```
under `<a-card` for the template/iso section but still couldn't search using the api. Mybe im missing something

**Comment by rhtyd** [comment]
@davidjumani please address this issue on priority as it's blocking general usability, in addition:
- As a user I should be able to search and select template based on the 4 filters (tabs)
- Unless I override the root disk option, it should not force or set the rootdisk value (it should also change if I change the template, or reset if I select an ISO)
- The rootdisk option shouldn't be passed via API if the override is/was not selected, also the value must be a whole number (than floating point). By default in VMware where I tested this, it is breaking VM deployment using Primate.

I see there is a PR but may not address all the issues in which case you may take that may as reference or cherry-pick commit and send a new PR. Thanks.
