### ISSUE TITLE
Can I use storage server like ceph 

### ISSUE THREAD

**Issue by alamintech** [apache/cloudstack-primate#532]
Hello dear,
**vCloudStack MGMT :** 4.14.0.0
**CloudStack install :** Centos 7.7
**Compute Nodes :** Centos 7.7
**Virtualization host :** kvm
 **ceph install :** Centos 7.8

Can I use **Storage Server** like **ceph** for my private cloud. Please see attachment for my design.

---
**Thanks.**
@alamintech
![fd7a320e-5501-47b9-bce1-ad4f39ff0644](https://user-images.githubusercontent.com/68062764/87268460-40fefc80-c4ec-11ea-8292-cf47dae70c87.jpg)

**Comment by rhtyd** [comment]
@alamintech please use the `users` mailing list (http://cloudstack.apache.org/mailing-lists.html) to ask questions, only report issues related to Primate on this repo. Closing on this remark.
