### ISSUE TITLE
How can I use LVM volume storage for my private CloudStack

### ISSUE THREAD

**Issue by alamintech** [apache/cloudstack-primate#546]
How can I use LVM volume storage for my private CloudStack. 

Please see my image below 
Also please give me any mail address so I have some query for my private server. 
many time I got below details for collect mail address, but I am not find out which exact mail address. 
----------------- 
Please ask questions on the users ML instead - http://cloudstack.apache.org/mailing-lists.html
You may also refer the docs and the quick install guide - http://docs.cloudstack.apache.org 
----------------

Please any one give me exact mail address where I send my query. 

Thanks. 

![lvm](https://user-images.githubusercontent.com/68062764/87757743-f6072100-c82c-11ea-8b4b-a1bf83a41e58.JPG)

**Comment by ravening** [comment]
@alamintech Im not sure how is this related to primate ui? You should ask this question in cloudstack repo

**Comment by alamintech** [comment]
Thanks for your replay! How can I get mail address for communicate for my query! 
Thanks

**Comment by alamintech** [comment]
can you send me which CoudStack official repo link

Thanks.

**Comment by ravening** [comment]
use this link to find the email address you want https://cloudstack.apache.org/mailing-lists.html
use this link to create issues with cloudstack. https://github.com/apache/cloudstack/issues

closing this issue as its not related to primate

**Comment by alamintech** [comment]
sure, Thanks.
