### ISSUE TITLE
[BUG] Missing security groups in deployVM in Basic Zone

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#549]
**Describe the bug**

The option of adding a VM to a security group is missing in the deployVM form for a basic zone. Ref the old UI
![Screenshot from 2020-07-21 10-40-09](https://user-images.githubusercontent.com/8244774/88015355-9f585a80-cb3e-11ea-8061-61ff846e3fc6.png)
![Screenshot from 2020-07-21 10-40-17](https://user-images.githubusercontent.com/8244774/88015357-a0898780-cb3e-11ea-9832-cf10f9c2c0a3.png)

**Comment by davidjumani** [comment]
@utchoang Could you look into this ?

**Comment by rhtyd** [comment]
Note don't pick any new big tasks for GA now, we're not supporting basic zone creation now.

**Comment by rhtyd** [comment]
Adv zone + SG must however work.

**Comment by davidjumani** [comment]
Closing this since it is out of scope
