### ISSUE TITLE
[Usability] Login screen - Make the cursor at username field when loading the screen

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#551]
**Describe the bug**
When loading the login screen the cursor is not on the username field which make the user to either click on it or tab a few times until it gets on it 

**Expected behavior**
It will be much easier and convenient if the cursor is at the field and the user could just start typing his username

**Comment by davidjumani** [comment]
Fixed in #539

**Comment by borisstoyanov** [comment]
![Screenshot 2020-07-27 at 10 11 37](https://user-images.githubusercontent.com/13551960/88513769-94e00a00-cff1-11ea-886e-04baef6afdbc.png)
Looking good with #539

**Comment by rhtyd** [comment]
PR merged, closing this
