### ISSUE TITLE
[BUG] Background color changed for action confirmation dialog

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack-primate#554]
**Describe the bug**
For any confirmation popup, the background is shown in black image which is not user friendly

**To Reproduce**

1. Log in as a User or an Admin
2. Go to Compute tab and click on instances
3. Click on Destroy virtual machine button
4. A pop up appears asking for confirmation

**Expected behavior**
The color should be consistent

**Screenshots**
![Screenshot 2020-07-22 at 18 21 01](https://user-images.githubusercontent.com/10645273/88201718-1af1fe80-cc48-11ea-91cb-b5212361ce83.png)

**Comment by rhtyd** [comment]
@ravening that looks like a build/env error, can you rebuild and try again? I've seen that sometimes cc @davidjumani @utchoang
