### ISSUE TITLE
[BUG] Missing Select Security Groups in Advaced Zone with SG Enabled

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#555]
**Describe the bug**
While Deploying a VM in a Zone with SG Enabled, the option to select the security groups is missing.

Ref Legacy UI :
![Screenshot from 2020-07-21 10-40-09](https://user-images.githubusercontent.com/8244774/88015355-9f585a80-cb3e-11ea-8061-61ff846e3fc6.png)

Also :
- Missing add Guest vlan for Advanced Zone with SG Enabled
- Fix Errors button still present after fixing errors and zone successfully created

**Comment by davidjumani** [comment]
@utchoang Could you look into this ? Will create a zone with SG Enabled on QA to test

**Comment by davidjumani** [comment]
Created `SGAdvanced` Zone

**Comment by utchoang** [comment]
@davidjumani I tried with SGAdvanced on
http://primate-qa.cloudstack.cloud:8080/client/
But I couldn't find the step security group when I switched from affinity group to network. Thanks.
![image](https://user-images.githubusercontent.com/13766648/88509289-eea0fe00-d00a-11ea-9024-d24f0638f8ce.png)
![image](https://user-images.githubusercontent.com/13766648/88509306-f95b9300-d00a-11ea-9fe0-51b901827eb4.png)

**Comment by davidjumani** [comment]
@utchoang Could you test now ?

**Comment by utchoang** [comment]
@davidjumani OK. I've seen it now. Thanks.

**Comment by davidjumani** [comment]
@utchoang Could you look into this too
- Missing Guest VLAN ID in create zone wizard for Advanced Zone with SG Enabled
- 'Fix Errors' button still present after fixing errors and zone successfully created

**Comment by rhtyd** [comment]
@davidjumani is this still an issue or fixed? cc @utchoang

**Comment by rhtyd** [comment]
PR https://github.com/apache/cloudstack-primate/pull/567 merged
