### ISSUE TITLE
[BUG] Create Zone bugs

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#560]
**Describe the bug**
- Missing Guest VLAN ID in create zone wizard after selecting Advanced Zone with SG Enabled
- 'Fix Errors' button still present after fixing errors and zone successfully created

![Screenshot from 2020-07-28 17-37-41](https://user-images.githubusercontent.com/8244774/88663452-43bb3d80-d0f9-11ea-99ff-6cfdb241a795.png)
![Screenshot from 2020-07-28 17-39-02](https://user-images.githubusercontent.com/8244774/88663457-45850100-d0f9-11ea-8516-33af5210b03e.png)

**Comment by davidjumani** [comment]
@utchoang Could you look into this ?

**Comment by rhtyd** [comment]
@davidjumani is this still an issue or fixed? cc @utchoang
