### ISSUE TITLE
Consolidated Bug List

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#563]
CarryOn from #528 

TO FIX :
- Can't take a vm storage snap in the vm detail view

Good to have or close:
- Contextual help missing in Add Zone, although not there in the legacy UI either
- Add account on project dashboard (OK with this, add button on the accounts/project component and remove the add button from project actions) 
- Keep the current router path while switching projects (David can explore, can we use the current router path/name to reload the page)
- All icons UI-wide look hanging at the bottom in Firefox but not Chrome (could be AntD bug)
- Explore if we can show label in quick-view for buttons

Mobile View/1.1:
- Project selector not visible in mobile mode ?
- Create zone form is not aligned in mobile view
- Header notification should be clearable (obstrucs in mobile view)
- Edit setting icon misaligned in mobile (accounts, domain, zones, etc)
- Page size changer doesn't show up on mobile mode

After 1.0/GA:
- Enter to submit a form (Alex's point - should be consistent)
- Search for IPAddress firewall rule ?
- While listing domains, on full page reload, it goes back to the root domain (context is lost; we don't keep selected domain in router path/url)
- Why do IPs always point to the resource ? (David - OK to remove)
- Account in user info card doesn't directly go to account but to the account listview ?
- LB Rule is just plain json in ilb

**Comment by davidjumani** [comment]
Fixed in #564 :
 - Fixing scale router
 - Fixing account actions
 - Fixing user actions
 - Adding message for create vm backup
 - Fix default allowuserdrivenbackups in ImportBackupOfferings
 - Fix typo in TakeSnapshot
 - Ensuring zone mandatory in upload template
 - Adding securitygroup to instacetab
 - Adding related vms to routers
 - Adding makeredundant to restart network
 - Fixing no key in listview
 - Link to ipaddress only if router path is publicip
 - Show vpc routers only to admin
 - Fix restartVPC args
 - Fix storage action visibility
 - Reorder routes to match legacy
 - Reorder cluster tabs
 - Fix number input width
 - Fix create vpc
 - List events also on fetchlatest
 - Fix show domain actions
 - Removing resource admin from default roles
 - Fix missing store
 - Adding createVPC view
 - Adding attachiso view

**Comment by rhtyd** [comment]
Has PR, issues addressed
