### ISSUE TITLE
Error when editing firewall rule

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#570]
I have this rule 
![rule](https://user-images.githubusercontent.com/67025242/89651987-c62ec480-d892-11ea-933d-4c65c36dcafe.PNG)

the problem is that when I try to edit that rule to set the protocol to all, I get the erro below.

![error](https://user-images.githubusercontent.com/67025242/89652058-e5c5ed00-d892-11ea-9b79-b0b2461d3d8a.PNG)

it looks like primate is looking for port number eventhough I am trying the set the protocol to all. this works ok in the legacy UI.

**Comment by rhtyd** [comment]
Can you review this @davidjumani
