### ISSUE TITLE
VM Hardware: NICs and IPs management

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#58]
For the VM's NIC hardware component where we show the NICs, implement the following:
- [x] Add network to VM
- [x] Change IP address of NIC
- [x] Edit/add secondary IPs for the NIC
- [x] Set nic to default
- [x] Remove NIC from VM

![Screenshot from 2019-12-07 00-59-51](https://user-images.githubusercontent.com/95203/70350587-0154a000-188d-11ea-89da-9f737c4fa985.png)

VM can have more than one nic, in that we also want buttons to set the nic as default nic and also to remove NIC from the VM:
![Screenshot from 2019-12-11 23-05-28](https://user-images.githubusercontent.com/95203/70645369-e017f900-1c6a-11ea-9a02-ddaa5effbe0e.png)

**Comment by rhtyd** [comment]
I've updated the screenshot and actions list, please check ^^ @RitchieVincent

**Comment by RitchieVincent** [comment]
👍  Luckily I haven't started this task yet, nearly finished #57 and then I'll move on to this one.

**Comment by rhtyd** [comment]
Fixed in #71
