### ISSUE TITLE
[BUG] Volume Migration - Replace disk offering selected by default

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#582]
**Describe the bug**
The option is selected by default. Such action shouldn't be executed by default, it should be under admin consideration and explicit request. 

**To Reproduce**

1. Migrate a volume 
![Screenshot 2020-08-14 at 11 20 57](https://user-images.githubusercontent.com/13551960/90229396-80d53e80-de20-11ea-8f65-f52e86428b95.png)

**Comment by rhtyd** [comment]
@davidjumani can you have a look at this?
