### ISSUE TITLE
[BUG] switching between Custom and Fixed/Static Compute Offering

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#588]
**Describe the bug**
Bug when switching between Custom and Fixed/Static Compute Offering

**To Reproduce**

- Log in to Primate, 
- start the VM deployemnt wizard, choose a Custom Compute offering, enter some values (1000 mhz, 256MB RAM)
- change  you mind, and select the Small Offering (or other fixed-size offering) and try to deploy a VM

Error:
![image](https://user-images.githubusercontent.com/45762285/90553302-74404580-e194-11ea-9d62-de9a3c38d91d.png)

Primate from PR 550

**Comment by andrijapanicsb** [comment]
(ignore the first box with error Launching VM)

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by andrijapanicsb** [comment]
LGTM
