### ISSUE TITLE
[BUG]  or  an improvement - on new windows, move focus/cursos to the first field

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#589]
When i.e. clicking a button to register template from URL, a new windows/form opens, but the text cursor is not in the first field (URL field) and one needs to explicitly click on the first field.

Small improvement for usability.

**Comment by rhtyd** [comment]
@davidjumani can you see if it's a good one - otherwise this is good to have but not mandatory for 1.0/GA

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/594/commits/e4580e761148815f4a4c2094bf22dc082cfe9f76

**Comment by andrijapanicsb** [comment]
LGTM (would be nice to have the same for all other forms (i.e. when creating a new data volume))
