### ISSUE TITLE
[BUG] no expunge when deleting multiple VMs at once

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#590]
![image](https://user-images.githubusercontent.com/45762285/90554738-95a23100-e196-11ea-882c-e8b81c66bf9b.png)

The Expunge is there when deleting a single VM, but not on deleting multiple VMs.

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/594/commits/0facb7a8e69bd33afc30fe20cb54378db7ec8051

**Comment by andrijapanicsb** [comment]
LGTM< thx.
