### ISSUE TITLE
[BUG] VM state in UI not updated when deployment failure

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#591]
Primate from PR 550

VM deployment is ongoing:
![image](https://user-images.githubusercontent.com/45762285/90555149-3690ec00-e197-11ea-9c6e-3b6f804eb647.png)

On deployment failure a proper message is shown, but the VM state is not updated to "Error", but instead need to refresh the current view:

![image](https://user-images.githubusercontent.com/45762285/90555303-7526a680-e197-11ea-90a8-45924c85bc0a.png)

**Comment by rhtyd** [comment]
@davidjumani is there a way we can cause the listView to refresh when the async job poll stops? Another way could be to launch the VM and move to the VM once it is deployed instead of doing to the list view (from the deployvm component)?

**Comment by andrijapanicsb** [comment]
I had a perhaps related thing - the VM was indeed deployed and started correctly, but its state after, I finished the deployment wizard, was initially "Stopped" and there was never (if I saw that correctly) a "spinning circle" that indicates that we query VMs state - and after the VM was deployed/started fine, the VM status remained as Stopped.

![image](https://user-images.githubusercontent.com/45762285/90615168-06cffb80-e20c-11ea-823d-a3e8f89314ef.png)

**Comment by davidjumani** [comment]
Refresh after deployment Fixed in https://github.com/apache/cloudstack-primate/pull/594/commits/71c875f50e9114b150599396031178fa76fa3abf

**Comment by andrijapanicsb** [comment]
This is (was, hopefully) definitively an issue even with successful deployments (Firefox, Windows 10)

**Comment by davidjumani** [comment]
@andrijapanicsb Fixes for vm failed as well as successfully deployed

**Comment by andrijapanicsb** [comment]
Looks good, beside the circle "not spinning" for me - which it was previously (but got broken in the meantime, or it might be my browser / I did clear cache) cc @davidjumani 
![image](https://user-images.githubusercontent.com/45762285/91418586-a1ef5380-e852-11ea-8af5-dad01f2c28f4.png)


Closing

**Comment by andrijapanicsb** [comment]
Actually, I'm reopening for comments - the VM is never in "Starting" state, so that is wrong - pls fix.

**Comment by davidjumani** [comment]
@andrijapanicsb Could you check with #627
