### ISSUE TITLE
[BUG] minor: add "MB" to the offering field desc

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#595]
![image](https://user-images.githubusercontent.com/45762285/90641992-21b56680-e232-11ea-8cbf-541b6dcf52d0.png)

The unit is missing in the desc - do the sam as "Mhz" for the CPU field.

**Comment by rhtyd** [comment]
Should be quick one - @shwstppr @davidjumani

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/594/commits/77c8f68364c80c0bf2866d3e3b2c735b50b1555d

**Comment by davidjumani** [comment]
@andrijapanicsb Could you verify that this has been fixed on latest master and close it ?

**Comment by andrijapanicsb** [comment]
fix is LGTM, but please considering updating related comment as "Number of CPU cores" or "Number of CPUs" and not "the CPU number" - or it might be my English as well

![image](https://user-images.githubusercontent.com/45762285/91418889-0b6f6200-e853-11ea-8523-212e623a112e.png)
