### ISSUE TITLE
[BUG] "Configuration" values from the vApp appliance vs Compute offering

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#596]
Deploying an OVA template with vApp Configurations (which define/require 1000Mhz CPU and 1MB of RAM - see the OVF part below).

The Primate doesn't allow (me) to select Small/Medium/Bigger offering - only selecting a custom offering works - seems like the OVF parameters are not parsed or somehing (talked to @nvazquez and he suggested it seems like the Primate bug, not backend)

![image](https://user-images.githubusercontent.com/45762285/90643402-ddc36100-e233-11ea-95db-2594ac3c9034.png)

**Comment by shwstppr** [comment]
@andrijapanicsb current behaviour in Primate is to strictly match configurations for RAM and CPU values. This can be changed if needed

**Comment by rhtyd** [comment]
@andrijapanicsb @nvazquez the compute offering does not determine the network speed, which is part of the network offering. The configuration name may therefore get misleading. I had initially proposed to @nvazquez @shwstppr to avoid showing the name selection which serves no purpose in backend (the selected option is not used) but to use it for filtering only compute offering wrt ram and cpu. Do we need to re-think how we show this?

**Comment by andrijapanicsb** [comment]
@rhtyd this is Daans testing machinge with poor name - no problem there.
I get it for the "exact match" - but didn't we communicate hiding all offerings that are "less" then the required Configuration - worst case it can stay as it is - but when I hover the offering (where mouse changes from the arrow to the red deny sign) - it would be good to have a generic message like "Offering CPU/RAM values do not match the exact values as requested by the Configuration" -  or similar - since the "deny" mouse arrow doesn't explain much (except saying "not allowed", so to speak)

**Comment by davidjumani** [comment]
Discussed with @andrijapanicsb Will be working on this

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/609/commits/2d5ab6dee96c1eeae1eaa575d811490ba2ede0a9

**Comment by andrijapanicsb** [comment]
I'll mark it as resolved, since we have another PR 609 handling all of this properly.
