### ISSUE TITLE
[BUG] Input field for RAM in the custom compute offering needs polishing

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#597]
Custom compute offering:

![image](https://user-images.githubusercontent.com/45762285/90658765-3e5a9a00-e244-11ea-808c-652093ceff2d.png)

Click inside the RAM field, hit backspace on keyboard (to delete the number 1 (which is btw a very bad default value, perhaps 256?) - the field will get value of "MB MB" then if you type a number (100), you get the stuff from the screenshot

Can the "MB" be placed outside of the actual field, so it makes more sense visually - same way as the "MHz" for the CPU speed field?

**Comment by utchoang** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/600

**Comment by davidjumani** [comment]
@andrijapanicsb Could you verify that this has been fixed on latest master and close it ?

**Comment by andrijapanicsb** [comment]
LGTM
