### ISSUE TITLE
[BUG] the "job querying" message-box will redirect users back to the previos page

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#598]
The title is ugly, but I don't know the terminology, here's what I mean

When deleting a template., the following happens:

1. Go to delete a template
![image](https://user-images.githubusercontent.com/45762285/90659555-1d467900-e245-11ea-80e5-b80821bc1494.png)

2. The following screen is shows (see the top "Deleting template XXXXX in progress" box/message)
![image](https://user-images.githubusercontent.com/45762285/90659656-3bac7480-e245-11ea-8247-e006f41c9c80.png)

3. now, while still this message box is shown on the top (i.e. template deletion is not finished), go back to the list of the templates 
![image](https://user-images.githubusercontent.com/45762285/90659913-8b8b3b80-e245-11ea-8be2-3f8b457b86fc.png)

4. when the template deletion is finished, it will redirect you back to the specific (deleted) template  screen ("one screen back"), with empty stuff:
![image](https://user-images.githubusercontent.com/45762285/90660185-defd8980-e245-11ea-844f-f4b95d0fc806.png)

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I will fix this task, Thanks.

**Comment by rhtyd** [comment]
@andrijapanicsb can you test against latest master

**Comment by andrijapanicsb** [comment]
looks good - thx!
