### ISSUE TITLE
[BUG] minor - label it "Data disks, not "Disk Offerings"

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#601]
![image](https://user-images.githubusercontent.com/45762285/90756354-8c22e100-e2dc-11ea-97ed-3cbf94bb9576.png)

Deploying a VM from a template, this section should say Data disks, not Disk offerings (as it's kind of meaningless) - or just "Disk" if that is an easier in case the VM is deployed from ISO (in which case that means Root disk)

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/594/commits/89b3d4d33a297854a90ffc48a7eda8abda0a7e62

**Comment by andrijapanicsb** [comment]
LGTM, thx
