### ISSUE TITLE
[BUG] Deploy VM job not submited for a long time (?)

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#603]
![image](https://user-images.githubusercontent.com/45762285/90889857-25272a00-e3b9-11ea-88ff-ca159651a58d.png)

Clicking the "Launch Virtual Machine" - sometimes it takes a lot of time to submit the job - i.e. the "circles" around CANCEL and LAUNCH VM.. buttons are spinning - now (last time) it took 30-60sec (not seen it before) - not internet issue, since I was on the video call at the same time,

**Comment by davidjumani** [comment]
@andrijapanicsb Could you provide the steps to reproduce it ?

**Comment by andrijapanicsb** [comment]
As agreed, let me try to experience this one again (when I experienced this, I was working from my 4G (latency 20-50ms) connection)
This week will be with "normal" latency.

**Comment by rhtyd** [comment]
I tried latest master and primate-qa (simulator) and a KVM/trillian env and don't see this. @andrijapanicsb please re-open if you reproduce this again.
