### ISSUE TITLE
[BUG] EDIT TEMPLATE not on pair with the old UI

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#604]
Primate:
![image](https://user-images.githubusercontent.com/45762285/90913572-bcea3f80-e3dc-11ea-948f-5b692739f88e.png)

Old UI:
![image](https://user-images.githubusercontent.com/45762285/90913627-cf647900-e3dc-11ea-84aa-37c42a393c04.png) 
and
![image](https://user-images.githubusercontent.com/45762285/90913659-dbe8d180-e3dc-11ea-866c-e8624acfc39f.png)

**Comment by davidjumani** [comment]
@andrijapanicsb The permissions such as featured, public, etc are in the update template sharing button
![Screenshot from 2020-08-24 12-36-28](https://user-images.githubusercontent.com/8244774/91014231-a6bfc780-e606-11ea-8516-65baa40e7b9b.png)
Can edit the tags in the card on the left
![Screenshot from 2020-08-24 12-38-27](https://user-images.githubusercontent.com/8244774/91014324-cd7dfe00-e606-11ea-95e8-18cd8c1e7b65.png)

**Comment by andrijapanicsb** [comment]
Um...right - then a false bug for the missing options (except the confusing sshKeyEnabled) - but, from a user point of view, I find these a bit hiden - but can live with it if everyone else is OK - what I mean - template permission DO define a realy "sharing of template with other accounts/domains", while the button "Update template sharing" manages public/featured/extractable (which I don't find to be a "sharing")

Anyway, parking this with you guys.

**Comment by andrijapanicsb** [comment]
cc @rhtyd please see my comment?

**Comment by rhtyd** [comment]
@davidjumani can you check and remove ssh enabled option if not necessary (does it make any difference)? (from both register and edit template forms)

**Comment by davidjumani** [comment]
@rhtyd It's just a field used to describe the template but does not have any effect in the service layer

**Comment by rhtyd** [comment]
@andrijapanicsb please verify against latest and close. Fixed in https://github.com/apache/cloudstack-primate/pull/634

**Comment by andrijapanicsb** [comment]
LGTM - (the ssh stuff renamed, though I still find the permissions vs sharingf buttons vs. the actual options very confusing)
