### ISSUE TITLE
[BUG] Add cluster - password is not masked

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#612]
**Describe the bug**
Password is not masked when adding a VMware cluster

**To Reproduce**

1. Log in as a User or an Admin
2. Go to clusters and add a VMware cluster 
3. Password appears in clear text as you write it 

**Expected behavior**
Should be hidden 

**Screenshots**

![Screenshot 2020-08-24 at 16 09 12](https://user-images.githubusercontent.com/13551960/91048420-56576280-e624-11ea-8cac-858da043118a.png)

**Comment by utchoang** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/613

**Comment by borisstoyanov** [comment]
thanks @utchoang lets close this once we merge the PR

**Comment by rhtyd** [comment]
PR merged
