### ISSUE TITLE
[BUG] Trying to run docker.sh script

### ISSUE THREAD

**Issue by j-porsche** [apache/cloudstack-primate#616]
Hey,

**Describe the bug**
I tried to install cloudstack-primate on a CentOS 8.1 VM. Everything worked fine until I had to run the docker.sh script. Later the command "npm run build" is executed. The process is stopping at this point with an error (image attached). 

Npm run build works fine if I start it manually outside the container.  Inside the container it isn't working. The npm versions are the same.

Can somebody help me with this problem?

Thank you!

**Screenshots**
![debugLog](https://user-images.githubusercontent.com/61408412/91171117-3da98400-e6da-11ea-9881-66bfb35f2646.PNG)

**Desktop (please complete the following information):**
 - OS: CentOS 8.1

**Comment by svenvogel** [comment]
@rhtyd @utchoang do you have some ideas on this error?

**Comment by onitake** [comment]
I'm trying to reproduce it here, but the build works perfectly fine on my system.

From my experience, npm is quite a brittle tool and can break without meaningful error at any time - in particular when internet connectivity is not good.

Is your error reproducible? Does it go away if you use a different internet connection?

**Comment by j-porsche** [comment]
I don't understand what you mean? Can you explain? My connection should be good.

**Comment by j-porsche** [comment]
And local (outside the container) it is working fine.

**Comment by onitake** [comment]
Ok, so first of all: The Dockerfile works fine for me. I get no error at all, no matter how many times I run it.

My experience with npm is that it can break easily for obscure reasons. The log you posted doesn't look very useful.
Can you try deleting the `node:lts-buster` image and run the build again? Is it reproducible?

**Comment by j-porsche** [comment]
I tried it but it doesn't work neither.

**Comment by onitake** [comment]
Perhaps this helps? https://github.com/vuejs/vue-cli/issues/2596

**Comment by onitake** [comment]
Note that Docker will copy the whole build directory into the container, so if you have anything left lying around there, it may disrupt the build.

**Comment by j-porsche** [comment]
Sorry but your tips didn't help me out. The error is still there.

**Comment by utchoang** [comment]
@rhtyd Do you have the other idea? On my device (Windows), it's completely normal.

**Comment by rhtyd** [comment]
@j-porsche can you build it locally without using docker? And try on a different laptop/VM? The error looks like a npm build issue

**Comment by rhtyd** [comment]
This is my npm version output, make sure to use npm LTS 12.x in the container:
```
> npm version
{
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '6',
  nghttp2: '1.41.0',
  node: '12.18.3',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.38.0',
  v8: '7.8.279.23-node.39',
  zlib: '1.2.11'
}
```

**Comment by onitake** [comment]
@rhtyd The Dockerfile specifies node:lts-buster as its build base container. That should pick up Node 12.18.3 according to https://hub.docker.com/layers/node/library/node/lts-buster/images/sha256-902bf79075924ff034642dc7da0e5f40a08ff65b5650c54bac3a03dea1e3a87f?context=explore

I just run another test on a separate machine running Debian buster using a fresh git clone. It worked flawlessly.
@j-porsche did you try a fresh checkout?

Perhaps it's an issue with CentOS 8, or the Docker version you're using.
How did you install Docker, and which version is it?

**Comment by j-porsche** [comment]
I tried it again with a fresh git clone. But I used node:lts-stretch instead of node:lts-buster. Now the build process works fine.

I use podman (v1.6.4) instead of docker.

**Comment by onitake** [comment]
@rhtyd Do you think we can change the base image to node:lts-stretch? The current base image also installs Node 12.18.3, like lts-buster.

**Comment by j-porsche** [comment]
Well from my perspective with node:lts-stretch it works fine now. So I think it could be a good change.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/626
