### ISSUE TITLE
[BUG] Template pagination needs some love

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#617]
On the list of template (when deploying a VM from a template), when you click on the "next page" button (or number 2. for the second page).... 
![image](https://user-images.githubusercontent.com/45762285/91174540-b65f0f00-e6df-11ea-89ee-c2212c3ada00.png)

It lists the first page of the Feautred, instead of the next page of the My Templates:

![image](https://user-images.githubusercontent.com/45762285/91174618-d1318380-e6df-11ea-800d-a37e45fcee15.png)

**Comment by utchoang** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/621

**Comment by andrijapanicsb** [comment]
LGTM
