### ISSUE TITLE
[BUG] A default one network selected, but no networks previously selected

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#618]
This is perhaps OK, but I find it (a little bit, not too much) confusing (especially when comparing to the behaviour in the old UI):
i.e. why is the first network not selected in the checkboxes option - we have below selected 'which one of the selected networks is the default one" - but we have never "selected" (checkbox) ANY of the networks in the above list of networks:

![image](https://user-images.githubusercontent.com/45762285/91186139-f4affa80-e6ee-11ea-948e-327a9ca70f28.png)

**Comment by davidjumani** [comment]
@andrijapanicsb Unable to reproduce. The first network is checked
![Screenshot from 2020-08-26 13-03-55](https://user-images.githubusercontent.com/8244774/91274630-9fcabd80-e79c-11ea-9037-6847a375eb8d.png)

**Comment by rhtyd** [comment]
@andrijapanicsb which browser/OS were you using?

**Comment by andrijapanicsb** [comment]
win10, firefox latests (but happy to retest with the latest master? - tbh no idea if I tested master RPM packages from 24th or some PR in progress - since I had to replace primate a few times to test specific PRs)

**Comment by andrijapanicsb** [comment]
happening with this version: cloudstack-primate-1.0.0-20200825.x86_64

**Comment by andrijapanicsb** [comment]
Nope, just installed the latest master (from 27, 00.40h CET) - and it's happening on all 3 browsers (Chrome, Edge, Firefox) - Windows 10. cc @davidjumani

**Comment by davidjumani** [comment]
Looks like it's vapps related. Will be fixed in the vapps PR

**Comment by davidjumani** [comment]
Fixed via https://github.com/apache/cloudstack-primate/pull/609/commits/55e4c85eac78f18b3248104074acb6a1e1f0b232
@andrijapanicsb Could you test it with #609

**Comment by andrijapanicsb** [comment]
This is not good, perhaps broken in some other fix/commit:

When the very first template on the Featured list (the one selected by default when you choose a Zone) is a deploy-as-is template, it seems that none of the OVF properties are parsed or something - as the network sections does NOT show 4 NICS to network mappings (part of the OVF template), also offerings are not filtered etc - see the images below

So I can't say if this original bug is fixed

![image](https://user-images.githubusercontent.com/45762285/91554819-24017a00-e930-11ea-9792-11e740367ecb.png)

and the networking part

![image](https://user-images.githubusercontent.com/45762285/91554859-354a8680-e930-11ea-91bf-a055836c56f8.png)

while i.e. the network sections should show nic to network mapping like this one:

![image](https://user-images.githubusercontent.com/45762285/91554928-557a4580-e930-11ea-9ab2-f8d97e3445a7.png)

**Comment by andrijapanicsb** [comment]
LGTM
