### ISSUE TITLE
[BUG] Success of VM deployment, causes weird API calls aftewards

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#619]
VM was deploying for a long time (i.e. first time ever from a new template - so OVF deployment in vCenter took 5min or so)
In the meantime I was configuring/creating a new VM (was in the new VM wizard, configuring options), but have NOT submited the new VM creation job.

Then when the previous VM deployment finished, my CURRENT VM deployment job was magically submitted or something 👍 🥇 

![image](https://user-images.githubusercontent.com/45762285/91189010-37270680-e6f2-11ea-921f-833edde8e0b0.png)

I've tested the same with template registration: while VM is being deployed, go and open the Register template form - and got some weird API calls to list templates, while I was on the Register template dialogue (but no error, as this was listTemplate api now)

![image](https://user-images.githubusercontent.com/45762285/91189790-27f48880-e6f3-11ea-8309-0cf2ff857ade.png)

**Comment by davidjumani** [comment]
@andrijapanicsb Could you provide the steps to reproduce this ?

**Comment by andrijapanicsb** [comment]
I have, as I wrote, so:

VM was deploying for a long time (i.e. first time ever from a new template - so OVF deployment in vCenter took 5min or so)
In the meantime I was configuring/creating a new VM (was in the new VM wizard, configuring options), but have NOT submited the new VM creation job.

Then when the previous VM deployment finished, my CURRENT VM deployment job was magically submitted or something

**Comment by davidjumani** [comment]
Could be caused by autogen view reloading while the user is in deployvm view. Fixed in #623

**Comment by andrijapanicsb** [comment]
LGTM
