### ISSUE TITLE
Custom Upload Action - Template, ISO, volume

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#62]
- [ ] Volume file upload 
- [ ] Template file upload 
- [ ] ISO file upload

Implement file uploading mechanism, the pattern is same for volume, template and isos. For example from old UI, for volume, template, iso:

![Screenshot from 2019-12-09 14-52-41](https://user-images.githubusercontent.com/95203/70423497-9aed9e80-1a93-11ea-8174-0028bec74415.png)

![Screenshot from 2019-12-24 14-58-07](https://user-images.githubusercontent.com/95203/71406362-ef7d4600-265d-11ea-82b2-da420262fa74.png)

![Screenshot from 2019-12-24 14-58-17](https://user-images.githubusercontent.com/95203/71406364-ef7d4600-265d-11ea-8afd-306d39a50d60.png)

Example reference of how to add a custom action form, you can see: https://github.com/apache/cloudstack-primate/pull/69/files

Upload component to use: https://www.antdv.com/components/upload/

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel tagged for next tasks to consider. Thanks.

**Comment by svenvogel** [comment]
@utchoang lets start with this issue.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I would like to ask if it is to change the uploading mechanism only, or to create a form similar to the old UI for volumn, template and isos?

**Comment by svenvogel** [comment]
@utchoang i think the complete form. is this correct @rhtyd?

**Comment by rhtyd** [comment]
@utchoang @svenvogel it needs to be the full form with the upload button/component, as in the old UI. I advise you to start with the simpler task of #50 and #86 and reuse that form with the upload iso/template form (this ticket). By doing this you can get a feel for the action form and reuse parts of it in the upload iso/template form. What do you think @svenvogel ?

**Comment by svenvogel** [comment]
@utchoang i think like @rhtyd. if its better in the other way to start i would recommend to do that. you feel free to start here 😄

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel When I'm uploading volume from local for a test using file .qcow2, I get the following error message: "Failed to upload file due to system misconfiguration. Please contact admin."

![Screenshot_6](https://user-images.githubusercontent.com/13766648/71864291-09c12480-3132-11ea-859f-90a9b9128f05.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/13766648/71864295-0cbc1500-3132-11ea-9af7-f31733784913.jpg)

**Comment by rhtyd** [comment]
@utchoang this is a tricky one as it requires an environment that can access SSVM public IP to upload the file, the reference/test server (acs.shapeblue.com) on port-forwards to the management server so you won't be able to access the internal ssvm public IP. The other issue is that this features requires the environment to be SSL enabled as the URL returned by the getUploadParamsForTemplate API is https enabled. For example as seen in dev tools:

![Screenshot from 2020-01-07 09-03-41](https://user-images.githubusercontent.com/95203/71866693-1db65780-312d-11ea-9cc8-a0d07df50efc.png)

The code for all of the upload feature (for uploading template, iso and volume) roughly follows this pattern:
- Call to register the template/iso/volume via the getUploadParamsForTemplate/getUploadParamsForIso/getUploadParamsForVolume
- This API returns post URL, and some secrets/signatures
- The UI makes a HTTP post request of the file and receives 'upload successful' or some suitable message

![Screenshot from 2020-01-07 09-17-48](https://user-images.githubusercontent.com/95203/71867083-b3061b80-312e-11ea-8113-0ecceb8dc774.png)
![Screenshot from 2020-01-07 09-17-58](https://user-images.githubusercontent.com/95203/71867084-b39eb200-312e-11ea-944b-c1580201c8c0.png)

For code reference you can see:
https://github.com/apache/cloudstack/blob/master/ui/scripts/templates.js#L796

You may try to implement this based on the above description and reference implementation from the old UI and I can help with testing. Let me know if you're unable to do so, in which case pick another task from the list (I'll ping you on the other tasks if you want)?

**Comment by svenvogel** [comment]
@rhtyd sounds good. Let’s change to the suggestion from you.


__

Sven Vogel
Teamlead Platform

EWERK DIGITAL GmbH
Brühl 24, D-04109 Leipzig
P +49 341 42649 - 99
F +49 341 42649 - 98
S.Vogel@ewerk.com
www.ewerk.com

Geschäftsführer:
Dr. Erik Wende, Hendrik Schubert, Frank Richter
Registergericht: Leipzig HRB 9065

Support:
+49 341 42649 555

Zertifiziert nach:
ISO/IEC 27001:2013
DIN EN ISO 9001:2015
DIN ISO/IEC 20000-1:2011

ISAE 3402 Typ II Assessed

EWERK-Blog<https://blog.ewerk.com/> | LinkedIn<https://www.linkedin.com/company/ewerk-group> | Xing<https://www.xing.com/company/ewerk> | Twitter<https://twitter.com/EWERK_Group> | Facebook<https://de-de.facebook.com/EWERK.IT/>

Mit Handelsregistereintragung vom 09.07.2019 ist die EWERK RZ GmbH auf die EWERK IT GmbH verschmolzen und firmiert nun gemeinsam unter dem Namen: EWERK DIGITAL GmbH, für weitere Informationen klicken Sie hier<https://www.ewerk.com/ewerkdigital>.

Auskünfte und Angebote per Mail sind freibleibend und unverbindlich.

Disclaimer Privacy:
Der Inhalt dieser E-Mail (einschließlich etwaiger beigefügter Dateien) ist vertraulich und nur für den Empfänger bestimmt. Sollten Sie nicht der bestimmungsgemäße Empfänger sein, ist Ihnen jegliche Offenlegung, Vervielfältigung, Weitergabe oder Nutzung des Inhalts untersagt. Bitte informieren Sie in diesem Fall unverzüglich den Absender und löschen Sie die E-Mail (einschließlich etwaiger beigefügter Dateien) von Ihrem System. Vielen Dank.

The contents of this e-mail (including any attachments) are confidential and may be legally privileged. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system. Thank you.

Am 07.01.2020 um 04:51 schrieb Rohit Yadav <notifications@github.com>:

﻿

@utchoang<https://github.com/utchoang> this is a tricky one as it requires an environment that can access SSVM public IP to upload the file, the reference/test server (acs.shapeblue.com) on port-forwards to the management server so you won't be able to access the internal ssvm public IP. The other issue is that this features requires the environment to be SSL enabled as the URL returned by the getUploadParamsForTemplate API is https enabled. For example as seen in dev tools:

[Screenshot from 2020-01-07 09-03-41]<https://user-images.githubusercontent.com/95203/71866693-1db65780-312d-11ea-9cc8-a0d07df50efc.png>

The code for all of the upload feature (for uploading template, iso and volume) roughly follows this pattern:

  *   Call to register the template/iso/volume via the getUploadParamsForTemplate/getUploadParamsForIso/getUploadParamsForVolume
  *   This API returns post URL, and some secrets/signatures
  *   The UI makes a HTTP post request of the file and receives 'upload successful' or some suitable message

[Screenshot from 2020-01-07 09-17-48]<https://user-images.githubusercontent.com/95203/71867083-b3061b80-312e-11ea-8113-0ecceb8dc774.png>
[Screenshot from 2020-01-07 09-17-58]<https://user-images.githubusercontent.com/95203/71867084-b39eb200-312e-11ea-944b-c1580201c8c0.png>

For code reference you can see:
https://github.com/apache/cloudstack/blob/master/ui/scripts/templates.js#L796

You may try to implement this based on the above description and reference implementation from the old UI and I can help with testing. Let me know if you're unable to do so, in which case pick another task from the list (I'll ping you on the other tasks if you want)?

**Comment by rhtyd** [comment]
@utchoang will you be able to work on it? Otherwise you may also have a look at:
https://github.com/apache/cloudstack-primate/issues/39 (I can explain in detail, as it will a slightly complex task requiring some ldap setup)

**Comment by rhtyd** [comment]
@utchoang I guess you can pick this one next, thanks.

**Comment by rhtyd** [comment]
@utchoang are you able to work on it next? Thanks.

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel  - any update/progress on this? If you're unable to work, please do share so I can assign it to someone else.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I've taken a week off for holiday. I had informed Sven, and I should have kept you updated. I'm sorry for that.
I am back to work today. As discussed with Sven, I will pick up the task of iceteabottle. Please let me know which one is of higher priority to work on first.

**Comment by rhtyd** [comment]
Assigned to @Pearl1594 
Components that can be used:
https://www.antdv.com/components/upload/
https://www.antdv.com/components/radio/

Old code reference: https://github.com/apache/cloudstack/blob/master/ui/scripts/templates.js#L796 
(notice how post is sent). Here's an example on how to use `axios` for file upload: https://serversideup.net/uploading-files-vuejs-axios/

Open SSVM public IP in a new tab and open with `https://` end point and accept cert warning. Then test against old UI and primate.
The existing form components for register template and iso can be extended. A new component for volume upload would be needed though.

**Comment by rhtyd** [comment]
@utchoang please carry on Florian's work of VM deployment wizard.

**Comment by Android1968** [comment]
Guys same error here,any detailed solutions?
![iso error1](https://user-images.githubusercontent.com/58725374/82395961-4eb17c00-9a7f-11ea-9d06-292c6a88f685.png)
![iso error](https://user-images.githubusercontent.com/58725374/82395963-507b3f80-9a7f-11ea-9631-7470a549777b.png)

**Comment by svenvogel** [comment]
@rhtyd what do you think about this?

**Comment by rhtyd** [comment]
@Android1968 this feature requires SSL/TLS certificates to be setup in the env for SSVM. The screen shots are from legacy UI, if SSVM is SSL enabled it should work with Primate.

**Comment by Android1968** [comment]
> @Android1968 this feature requires SSL/TLS certificates to be setup in the env for SSVM. The screen shots are from legacy UI, if SSVM is SSL enabled it should work with Primate.

Thanks fo the info @rhtyd,do you have any link on how to do this in 4.13 release of Cloudstack?i find it hard because the resources are so limited for this version,thanks again mate!

**Comment by rhtyd** [comment]
Read the docs @Android1968 http://docs.cloudstack.apache.org/en/latest/adminguide/systemvm.html#using-a-ssl-certificate-for-the-console-proxy
