### ISSUE TITLE
[BUG] Set default CPU speed and CPU core count to zero (if not autopopulated from ASIS offering)

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#620]
I've NOT selected the EULA agreement, and when I click the button - there is no error shown (was showing/poping up previously)
(same goes for the password length check - there is a red warning around the password-input-field, but no popup error when you try deploying VM without honouring the needed length)

![image](https://user-images.githubusercontent.com/45762285/91191168-b9b0c580-e6f4-11ea-8aec-d1746dc29705.png)

**Comment by davidjumani** [comment]
@andrijapanicsb it shows up as a popup. But yes, will add a message below the checkbox too

![Screenshot from 2020-08-26 11-37-00](https://user-images.githubusercontent.com/8244774/91267303-b703ae00-e790-11ea-97f6-d264c9a3decc.png)

**Comment by davidjumani** [comment]
Adding message if form is incomplete via https://github.com/apache/cloudstack-primate/pull/609/commits/8d8954854ec9e8936810d397dfb661941e5fdbcf

![Screenshot from 2020-08-26 12-59-55](https://user-images.githubusercontent.com/8244774/91274268-0ef3e200-e79c-11ea-9491-4abff1f6e553.png)

**Comment by andrijapanicsb** [comment]
@davidjumani it did NOT show for me as a popup (but I have seen those popups some days ago) - so I though it's a regression?

**Comment by davidjumani** [comment]
@andrijapanicsb I've added a fix, you can try building it from #609 and try

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/628

**Comment by andrijapanicsb** [comment]
CPU speed is not set to zero, I will reopen once I retest/upgrade packages
