### ISSUE TITLE
[BUG] Clicking outside the form (i.e. new offering creation) closes the form

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#629]
![image](https://user-images.githubusercontent.com/45762285/91492040-3ab6bb00-e8b5-11ea-9129-b5c434717b10.png)

If you click outside of the form (i.e. the red circle on the image), the form is closed, and you get frustrated!

**Comment by utchoang** [comment]
Fixed in https://github.com/apache/cloudstack-primate/pull/631

**Comment by davidjumani** [comment]
@andrijapanicsb Not sure if this is a bug. A user might just want to cancel the form and clicking outside is a lot simpler than hitting cancel or 'x' cc @rhtyd

**Comment by andrijapanicsb** [comment]
LGTM
