### ISSUE TITLE
[BUG] Batch-deleting VMs doesn't show as completed when done

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#630]
Had a few running and a few VMs in Error state (error during deploying them, but they exist as VMs in vSphere)

Choosen to batch delete all of them - confirmed in vCenter that all running VMs were stopped, deleted (with those Error VMs not deleted, I've logged a separate bug in CloudStack for that) - but the Primate kept regreshing and showing those previously Running VMs as Stopping, while there are already stopped and deleted in vSphere:

![image](https://user-images.githubusercontent.com/45762285/91497210-d4826600-e8bd-11ea-8895-3bdaba323aaf.png)

**Comment by andrijapanicsb** [comment]
Hitting the Refresh button in instance view - will show zero VMs (as it should), since they are all deleted.

**Comment by davidjumani** [comment]
A simpler fix would be to refresh the list view every 30 seconds or so that the user has the most up to date info at any time, irrespective of any action performed. Thoughts @rhtyd ?

**Comment by rhtyd** [comment]
@davidjumani it may require some framework level fixes - could it be possible to track the list of asyncjobs somehow and then refresh when all have been completed? (instead of blind poling 30s)

**Comment by davidjumani** [comment]
Yes, but I think it's unnecessary. When refreshing the list view every 30 sec, there's always the latest data available to the user
