### ISSUE TITLE
[TESTPLAN] Smoketest for 1.0.0-GA with User Role, VMware (6.7) and ACS 4.15 (PR4250)

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#640]
Note: for User role test exclude after Account/User feature, for DomainAdmin role exclude after Infrastructure (except for Offerings)

**Instances**
- [x] Create instance using template
- [x] Create instance using ISO image and different parameters than the previous one
- [x] Test all VM actions - Start/Stop/Reboot/Reinstall/Update, etc
- [x] Add/modify/delete VM setting
- [x] Add network to VM, change IP address, make it default, delete
- [x] Add/delete secondary IP address

**Compute > Kubernetes**
This requires configuring and setting up CKS: http://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-service.html
- [x] Add Kubernetes cluster
- [x] Start/stop a Kubernetes cluster
- [x] Scale Kubernetes cluster
- [x] Upgrade Kubernetes cluster
- [x] Delete Kubernetes cluster

**Add Instance groups**
- [x] Add/modify/delete instance group

**SSH Key Pairs**
- [x] Add/delete SSH key pair

**Affinity Groups**
- [x] Add/delete host affinity group
- [x] Add/delete host anti-affinity group

**Volumes**
- [x] Create volume
- [x] Upload local volume
- [x] Upload volume from URL
- [x] Volume actions - snapshots, resize, migrate, download, create template

**Snapshots**
- [x] Snapshot actions - create template/volume, revert, delete

**VM Snapshots**
- [x] VM Snapshot actions - revert, delete

**Backups**
NA

**Guest networks**
- [x] Add isolated network
- [x] Add L2 network
- [x] Add shared network
- [x] Network actions - update, restart, replace ACL list, delete
- [x] Add/delete egress rules
- [x] Acquire IP address

**VPC**
- [x] Add VPC
- [x] VPC actions - updat, restart, delete
- [ ] Add security group - not possible with VMware
- [x] Add/delete ingress/egress rule
- [x] site-2-site VPN

**Public IP Addresses**
- [x] Acquire new IP
- [x] Actions - enable static NAT, release IP, enable VPN

**Templates**
- [x] Register template
- [x] Upload local template
- [x] Template actions - edit, download, update permissions, copy, delete

**ISOs**
- [x] Register ISO
- [x] Upload local ISO
- [x] ISO actions - edit, download update permissions, copy, delete

**Events**
- [x] Search, archive, delete

**Projects**
- [x] Add project
- [x] Project actions - edit, suspend, add account, delete
- [x] Different projects with different permission

**Accounts, users, roles**
- [x] Create/modify/check role/delete regular user account
- [ ] Create/modify/check role/delete resource admin account
- [x] Create/modify/check role/delete domain admin account
- [x] Create/modify/check role/delete admin user
- [x] Account actions - edit, disable, lock, delete

**Domains**
- [x] Create new domain
- [x] Create subdomain in the new domain
- [x] Delete the first domain (2nd, not 3rd level)
- [ ] Edit/delete domain
- [x] Modify domain limits/settings

**Roles**
- [x] Add new role
- [x] Role actions - edit, delete

**Infrastructure summary**

**Zones**
- [ ] Add zone
- [ ] Zone actions - edit, enable/disable, enable/disable HA, delete, etc.
- [ ] Modify settings

**Pods**
- [ ] Add pod
- [ ] Pod actions - edit, enable/disable, delete

**Clusters**
- [ ] Add cluster
- [ ] Cluster actions - enable/disable, unmanage, enable/disable HA, delete, etc

**Hosts**
- [ ] Add host
- [ ] Host actions - edit, enable/disable, maintenance mode, enable/disable/configure HA, etc.

**Primary storage**
- [ ] Add primary storage
- [ ] Primary storage actions - edit, enable/disable maintenance mode
- [ ] Settings - modify

**Secondary storage**
- [ ] Add secondary storage
- [ ] Delete secondary storage
- [ ] Settings - modify

**Compute offering**
- [ ] Add shared thin compute offering
- [ ] Add local fat compute offering
- [ ] Offering actions - edit, access, delete

**System offering**
- [ ] Add shared thin system offering for VR
- [ ] Add local sparse system offering for console proxy
- [ ] Offering actions - edit, delete

**Disk offering**
- [ ] Add shared thin disk offering
- [ ] Add local fat disk offering
- [ ] Offering actions - edit, access, delete

**Backup offering**
- [ ] Import offering
- [ ] Configure backup provider (Veeam)
- [ ] Create backup offering
- [ ] Assign VM to backup offering
- [ ] Revert to backup
- [ ] Delete backup
**Network offering**
- [ ] Add isolated network with some supported services
- [ ] Add L2 network
- [ ] Add shared network with some supported services
- [ ] Network actions - edit, enable/disable, access, delete

**VPC offering**
- [ ] Change VPC offerings order
- [ ] Add new VPC offering with some supported services
- [ ] VPC offering actions - edit, enable/disable, access, delete

**Global settings**
- [ ] Search setting
- [ ] Modify setting

**LDAP configuration**
- [ ] Add LDAP configuration
- [ ] Login with LDAP account

**Common functionality**
- [ ] Sorting
- [ ] Pagination
- [ ] Searching
- [ ] Add/remove tags
- [ ] Refresh
- [ ] Links

**Comment by rhtyd** [comment]
All user role specific test plan executed, closing
