### ISSUE TITLE
[BUG] Add message/questions when unmanaging an instance?

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#644]
Perhaps consider putting a simple "are you sure... once done, can't be undone" kind of question?

**Comment by rhtyd** [comment]
With @davidjumani

**Comment by rhtyd** [comment]
@andrijapanicsb fixed in https://github.com/apache/cloudstack-primate/pull/656 please review and close the issue, thnx

**Comment by andrijapanicsb** [comment]
LGTM
