### ISSUE TITLE
[BUG] List network's range with other details during VM deployment & MAC format explanation

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#648]
Not really a bug, but an improvement to make the "choose IP" even possible/usable:

![image](https://user-images.githubusercontent.com/45762285/91810690-9fb03f00-ec2e-11ea-9ff5-8df2518503d8.png)

As an end-user, I would like to see here the IP range of the network, to be able to KNOW from which range to use an IP when specifying it explicitly down for the NIC attached to that network. Otherwise, I need to rely on memory/knowing from top of my head what is the IP range, or getting out of the wizard and observing that.

**Comment by andrijapanicsb** [comment]
To avoid opening a new BUG, can we also add a note somewhere/somehow of an expected format for the MAC address, as just numbers is not correct, need to be in format aa-bb-cc-dd-ee-ff (i.e. aabbccddeeff or aa:bb:cc:dd:ee:ff doesn't work)

![image](https://user-images.githubusercontent.com/45762285/91814105-efddd000-ec33-11ea-8611-14a85cf9e300.png)

**Comment by rhtyd** [comment]
@utchoang can you add a mac address validator on the input, I think the format `01:23:45:67:89:ab` should work cc @andrijapanicsb

**Comment by andrijapanicsb** [comment]
it already works, by requiring the dash instead od the column (well, once you submit the job?) - so all good - I just would like to see a note (or validate while typing if possible) - so that user KNOWs which format is needed.
