### ISSUE TITLE
[BUG]  Minor: update label/text

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#652]
![image](https://user-images.githubusercontent.com/45762285/91822617-54029300-ec38-11ea-9082-609747bb1387.png)

Should be "...AS default"  or "...AS default network" not "to"

**Comment by andrijapanicsb** [comment]
Also, there is no hover popup for "make this NIC default" button (and there is for other buttons, except for the delete/bin which is self-explanatory):

![image](https://user-images.githubusercontent.com/45762285/91851131-f3d31780-ec5e-11ea-82ba-383e34dfe8b9.png)

**Comment by rhtyd** [comment]
@andrijapanicsb fixed in https://github.com/apache/cloudstack-primate/pull/655, please review and close the issue

**Comment by andrijapanicsb** [comment]
LGTM
