### ISSUE TITLE
[BUG] Click Instance --> Click Volume = breadcrumb gone

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#653]
clicking on the volume of the instance moves the "breadcrumb" to volumes, so you can't click back on the instance whose volume you are viewing atm (I can use the browser back button, but that's not the same)

![image](https://user-images.githubusercontent.com/45762285/91840329-d26b2f00-ec50-11ea-8983-70a43fb9753b.png)

![image](https://user-images.githubusercontent.com/45762285/91840379-e6169580-ec50-11ea-9986-2e5099a04467.png)

**Comment by rhtyd** [comment]
@andrijapanicsb the intention was to use and encourage users to use the browser back button

**Comment by andrijapanicsb** [comment]
I don't personally like it (due to used to consume breadcrumb), but hey, that's my problem. Closing.
