### ISSUE TITLE
[BUG] Regular users should not see their network's VLAN

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#659]
Old UI doesn't show it. I'm wondering if we should also hide it:
![image](https://user-images.githubusercontent.com/45762285/91850871-8f17bd00-ec5e-11ea-8a4a-de526156cdd3.png)

**Comment by rhtyd** [comment]
@andrijapanicsb fixed in https://github.com/apache/cloudstack-primate/pull/661 please review and close the issue, thnx

**Comment by andrijapanicsb** [comment]
LGTM
