### ISSUE TITLE
[BUG] K8s version - various issues ?

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#660]
I might be doing something wrong, but I don't think so?
Seems like a backend issue ?
![image](https://user-images.githubusercontent.com/45762285/91860067-79f55b00-ec6b-11ea-87d6-20214b1be89c.png)

![image](https://user-images.githubusercontent.com/45762285/91860133-92657580-ec6b-11ea-8bc2-a82a66b33472.png)

**Comment by andrijapanicsb** [comment]
If I change that to 2 CPUs, then this doesn't fail but version format fails or something:

![image](https://user-images.githubusercontent.com/45762285/91860541-17508f00-ec6c-11ea-8a08-ebbb6af2adeb.png)
![image](https://user-images.githubusercontent.com/45762285/91860583-233c5100-ec6c-11ea-8797-d452d65a1675.png)

cc @shwstppr can you please test drive the K8s plugin in primate - I'm not sure if I'm doing something wrong, at least based on the official docs it should be fine.

**Comment by andrijapanicsb** [comment]
the version needs to be specified as 1.15.0 (or x.y.z in general?) then it works fine (and with 2 CPU)

 Should we have a popup (the "i" letter) that says "specify the version in format x.y.z" ? @shwstppr cc @davidjumani

**Comment by rhtyd** [comment]
@andrijapanicsb looks like 2CPU is a requirement and the version needs to be 1.15.0 as there is no k8s 1.15 release but 1.15.0 or 1.15.1 release. Have you followed the docs http://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-service.html ?

**Comment by shwstppr** [comment]
I've added some improvements here, https://github.com/apache/cloudstack/pull/4269, error messages and API param description. I've not explicitly tied 2vCPU, 2GB memory requirement in UI as it might change once we move to a different template (from CoreOS)

**Comment by rhtyd** [comment]
Do we need to make any change in Primate @shwstppr cc @andrijapanicsb @davidjumani ?

**Comment by shwstppr** [comment]
@rhtyd I don't think any changes will be needed in Primate. Though, maybe we can verify backend changes with Primate which should show better error messages and parameter information now

**Comment by rhtyd** [comment]
Closing on your remark @shwstppr
