### ISSUE TITLE
[FEATURE] Disable values starting with a space 

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#668]
![image](https://user-images.githubusercontent.com/45762285/92383657-08a42500-f10f-11ea-88b9-131ec74af753.png)

Copying the global setting value (or some other value from UI), adds space in front of the copied text, then when pasting I managed to have a template whose name starts with space....

**Comment by shwstppr** [comment]
@rhtyd @davidjumani can we have textinput to trim entered text while submitting the form?

**Comment by utchoang** [comment]
@rhtyd I think we need to trim text input after entered?

**Comment by davidjumani** [comment]
We can do it both ways, but it would be better to trim it during the submit, to reduce the code changes introduced

**Comment by rhtyd** [comment]
@andrijapanicsb it may cause unexpected results in some cases, what is somebody wants to put space in front/end of a string input? Does old UI trim the space too ? I'm tentatively pushing this to 1.1 as it's not a critical/blocker issue.

**Comment by rhtyd** [comment]
David checked and it's an issue at backend, fixing this in UI will still allow API to do this - so ideally the backend should trim the space.

**Comment by davidjumani** [comment]
Fixed in the backend via https://github.com/apache/cloudstack/pull/4311

**Comment by rhtyd** [comment]
Closing based on @davidjumani 's remark, the fix at backend needs to be cautious but will utlimately fix the issue for all kinds of client inputs (UI, API...)
