### ISSUE TITLE
[BUG] VM Deployment wizard not listing existing "Instance Groups"

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#669]
Perhaps for discussion...

We can create Instance Groups (a dedicated menu in Priamte, while missing in old UI) = but it seems existing groups are not listed (to be able to select some of the existing groups) when deploying a VM

So, having a dedicated Instance Groups menu is (atm) useless, as you can not select them during VM deployment.
Either remove it (menu item), or (preferably) call the listInstanceGroups API in VM deployment...?

**Comment by rhtyd** [comment]
@davidjumani see the auto-complet-able a-input (see similar used in Role->rules) which can show a list of available VM instance groups to the user as well as allow any kind of new string input for the groups input (end of VM deployment form)

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
LGTM
