### ISSUE TITLE
[BUG] Sensitive vcenter info should be hidden from the "user" role

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#670]
had volume, deleted it withOUT expinging it, recovered it, tried to attach it again - and got the error (could reproduce it this way twice) - beside being ACS bug, we should not expose vCenter IP and disk path etc... on vCenter/storage:

![image](https://user-images.githubusercontent.com/45762285/92389665-ccc28d00-f119-11ea-9249-2c7be180fafc.png)

**Comment by davidjumani** [comment]
@andrijapanicsb Primate just displays the error thrown by the backend. This will require a backend fix

**Comment by rhtyd** [comment]
@andrijapanicsb this is same as what you see in old UI, any exception thrown is usually shown as an alert which shows error from the backend API response

**Comment by rhtyd** [comment]
Closing on this remark, please reopen if you disagree @andrijapanicsb thnx
