### ISSUE TITLE
[BUG] Refresh list of systemVMs if some are starting/stopping/destroying

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#671]
![image](https://user-images.githubusercontent.com/45762285/92391082-54110000-f11c-11ea-8d10-2ad2ba417407.png)

there are circles going around the blue buttons, but in reality no API call to query status of VMs etc...

**Comment by davidjumani** [comment]
Can be fixed by tweaking https://github.com/apache/cloudstack-primate/pull/662

**Comment by rhtyd** [comment]
@andrijapanicsb currently we don't have a event-based way to know if a resource state has changed, so we cannot know for all sorts of resources (including systemvms) - old UI shares the same limitation and therefore you're required to refresh

**Comment by andrijapanicsb** [comment]
If not possible to fix it easily - ok, let's close it.

**Comment by rhtyd** [comment]
Yes, thanks. Closing this on your remark.
