### ISSUE TITLE
[BUG] L2 networks - there is nothing to clean-up or make redundant

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#674]
Although this is on pair with the old UI - we should probably remove this (or the whole restart button) for L2 networks, as there is no VR inside, so there is nothing to "cleanup" (recreate VR) nor anything to make redundant (as there is no VR). 

In general, what does it mean to restart an L2 network? (should we remove the button)?

![image](https://user-images.githubusercontent.com/45762285/92576557-f39fd100-f289-11ea-9115-282dea6e4b2e.png)

**Comment by utchoang** [comment]
@rhtyd By this issue, we'll hide the restart network button for the L2 network?

**Comment by davidjumani** [comment]
@utchoang Yes!

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
LGTM, button hidden
