### ISSUE TITLE
[BUG] Zones not listed/offered when deploying a VM in a network from a VPC view.

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#675]
![image](https://user-images.githubusercontent.com/45762285/92610427-fa453d00-f2b7-11ea-8299-03ade15cb5b2.png)

click on Add Instance and then you get:

![image](https://user-images.githubusercontent.com/45762285/92610511-0e893a00-f2b8-11ea-844a-9c76aab21e33.png)

**Comment by ravening** [comment]
Tested this now and was not able to reproduce it. All zones got listed after clicking on "New instance" from vpc -> networks section

**Comment by andrijapanicsb** [comment]
Using now the latest master, I can also NOT reproduce it - closing.

**Comment by rhtyd** [comment]
@andrijapanicsb I've tested David's PR and merged it
