### ISSUE TITLE
[BUG] ACLs - 2 issues with displaying them

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#676]
VPC, ACL.

issue1: when go to particular VPC, then to network, then click on the network (to mange it, replace acl, whatever...) - there is no ACL shown (to be able to know which ACL is ALREDY applied on the network) - in the old UI, this is shown when managing a network:
![image](https://user-images.githubusercontent.com/45762285/92611584-3af18600-f2b9-11ea-93f9-1787ddfe9841.png)

instead, the ACL is only visible on network listing  -  issue2:
when we select a VPC and click on networks - there is ACL UUID shown, instead of it's name:
![image](https://user-images.githubusercontent.com/45762285/92611750-670d0700-f2b9-11ea-801c-751f45599a57.png)

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
Doesn't look good on the latest master @rhtyd @ravening ?
![image](https://user-images.githubusercontent.com/45762285/92919945-b2e2bc00-f431-11ea-8054-7d3fa205a990.png)

ACL also, still, not displayed when you click on the network - as a user, when I'm viewing network properties, I prefer to see ACL as well, if possible:

![image](https://user-images.githubusercontent.com/45762285/92920007-d3127b00-f431-11ea-98ec-a2c85323b1b1.png)

**Comment by ravening** [comment]
@andrijapanicsb @rhtyd it wont work until https://github.com/apache/cloudstack/pull/4317 is merged.

**Comment by andrijapanicsb** [comment]
merged, thx

**Comment by andrijapanicsb** [comment]
@ravening I've just realised I merged the ACS, not primate PR :)

Ok, will trust that, since I'm short on time to merge this to my test-env, etc.

Thanks

**Comment by andrijapanicsb** [comment]
To be tested with master later - leaving the issue opened until tested.

**Comment by ravening** [comment]
@andrijapanicsb did you get chance to test this?

**Comment by DaanHoogland** [comment]
both confirmed on latest
