### ISSUE TITLE
[BUG] With VPC - LoadBalancing tab should be hidden if the IP is already used for i.e. Port Forwarding or Static NAT

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#678]
In VPC, there is no preserve mode with Public IPs - and for Port Forwarding, StaticNAT and LoadBalancing - if any of these services is enabled on a single (additional) Public IP - the other 2 services/tabs/buttons should be hidden - otherwise, user will attempt to configure and get an error like below (an expected error):

![image](https://user-images.githubusercontent.com/45762285/92614774-b7d22f00-f2bc-11ea-8185-30d2bf111769.png)

**Comment by ravening** [comment]
@andrijapanicsb I dont see any port forwarding or loadbalancer tab is static nat is enabled

![Screenshot 2020-09-14 at 12 50 05](https://user-images.githubusercontent.com/10645273/93077240-d2275680-f688-11ea-967a-bf1671e9bb41.png)


If its not enabled then I see both tabs

![Screenshot 2020-09-14 at 12 50 42](https://user-images.githubusercontent.com/10645273/93077303-e703ea00-f688-11ea-9898-60570d35d641.png)

**Comment by andrijapanicsb** [comment]
that is correct only for StaticNAT @ravening - needs to be fixed also for PF or LB - I'm not sure if @davidjumani is already on it or not?

**Comment by davidjumani** [comment]
@andrijapanicsb Havn't started on it yet

**Comment by rhtyd** [comment]
@davidjumani can you pick this or advise @utchoang on what/how to fix this? Thanks

**Comment by davidjumani** [comment]
@utchoang I think fixing this would involve merging DetailsTab, FirewallRules, PortForwarding, LoadBalancing and VpnDetails into a single tabbed vue. Once this is done :
1. If the resource has port forwarding / load balancing rules, the enableStaticNat button should be hidden.
2. If it is an ip associated with a vpc network, allow adding firewall rules, and either port forwarding or load balancing rules. Hide the port forwarding tab if load balancing rules are present and vice versa

**Comment by rhtyd** [comment]
@andrijapanicsb can you check the behaviour against old UI?

**Comment by utchoang** [comment]
@rhtyd @davidjumani Currently I don't know which field to rely on to hide the Load Balancer Rule or PortFowardRule tab.
![image](https://user-images.githubusercontent.com/13766648/93982272-3c3bac00-fdab-11ea-944e-492cc8d9c810.png)
Or is it based on getting data from the 2 API `listPortForwardingRules` and `listLoadBalancerRules`?

**Comment by davidjumani** [comment]
It is based on the `listPortForwardingRules` and `listLoadBalancerRules` apis, while the vpcid filed indicates whether it belongs to a vpc

**Comment by rhtyd** [comment]
@utchoang I've created/tested the cases that you can check and fix. Here are the cases: (@andrijapanicsb appreciate if you can be more specific while filing bugs, thanks)

:heavy_check_mark: Case 1 - in case of static NAT I've verified that we don't show any tabs: (old UI has same UX)

![Screenshot from 2020-09-23 18-00-38](https://user-images.githubusercontent.com/95203/94012686-c04f5d00-fdc6-11ea-967f-b30d753a68b1.png)

:heavy_multiplication_x: Case 2 - VPC has LB rule, it shouldn't show firewall or PF tabs:

![Screenshot from 2020-09-23 18-03-10](https://user-images.githubusercontent.com/95203/94013134-47043a00-fdc7-11ea-9513-0c8cc9adec7a.png)
![Screenshot from 2020-09-23 18-04-39](https://user-images.githubusercontent.com/95203/94013142-48356700-fdc7-11ea-87a3-a28ba3c169be.png)

:heavy_multiplication_x: Case 3 - VPC has PF rules, it shouldn't show firewall or LB tabs:
![Screenshot from 2020-09-23 18-05-28](https://user-images.githubusercontent.com/95203/94013259-72872480-fdc7-11ea-8223-024a3eb41c1c.png)
![Screenshot from 2020-09-23 18-05-39](https://user-images.githubusercontent.com/95203/94013261-73b85180-fdc7-11ea-90ca-cc8dbd920514.png)

:heavy_check_mark: Case 4 - in case the VPC IP has no tier, PF or LB rules, we should show PF and LB tabs for VPC:

![Screenshot from 2020-09-23 18-06-38](https://user-images.githubusercontent.com/95203/94013410-a6fae080-fdc7-11ea-9e71-e08cf1f43601.png)
![Screenshot from 2020-09-23 18-07-36](https://user-images.githubusercontent.com/95203/94013426-afebb200-fdc7-11ea-8372-ef543bfcc1e9.png)

**Comment by rhtyd** [comment]
@utchoang the real issue are only case 2 and 3; it may need tweaking here https://github.com/apache/cloudstack-primate/blob/master/src/components/view/ResourceView.vue#L115 (we may need to somehow emit and ensure this code runs, after doing the specific list APIs calls (for listing pf and lb rules) and then hide appropriately)

**Comment by andrijapanicsb** [comment]
> 
> 
> @andrijapanicsb can you check the behaviour against old UI?

I did check, and went with @davidjumani in details through the old UI etc.
This is kinda common thing to check the old UI and it's a matter of 1.5minute testing.
