### ISSUE TITLE
[BUG] Tags not possible to be set on a  LB rule

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#679]
![image](https://user-images.githubusercontent.com/45762285/92615582-8d34a600-f2bd-11ea-8dae-da1a06216580.png)

**Comment by andrijapanicsb** [comment]
Same is true for VPC or Isolated Network LB rules

**Comment by rhtyd** [comment]
@andrijapanicsb pl test and close

**Comment by DaanHoogland** [comment]
works on latest
