### ISSUE TITLE
[BUG] Something spinning when choosing a destination VM for a PF rule

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#680]
![image](https://user-images.githubusercontent.com/45762285/92616134-2a8fda00-f2be-11ea-9474-141807627376.png)

 (IP address not fetched?)

**Comment by andrijapanicsb** [comment]
Same happens in other forms - i.e. when adding a destination VM for a LB rule (happens only after you select a VM, before pressing OK)

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
LGTM, can see/use Secondary IPs as well, etc.
