### ISSUE TITLE
[BUG] Buttons not clickable while error popup present

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#689]
I can't click the template sharing buttong while the popup is there - IMHO I should be able to click on what I want - perhaps should be tested with other kind of popups (not just error - if that makes sense/difference)

![image](https://user-images.githubusercontent.com/45762285/92698390-9751b580-f34c-11ea-92f7-cad7c71b3d2f.png)

**Comment by andrijapanicsb** [comment]
Even if go to Instances and try to operate the buttons - they are not clickable.

**Comment by rhtyd** [comment]
@andrijapanicsb Well you can click on the cross to close the error box?

**Comment by rhtyd** [comment]
I'll close this as buttons are clickable once the popup error notification is closed
