### ISSUE TITLE
[BUG] Hide "Public" switch if the global setting prohibits "user" making templates public

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#690]
![image](https://user-images.githubusercontent.com/45762285/92698486-bea88280-f34c-11ea-9c33-67361da7c088.png)

It's allowed, with a proper error message - not critical, but we should hide it if the global setting value prohibits regular "user" role to make templates public.

**Comment by andrijapanicsb** [comment]
If fixing this - please do the same on "Register template" and Register ISO forms - and same for the Upload from Local (template/iso)

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
LGTM in all possible forms.
