### ISSUE TITLE
[BUG] regular user can't archive/delete (any/his own) events - buttons missing!

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#694]
![image](https://user-images.githubusercontent.com/45762285/92721888-10f69d00-f367-11ea-9a60-47b151bd95ed.png)

**Comment by andrijapanicsb** [comment]
even ADMIN can't delete (missing buttons) in the main view of all events - for admin only when you select a single event, you can archive/delete that one - this all needs to be fixed - please see the old UI for comparison. thx

**Comment by davidjumani** [comment]
@andrijapanicsb This was specifically removed for users since they should not be able to delete their events from a security pov. Will look into why admins can't delete them

**Comment by davidjumani** [comment]
Checkboxes hid via https://github.com/apache/cloudstack-primate/issues/694

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master; merged David's #698

**Comment by andrijapanicsb** [comment]
LGTM, but I've raised 2 related ones for events listing/deletion
