### ISSUE TITLE
[BUG] "user" role - reset password form broken

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#700]
![image](https://user-images.githubusercontent.com/45762285/92876619-9f702a80-f40a-11ea-8316-9f35dde3b96b.png)

as a regular user role - chaning your own pass (works fine when "admin" reset other user's pass.

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest master

**Comment by andrijapanicsb** [comment]
LGTM
