### ISSUE TITLE
[BUG] "VPN uses" missing from the network-related main menu

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#703]
on old UI:
![image](https://user-images.githubusercontent.com/45762285/92920559-c0e50c80-f432-11ea-8ec6-0db620b41d7e.png)
(once you enable at least one remote VPN on any network/VPC - otherwise is hidden)

![image](https://user-images.githubusercontent.com/45762285/92920803-2f29cf00-f433-11ea-9578-aecdc7d1dac2.png)

**Comment by andrijapanicsb** [comment]
If we blindly add the vpn user to the main menu

there is some strange behaviour while adding/deleting users - so I guess that is the reason why the menu time "vpn users" us hidden in the old UI when there are zero remote-VPN enabled for the logged-in account:
![image](https://user-images.githubusercontent.com/45762285/92921986-52ee1480-f435-11ea-8e9b-6b353ce5e34a.png)


![image](https://user-images.githubusercontent.com/45762285/92921940-436ecb80-f435-11ea-8dec-53c02035b8c3.png)

So we need to also selectively show it - or possibly fix the backend (assuming it's a quick fix) and then always show the menu

- if we always show it, we need to do end-to-end testing:
-- user1, user2 existing, remove all remote-VPN for any networks/VPCs, delete user1, add user3, enable VPN again and observe if user1 and user3 only exist inside a VR where the VPN was enabled

**Comment by ravening** [comment]
@andrijapanicsb I was able to add vpn user only if there are existing remote access vpn connection.
In the old ui, we first check the count of remote access vpn. If its > 0 then we display "Vpn Users" entry else it hidden


But in new UI, `hidden: true` is always set and so even if we have active remote vpn connections, it wont show up.

**Comment by andrijapanicsb** [comment]
Alright - so we need a fix for this - to show only when there is > 0 VPNs enabled for the given account...

**Comment by rhtyd** [comment]
@andrijapanicsb I think I added the navigation from the IP/tab where you enable VPN. So go to network -> IP -> VPN tab, if VPN is enabled there's a button to manage VPN users. I think the VPN enabled is for all networks accessible for an account.

**Comment by andrijapanicsb** [comment]
that is true @rhtyd - if we are OK to change the "location" of where the user can find his "VPN users" - I can live with that.
But in the old UI, those users are visible both from that location your explained, and also from the main "Networks" menu

**Comment by rhtyd** [comment]
I'm closing on your remark Andrija, there is a navigation management possible by going to a network -> IP -> VPN tab -> manage users.
