### ISSUE TITLE
[BUG] listing 500 events per page breaks page

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#705]
listing 100 events per page works fine.
going to **500** breaks the page, the request is taking an insane amount of time to get any reply from the mgmt (based on the developer tools), then it gives an error like in the following screenshot:

![image](https://user-images.githubusercontent.com/45762285/92930691-b29eec80-f442-11ea-99ba-edbffcc75484.png)

**Comment by davidjumani** [comment]
@andrijapanicsb The count is the total number of events, but the event array will only contain 500. I've tested it and although it takes time to fetch the data, the page still loads successfully.
It could be a network issue that you've experienced

**Comment by andrijapanicsb** [comment]
I'm absolutely sure it was not my network, as I was reproducing the issue a few times in a row, and never had the issue with 100/page.

But on the latest master, it looks good (beside Firefox complaining that page is slowing down my computer etc - 6 core machine...)

Wondering if going down from 500 to 200 as the max limit makes sense / is possible - if not please close the issue @davidjumani 
Thx

**Comment by rhtyd** [comment]
Closing on your remark @andrijapanicsb and the other issue, we can limit max. page size to 200 which is a fairly large number
