### ISSUE TITLE
[BUG] PROPOSAL: Reduce max pagination from 500/page to 200/page

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#708]
- If you choose to list 500 records per page in i.e. Event, the machine with 6 CPU cores @ 4.0 Ghz becomes almost unusable (Firefox does complain that the page is slowing down the computer
- If you list 500 records (events) per page, then select them all (checkbox) and try to delete, yiou get the URL too long error.

![image](https://user-images.githubusercontent.com/45762285/93056673-07be4680-f66d-11ea-86ab-35af79e07b74.png)

In general, I think 500 is simply too much, and 200 works acceptably (slow) with no errors seen so far (i.e. I don't get the URL too long etc)

Should we reduce the max records per page from 500 to 200?
@rhtyd @utchoang @davidjumani

**Comment by utchoang** [comment]
@andrijapanicsb Agree, I think 200 items per page is ok. 
@rhtyd @davidjumani Thoughts?

**Comment by rhtyd** [comment]
The max limit 500 was used as that's why is documented for most APIs (the max. limit of page size to be 500). But I see no harm in using 200 as max page size for UI.
@utchoang feel free to raise a PR for this UI-wide (mostly auto-gen view and few other places) Thnx

**Comment by rhtyd** [comment]
Merged, please test latest master and close @andrijapanicsb

**Comment by rhtyd** [comment]
I'll save you some effort, LGTM
