### ISSUE TITLE
[BUG]  '@link-color' does not effect the mouse-over color in details section

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#712]
**Describe the bug**

config.json property '@link-color' changes navigation section mouse-over color of links, but not the mouse-over colour in the details.

**To Reproduce**
Steps to reproduce the behavior; '@link-color' in the config.json file.

1. change the property 

**Expected behavior**

The mouse-over colour in the details section changes to match the color set in the config.json file

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/93192132-3dcafb80-f73d-11ea-8efe-e9e57b38a69a.png)

**Additional context**

**Comment by rhtyd** [comment]
Hi @utchoang since you had added support for theming in Primate, can you look into adding support for link:hover or make it use the configured link-color when mouse is hovered on links. cc @svenvogel

**Comment by rhtyd** [comment]
@utchoang out of curiosity would it also be possible to add support for (a) general background colour (say for a black/dark theme) and (b) ensure that primary colour is used for popup notification loader (which floats when an action is performed such as stopping a VM, it shows a rotating circle in blue colour irrespective of primary colour)

**Comment by utchoang** [comment]
@rhtyd I think this is doable. I will try it out and notify you later. Thanks.

**Comment by DaanHoogland** [comment]
not sure if this is what @PaulAngus meant:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/2486961/93806152-08487580-fc49-11ea-818f-1e1c29295de2.png">
the link color is changed as expected but the hovored link is still the default.

**Comment by DaanHoogland** [comment]
tests ok in pr #718

**Comment by rhtyd** [comment]
LGTM, verified link and hover colour
![Screenshot from 2020-09-23 11-28-03](https://user-images.githubusercontent.com/95203/93972433-e4dc1280-fd8f-11ea-92c1-0e22f3c5d05f.png)

**Comment by rhtyd** [comment]
Vefied and close in PR #718
