### ISSUE TITLE
[BUG] '@processing' color does not affect the page loading progress or circular 'I'm thinking' graphic

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#713]
**Describe the bug**

**To Reproduce**

Change the property  '@processing' in the config.json file.

1. go to Primate URL (see large 'thinking' graphic is still blue)
2. Log in as user or admin.  (see small 'thinking' graphic and page loading bar at the top of the page are still blue)

**Expected behaviour**

- 'thinking' graphic and page loading bar should match the '@processing' bar.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/93194035-897ea480-f73f-11ea-87b0-369f6c0701ae.png)

**Additional context**

**Comment by rhtyd** [comment]
@PaulAngus actually the variable names are from Vue/AntDesign the `@processing-color` is what is uses for status button/icon used for a resource (such as VM state etc) - https://antdv.com/components/badge/#components-badge-demo-status

@utchoang can you look into this as well - is it possible to use the defined primary-colour for the loaders?

**Comment by DaanHoogland** [comment]
can't get the processing colors to change, @utchoang can you help? the only config item i see to change is  `"@processing-color": "#e02020"`, is that the item to change? if so, it doesn't work.

**Comment by DaanHoogland** [comment]
tests ok in 718 (except I don't seem to understand the rgba(0, 0, 0, 0.15))

**Comment by rhtyd** [comment]
LGTM, verified action notification loading icon colour
![Screenshot from 2020-09-23 11-26-11](https://user-images.githubusercontent.com/95203/93972460-ee657a80-fd8f-11ea-8eca-fc1cf915b8f5.png)

**Comment by rhtyd** [comment]
Vefied and close in PR #718
