### ISSUE TITLE
[BUG] (UI) (borderline feature request) - can't change the navigation menu color for default view or project view

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#714]
**Describe the bug**

**To Reproduce**

none - can't do it...

**Expected behavior**

To match all other branding, a cloud operator will likely want to change the navigation background colors.

**Screenshots**

![image](https://user-images.githubusercontent.com/4810220/93197482-9ac9b000-f743-11ea-9fc1-fabae922acf3.png)  

![image](https://user-images.githubusercontent.com/4810220/93197563-b59c2480-f743-11ea-9166-2a3166e3173a.png)

**Additional context**

**Comment by rhtyd** [comment]
@PaulAngus I'm able to change the primary-color option that affects the color of selected navigation menu item and see this for default and project views:

![Screenshot from 2020-09-15 15-50-08](https://user-images.githubusercontent.com/95203/93198845-315d9780-f76b-11ea-99d8-a3dbbf8cd968.png)

![Screenshot from 2020-09-15 15-50-19](https://user-images.githubusercontent.com/95203/93198848-33275b00-f76b-11ea-9ec4-5f828a7dc99a.png)

Or do you mean the background colour?

**Comment by PaulAngus** [comment]
yes actual background colour, current white or blue.

**Comment by rhtyd** [comment]
@utchoang can you explore if we can change the background of left nav bar for light vs dark mode ?

**Comment by utchoang** [comment]
@rhtyd This is OK. I'll add to #718

**Comment by DaanHoogland** [comment]
looks ok: 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/2486961/93815490-57e16e00-fc56-11ea-89f4-7dfefb4b9e66.png">

**Comment by PaulAngus** [comment]
just to check, it was the **_background_** colour of the navigation bar, rather than links.

**Comment by PaulAngus** [comment]
I may want it blue, red, white, yellow to match the branding in the data panel

**Comment by rhtyd** [comment]
@PaulAngus from one of the screenshot's I see from Hoang's PR, the background is set to brown and lgtm - https://github.com/apache/cloudstack-primate/pull/718#issuecomment-694708920

**Comment by rhtyd** [comment]
Verified left nav bar colour for default view:
![Screenshot from 2020-09-23 11-26-11](https://user-images.githubusercontent.com/95203/93972489-fcb39680-fd8f-11ea-8716-ed315710f286.png)

Project view is still dark-er though:
![Screenshot from 2020-09-23 11-29-26](https://user-images.githubusercontent.com/95203/93972559-17860b00-fd90-11ea-8712-87f77093c85a.png)

**Comment by rhtyd** [comment]
Vefied and close in PR #718
Caveat - the navigation bar background colour is the same across default and project view
