### ISSUE TITLE
[BUG] "OS Type" not shown in instance view

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#720]
old UI:
![image](https://user-images.githubusercontent.com/45762285/93359769-4574c800-f843-11ea-80f2-b339e28bb33d.png)

new UI is missing this field
Would be nice for someone to systematically go through the list of details that are displayed on old UI (for instances at least) and compare to the detailed displayed in Primate for the same instance.

**Comment by rhtyd** [comment]
@andrijapanicsb I think it is when you move cursor on the OS icon

**Comment by rhtyd** [comment]
@andrijapanicsb pl test and close

**Comment by DaanHoogland** [comment]
fixed in latest
