### ISSUE TITLE
[FEATURE] Clicking anywhere on the line (instead of just the radio button) should select the i.e. Offering

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#721]
![image](https://user-images.githubusercontent.com/45762285/93462012-e916b480-f8e5-11ea-8320-77dd20a2705a.png)

I would like to be able to click anywhere on the line in order to select the offering - instead of having to click only the "radio button"

**Comment by utchoang** [comment]
@andrijapanicsb @rhtyd cc @svenvogel  Does this apply to disk offerings, networks, security, and affinity group?

**Comment by andrijapanicsb** [comment]
I would say - let's apply it EVERYWHERE where there are radio buttons?
