### ISSUE TITLE
[BUG] minor: center the name of the network for L2 network

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#724]
![image](https://user-images.githubusercontent.com/45762285/93624046-fc0daf80-f9df-11ea-9833-bbf4fa41ff49.png)

if possible, center (vertically) L2 networks (other networks have their CIDR shown, 2 rows, centered fine vertically, but L2 network doesn't have the CIDR, so single row, and not centered vertically)

**Comment by andrijapanicsb** [comment]
same for other fields - if possible:

![image](https://user-images.githubusercontent.com/45762285/93624219-50189400-f9e0-11ea-883f-fe9f5649d66f.png)

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland can you review/test and close against master?

**Comment by DaanHoogland** [comment]
@rhtyd (cc @andrijapanicsb ) i have not found this issue but from the description it isn't clear where (via what path) to look, so bouncing a bit to @andrijapanicsb

**Comment by DaanHoogland** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/2486961/93803535-522f5c80-fc45-11ea-8cba-a13114d91f91.png">
