### ISSUE TITLE
[FEATURE] Add CIDR next to the network name, for deploy-as-is templates

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#725]
For normal templates, when user chooses some networks to attach the VM to, there is CIDR of that network shown to help user.

With deploy-as-is templates, CIDR is not shown - let's add it when possible - to look something like this:

![image](https://user-images.githubusercontent.com/45762285/93626206-64aa5b80-f9e3-11ea-8b03-757d0fc5d21a.png)

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland can you test against master and close this, thnx

**Comment by DaanHoogland** [comment]
works: <img width="800" alt="image" src="https://user-images.githubusercontent.com/2486961/93862235-01aa1480-fcc2-11ea-83e8-8fa3a4b1437e.png">
