### ISSUE TITLE
[BUG] again, pages refreshed when they should not be

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#726]
Deploying a VM, submitted the job in UI, then opened the " new VM" wizard again - and when the PREVIOUS job completed (same happens if deleting a VM previously) - a weird refresh API is sent, and in the middle of the deploy vm form/dialouge where I was, I get kicked out and errors are shown:

![image](https://user-images.githubusercontent.com/45762285/93626945-80fac800-f9e4-11ea-9765-f5197ce5467f.png)

**Comment by rhtyd** [comment]
@andrijapanicsb please review/test and close against master

**Comment by DaanHoogland** [comment]
still failing, but might be due to crossing builds. I will rebuild an env tonight and try again tomorrow:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/2486961/93766678-0e256300-fc17-11ea-949c-0b0e3c1013e9.png">

**Comment by DaanHoogland** [comment]
newer version tested; both multiple vm creation as deleting a VM and then opening another delete dialog while an expunge completes, work as expected
