### ISSUE TITLE
[BUG] Volume destroy form NOT closed after submitting the job

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#731]
![image](https://user-images.githubusercontent.com/45762285/93742925-4153fc00-fbef-11ea-9e4a-669dc58e8705.png)

If I hit the OK button AGAIN, it will delete the FIRST volume listed in the list of volumes!!!

**Comment by rhtyd** [comment]
Seems like a regression @davidjumani can you check, was this from your modal close PR?

**Comment by andrijapanicsb** [comment]
same/similar happens, when volume is already deleted, and you press the delete button in order to EXPUNGE it - please make sure to test that as well. thx

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland can you review/test against master and close this

**Comment by andrijapanicsb** [comment]
This is/was happening also on delete network form etc...
Will try to test on fresh mater now

**Comment by DaanHoogland** [comment]
confirmed in latest
