### ISSUE TITLE
[BUG] Show ISO info/name, instead of just UUID

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#736]
ISO, that is attached to the VM

![image](https://user-images.githubusercontent.com/45762285/93892918-5911aa00-fced-11ea-95da-19a9a51b8a63.png)

**Comment by rhtyd** [comment]
I'm seeing both name and uuid, what is the issue @andrijapanicsb ?

**Comment by rhtyd** [comment]
I don't see any bug here, we're showing the ISO name (clickable too) and the ISO ID:
![Screenshot from 2020-09-23 17-58-59](https://user-images.githubusercontent.com/95203/94012467-7a929480-fdc6-11ea-991d-f5445b70d91d.png)

**Comment by rhtyd** [comment]
@andrijapanicsb I'm closing this as indeed we show the ISO name, if there's anything else you'd like to add pl reopen.

**Comment by andrijapanicsb** [comment]
Um... 🤦
