### ISSUE TITLE
[BUG] user with special role is denied log on without sensible message

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#740]
**Describe the bug**
After creating a new role with all permissions except for updateZone, and creating an account with that role, the user can not log on.

**To Reproduce**

1. Log in as Admin
2. Create a role of type admin
3. Create an account with this role
4. log in with the user from the new role
5. See error

**Expected behavior**
Either the login succeeds, or a meaningful message is displayed.

**Screenshots**
<img width="1123" alt="Screenshot 2020-09-23 at 10 21 06" src="https://user-images.githubusercontent.com/2486961/93988568-2ae1a800-fd89-11ea-90a0-20d1da10759d.png">

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/2486961/93988716-582e5600-fd89-11ea-8d4a-111490975717.png">

<img width="1000" alt="Screenshot 2020-09-23 at 10 29 12" src="https://user-images.githubusercontent.com/2486961/93988590-3208b600-fd89-11ea-9b8c-1b818ac271c2.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser firefox 80.0
 - Version 1.0.0-GA preview

**Additional context**
In the old UI no message is displayed at all, no apparent change in the UI is visible after pressing the "login" button.

**Comment by davidjumani** [comment]
@DaanHoogland That's because the user doesn't have access to `listApis` and `listCapabilities` APIs which are needed by primate

**Comment by DaanHoogland** [comment]
@davidjumani why would he not have access to those APIs?

**Comment by DaanHoogland** [comment]
btw, it seems this is not primate specific. lopg on fails on the old UI as well. It seems to be a genuine bug though. even when mentioned API are added as allow and * is added as allow, login fails.

**Comment by rhtyd** [comment]
@davidjumani @utchoang maybe if it fails we should log a sensible message that unable to discover features as listApis (or any other essential APIs we expect) is not allowed?

**Comment by rhtyd** [comment]
There are a bunch of APIs we call on login that "we" expect to work but don't have an error handler - https://github.com/apache/cloudstack-primate/blob/master/src/store/modules/user.js#L148

**Comment by davidjumani** [comment]
@rhtyd There's also the issue of the user being logged out if there's a call being made to a blacklisted API rather than being told that the API doesn't exist or denied. Will be working on all of them when I raise a PR agianst this

**Comment by rhtyd** [comment]
@DaanHoogland usually we require that the following APIs are enabled for Primate to atleast show something (what you're hitting, you'll hit on old UI as well): listApis, listUsers, listZones, listCapabilities (I'm not sure about listLdapConfigurations or cloudianIsEnabled).
