### ISSUE TITLE
[BUG] when deleting a domain with a subdomain, it remains visible

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#741]
**Describe the bug**
when deleting a domain with cleanup any child is expected to be gone (subdomains or other things like accounts)

**To Reproduce**

1. Log in as an Admin
1. Go to 'Domains'
1. Click on '+ Add Domain'
1. add a name (like "sub")
1. submit the form
1. select the new domain
1. Click on '+ Add Domain'
1. add a name (like "leaf")
1. submit the form
1. select the parent domain ("sub")
1. delete the domain and select "Cleanup" in the delete dialog

now the "leaf" will be vissible as a child of ROOT.

**Expected behavior**
"sub" and all below it should be gone.

**Screenshots**

<img width="709" alt="Screenshot 2020-09-23 at 12 24 08" src="https://user-images.githubusercontent.com/2486961/94001446-d0504800-fd98-11ea-896c-d64df455f423.png">

<img width="128" alt="Screenshot 2020-09-23 at 12 24 32" src="https://user-images.githubusercontent.com/2486961/94001525-e52cdb80-fd98-11ea-9ea4-014c6f8f5342.png">

**Additional context**
Note that navigating away and back does clear the domain from view, making this a minor issue.

**Comment by rhtyd** [comment]
I think we've fixed it, perhaps a regression. @utchoang can you review and fix it? Thanks

**Comment by utchoang** [comment]
@DaanHoogland @rhtyd cc @svenvogel 
I tried with http://primate-qa.cloudstack.cloud:8080/client/master/ but I can't reproduce the error. When I removed the `sub` domain then both` sub` & `leaf` were removed from the tree domain. Can you retest and tell me where the error came from?
![image](https://user-images.githubusercontent.com/13766648/94109524-4de48880-fe6b-11ea-9e05-1e887c83528d.png)
![image](https://user-images.githubusercontent.com/13766648/94109568-62288580-fe6b-11ea-8ae2-b1e4e36871f6.png)

**Comment by DaanHoogland** [comment]
@utchoang i have just tested this on last nightly build and it is still there. As stated in my "additional Context" there is an easy workaround and selecting the "leaf" will still display the parent. I will give it another go with another parent than ROOT.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/2486961/94117968-2da5d100-fe4d-11ea-83eb-de754432189b.png">

**Comment by DaanHoogland** [comment]
@utchoang I noticed something related: when deleting a domain without cleanup, it fails but does remove the domain and its childeren from the tree.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/2486961/94119629-765e8980-fe4f-11ea-96a0-85c4f2e0e95c.png">

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/2486961/94119694-8b3b1d00-fe4f-11ea-9718-9cfdaa0f2a3a.png">

I think this ups the priority on this issue a bit

Note that this is firefox on macos, that might be relevant.
