### ISSUE TITLE
[FEATURE] domain admin should have "User" as default account type when adding an account

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#746]
**Is your feature request related to a problem? Please describe.**
As a Domain Admin my ussual account type to add is "User" so I want this to be the default choice.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2486961/94120237-31872280-fe50-11ea-95a5-eb66852a3559.png">

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland please test and close against latest master

**Comment by DaanHoogland** [comment]
works on master
