### ISSUE TITLE
[BUG]  Getting 404 after deleting a VM

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#753]
VM deletion in progress:

![image](https://user-images.githubusercontent.com/45762285/94292071-c1b28e00-ff5c-11ea-8162-06bed43e3ee0.png)

After it's done, instead of going back to the list of instances, I get 404:

![image](https://user-images.githubusercontent.com/45762285/94292127-d55df480-ff5c-11ea-8e74-057177852431.png)

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland please test and close against latest master

**Comment by DaanHoogland** [comment]
stillhappens in latest:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/2486961/94432692-6b7d5f00-0197-11eb-8e88-62693f967f29.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/2486961/94432735-7a641180-0197-11eb-98be-287084aef28d.png">

**Comment by rhtyd** [comment]
@utchoang can you check this?

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close

**Comment by andrijapanicsb** [comment]
LGTM, thx
