### ISSUE TITLE
[BUG] Network Offering form security options are not saved correctly

### ISSUE THREAD

**Issue by alexandremattioli** [apache/cloudstack-primate#757]
**Describe the bug**
When creating a network offering with "promiscuous mode", "forged transmits" and "MAC address changes" on Primate it sets the values on the "network_offering_details" table as "accept" when the correct value that should be set is "true".

**To Reproduce**

1. Log in as an Admin
2. Go to 'network offerings'
3. Create a network offering with the 3 security settings enabled
4. On the "network_offering_details" they will have the value "accept".

**Expected behavior**
Value for security settings should be "true"

**Screenshots**

![Promisc](https://user-images.githubusercontent.com/60507727/94457090-06803400-01ac-11eb-9405-54f53507f7fb.JPG)

**Comment by rhtyd** [comment]
@shwstppr can you check this? In the handler should the option accept be saved as true?
