### ISSUE TITLE
[BUG]  Primate GuestNetwork Not able to Add IP Range

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack-primate#758]
**Describe the bug**
in primate interface , zone, physical internface, guest network, not able to add ip range, a part from initially created.  Also not able to see the start and end ip that initially created. 

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Infrastructure'
3. Click on '.Zone, and Physical Interface, Select GuestNetwork'
4. Not able to see the IPRange that created , or  Not able to add New Range (start and end IP)

**Expected behavior**
Able to see the IP range linked to GuestNetwork, and Able to add new range.
In old interface , it able to see .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CENTOS, 7, Primate
 - Browser Chrome

**Additional context**

**Comment by rhtyd** [comment]
@utchoang can you check this?
