### ISSUE TITLE
[BUG]  VM Instance, Change IP , Do not have DropDown List to Select 

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack-primate#759]
**Describe the bug**
Primate Interface, VM instance , Change IP Address,  only Manual key in IP address to change. It shall be list down IP to select to change , Old Interface has this. 

**To Reproduce**
1. Log in as a User or an Admin
2. Go to 'Instance, Select the VM'
3. Click on 'NIC' and Click '-'
4. Click Change IP icon, and it will pop up new window for key in IP
5. The IP to key in is manual keyin, it shall be select from drop down list select ip avaible to change

**Expected behavior**
It shall list out the available IP to change, instead of Admin Key in whatever they want .
In old interface, this is dropdown selection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 

**Additional context**

**Comment by rhtyd** [comment]
@utchoang can you check this?
