### ISSUE TITLE
[FEATURE]  Able to reserve an IP and not to be assign to VM

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack-primate#760]
**Is your feature request related to a problem? Please describe.**
Some IP address that assigned to VM, but that IP that having issue of Spamming, Blacklist etc, and after the VM being changed to new IP, the issued-ip will return to the IP Pool and future re-assign to other VM.
The system not able to reserve the problem ip which temporary do not re-assign to as it the spamming issue took time to resolve, some time it may took few months for resolving. 

**Describe the solution you'd like**
Allow mark IP as Reserve, and reserved ip shall not be auto-reassign to VM 

**Describe alternatives you've considered**

**Additional context**

**Comment by rhtyd** [comment]
@utchoang can you check this?

**Comment by rhtyd** [comment]
@hstan77 you can do that by acquiring the public IP in a guest network; and then not use it (to assign/snat to a VM or otherwise). Also please raise backend features at https://github.com/apache/cloudstack, this Git repository is only for tracking frontend features only. Thanks.
