### ISSUE TITLE
[BUG] Additional curly bracket on the status message when creating a new disk offering

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#765]
**Describe the bug**
 There is an additional curly bracket on the status message when creating a new disk offering

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Service offerings - Disk offerings' and click on 'Add disk offering'
3. Add some kind of disk offering and look at the status message that the offering has been created successfully - there is one additional curly bracket at the end of the text.

**Expected behavior**
There should be no curly bracket at the end of the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/94561137-4870af00-026c-11eb-9813-8a855b4ff80f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Verified, PR fixed it @vladimirpetrov please re-test against latest master. Thanks for reporting.

**Comment by vladimirpetrov** [comment]
LGTM
