### ISSUE TITLE
[BUG] Not able to configure Load Balancer rules in isolated network

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack-primate#766]
**Describe the bug**
I created an isolated network and I dont see any option to create Load balancer rules.
Only source NAT is enabled in that network

The issue mentioned in https://github.com/apache/cloudstack-primate/issues/678 states that it should be hidden if PF or static nat is enabled. In my case none of them are enabled and still I dont see any options.

This is blocking testing the HAproxy Loadbalancer customization.

**To Reproduce**

1. Log in as a User or an Admin
2. Go to Networks
3. Click on Add networks and create a new Isolated network
4. Select the isolated network created above. Click on public IP address and select the IP address on which Source NAT is enabled
5. I dont see any tab for Load balancing

**Expected behavior**
I should see a tab for load balancing

**Screenshots**
New ui

![Screenshot 2020-09-29 at 15 19 00](https://user-images.githubusercontent.com/10645273/94563511-1b6dcd80-0267-11eb-80f8-aad53ac7eb4f.png)

I do see load balancing option in old ui

![Screenshot 2020-09-29 at 15 19 20](https://user-images.githubusercontent.com/10645273/94563554-27f22600-0267-11eb-946d-ff4d56ad01c7.png)

![Screenshot 2020-09-29 at 15 38 30](https://user-images.githubusercontent.com/10645273/94565708-d4cda280-0269-11eb-9997-56709b31ed41.png)

**Comment by ravening** [comment]
I do see it for VPC though

![Screenshot 2020-09-29 at 15 40 07](https://user-images.githubusercontent.com/10645273/94565901-0fcfd600-026a-11eb-9c18-5fa9780cb4a6.png)

**Comment by ravening** [comment]
cc @utchoang @andrijapanicsb

**Comment by ravening** [comment]
Load balancing rules cant be configured on Source NAT IP in VPC in legacy UI but it can be confgiured in primate which is a bug

**Comment by rhtyd** [comment]
@ravening are you working on a fix, or want us to triage?

**Comment by ravening** [comment]
@rhtyd yes working on a fix. will create pr soon
