### ISSUE TITLE
[BUG] Wrong total number of items when migrating a VM

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#773]
**Describe the bug**
When migrating a VM, the total number of items shows all of them, but you can only choose from the suitable targets which is much less - this makes the dialog confusing.

**To Reproduce**

1. Log in as Admin
2. Prepare several clusters and hosts with different storage types.
3. Go to 'Compute > Instances' and choose an instance.
4. Click on 'Migrate' button

**Expected behavior**
The total number of items must be calculated only for the suitable targets, not all.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/94656998-8079ff80-0309-11eb-9425-d7c8c8d4f6be.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None.

**Comment by utchoang** [comment]
@rhtyd @davidjumani cc @svenvogel I think this comes from the result `count` of API was wrong?

**Comment by davidjumani** [comment]
That's right @utchoang Will look into creating a backend fix for this

**Comment by rhtyd** [comment]
@vladimirpetrov can you test latest master and close this? thnx

**Comment by vladimirpetrov** [comment]
Fix confirmed.
