### ISSUE TITLE
[BUG] boot into setup dissapeared

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#785]
**Describe the bug**
A boot into setup check is expected in the instance action start and reboot as are shown in the vm wizard:

<img width="795" alt="Screenshot 2020-10-02 at 15 27 39" src="https://user-images.githubusercontent.com/2486961/94930482-c16b4300-04c6-11eb-897f-795a7a5c596f.png">

<img width="509" alt="Screenshot 2020-10-02 at 15 46 40" src="https://user-images.githubusercontent.com/2486961/94930488-c4feca00-04c6-11eb-8296-f4da52192405.png">

<img width="513" alt="Screenshot 2020-10-02 at 15 47 04" src="https://user-images.githubusercontent.com/2486961/94930499-c7f9ba80-04c6-11eb-8aee-d5639fcff6b7.png">

**To Reproduce**

1. Log in as a User or an Admin
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by DaanHoogland** [comment]
@davidjumani @shwstppr looks like a regression since the initial merge. I noticed during taking screenshots for an intro doc. do you have a quick assesment? cc @rhtyd

**Comment by davidjumani** [comment]
@DaanHoogland It shows up only if the vm's hypervisor is VMware
![Screenshot from 2020-10-05 11-57-32](https://user-images.githubusercontent.com/8244774/95046603-1d6ddb80-0702-11eb-8050-411ca06e8304.png)
![Screenshot from 2020-10-05 11-57-43](https://user-images.githubusercontent.com/8244774/95046607-1e9f0880-0702-11eb-8d72-a8433ce080cc.png)

**Comment by DaanHoogland** [comment]
sorry @davidjumani I thought I knew my work. I'll double check.

**Comment by DaanHoogland** [comment]
this seems to be a version mixup, closing for now... will double check along the way in future activities
