### ISSUE TITLE
[BUG] Storage tags displayed multiple

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#786]
**Describe the bug**
Tags are duplicated when adding a pool. All the records point to the same tag but they appear as many times it's been used per storage pool. 

**To Reproduce**

1. Create a storage tag
2. Tag a few pools with the tag
3. Observe the tag will appear multiple times as the pools tagged

**Expected behavior**
Tags should appear once 

**Screenshots**
![image-20201004-184303](https://user-images.githubusercontent.com/13551960/95052277-52c0fc00-06f7-11eb-848c-6c831b51d91a.png)
![Screenshot 2020-10-01 at 10 49 06](https://user-images.githubusercontent.com/13551960/95052279-53599280-06f7-11eb-8a91-532869d01892.png)

**Comment by rhtyd** [comment]
@borisstoyanov can you test this and close? Thanks.

**Comment by borisstoyanov** [comment]
LGTM
![Screen Shot 2020-10-06 at 10 00 13](https://user-images.githubusercontent.com/13551960/95169011-d98add00-07ba-11eb-8286-868df72b1a98.png)
