### ISSUE TITLE
[BUG] Missing confirmation/notification after removal of primary storage

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#791]
**Describe the bug**
When a primary storage is deleted, there is no any kind of confirmation and a message in the notification list - just redirect back to the list of the storages.

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Infrastructure > Primary Storage' and click on a storage.
3. Now enable maintenance mode and remove the storage.

**Expected behavior**
There must be a message, confirming that the operation has been completed successfully and a notification should be added in the notifications area.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment]
`deleteStoragePool` is not a async API so there is no polling and therefore there is no notification on the top-right side (notifications). However a message is shown that needs checking - @davidjumani

**Comment by rhtyd** [comment]
@vladimirpetrov I see notification message on middle-top but not on the notifications area (which is expected for any non-async API)
![Screenshot from 2020-10-07 14-41-10](https://user-images.githubusercontent.com/95203/95311423-38c81a80-08ab-11eb-9590-cbf95ec6453e.png)

**Comment by rhtyd** [comment]
@vladimirpetrov can you test and close this? As explained we're not supporting notifications for non-async APIs but just the messages as shown above.

**Comment by vladimirpetrov** [comment]
Ok, there is a brief notification indeed - and it's not a big deal that the notification is missing, closing the issue.
