### ISSUE TITLE
[BUG] VLXAN needs be removed as isolation method from non-Guest traffic type

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#794]
seems that VxLAN is uncodnitionally displayed, even when no network trafic TYPE is selected

AFAIK, VxLAN is only supported as an isolation method for Guest traffic -not for any other kind of traffic

![image](https://user-images.githubusercontent.com/45762285/95438084-1a6b2900-0956-11eb-8124-29e5809e36c2.png)

**Comment by rhtyd** [comment]
The API doc says for addTrafficType API:
```
isolationmethod          string   Used if physical network has multiple iso
                                  lation types and traffic type is public.
                                   Choose which isolation method. Valid op
                                  tions currently 'vlan' or 'vxlan', defau
                                  lts to 'vlan'.

```
So both options VLAN and VXLAN are valid, please close the issue @andrijapanicsb

**Comment by andrijapanicsb** [comment]
alright... that is news to me (what about mgmt/storage, etc) - let's leave it for now. we can always revise later.

**Comment by rhtyd** [comment]
Thanks closing on your remark.
