### ISSUE TITLE
UI missing - Cannot select option private registry for kubernetes cluster.

### ISSUE THREAD

**Issue by tungntvn23** [apache/cloudstack-primate#801]
- Cannot select optional private registry when create kubernetes cluster.

+ New UI
![image](https://user-images.githubusercontent.com/46994732/95721211-75758680-0c9c-11eb-9c7d-9cba214c5512.png)

+ Old UI
![image](https://user-images.githubusercontent.com/46994732/95721270-8aeab080-0c9c-11eb-97df-73daec60fce2.png)

**Comment by rhtyd** [comment]
Was the private registry feature implemented in backend cc @davidjumani @shwstppr @Pearl1594 ?

**Comment by rhtyd** [comment]
Please triage and then fix for 1.0 or move to 1.1 if the backend does not support private registry feature.

**Comment by rhtyd** [comment]
Fixed in #802 

@tungntvn23 can you test latest master and re-open if you're able to reproduce it again? Thanks.
