### ISSUE TITLE
[FEATURE] Clicking Menu group name - to choose the first menu item

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#805]
For some time now, while testing and having to click around frequently, I've been very irritated by having to click on Compute, then on Instances (in order to reach Instances as the first menu item), as this means clicking 2 times in order to get to the first item in the menu group - this is not user/mouse friendly :)

Can we somehow ensure old-UI-like behaviour -  that when a menu group (i.e 'Compute' or 'Images') is clicked, that we automatically select/show the first menu item (i.e. 'Instances', or 'Templates' in this example).

Hopefully it makes sense. thx

**Comment by utchoang** [comment]
@rhtyd There's one problem: This will take away a collapsed menu context. What do you think?

**Comment by rhtyd** [comment]
@andrijapanicsb that's just a matter of getting used to, otherwise we won't be able to have collapsable sub-menus

**Comment by andrijapanicsb** [comment]
Copy that. Is it possible (not sure how it would look tbh - to have some kind of floating menus - or self-exapnding on hover ??? (floating menu = same as in the mobile/tablet view, i.e. on smaller resolutions when you hover over Compute, there is menu shown for Instances and other things)

Self-expanding menu on hover would be nice, if possible...
