### ISSUE TITLE
[IMPROVEMENT] listing backups from backup and recovery

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack-primate#806]
Hi @rhtyd 

is there a listing of the backups from the backup and recovery framework like the old ui or do we forget this to implement?

old UI
![image](https://user-images.githubusercontent.com/5433844/96099013-10f03c80-0ed3-11eb-88e0-2927f3d177ce.png)

ne UI?

Cheers

Sven

**Comment by utchoang** [comment]
@rhtyd We already have backup offerings. Please check again new UI.
![image](https://user-images.githubusercontent.com/13766648/96101186-67737000-0eff-11eb-8b7a-0173cca7782b.png)
![image](https://user-images.githubusercontent.com/13766648/96101205-6b06f700-0eff-11eb-8f06-fc9757df670c.png)

**Comment by rhtyd** [comment]
@svenvogel I think we don't show it in Primate unless the feature is enabled via its global setting. Can you check and close this?

**Comment by rhtyd** [comment]
@svenvogel I checked this will show up only if `backup.framework.enabled` global setting is enabled and on primate-qa env I see it does show up:
![Screenshot from 2020-10-28 15-36-18](https://user-images.githubusercontent.com/95203/97422161-714f9700-1933-11eb-8fa1-3141b4adf3e7.png)

**Comment by rhtyd** [comment]
Closing this as it turned out to be a non-issue
