### ISSUE TITLE
[IIMPROVEMENT] create snapshot from virtual machine with managed storage

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack-primate#807]
Hi @rhtyd @utchoang 

Storage Snapshot functionality.

in the old ui we have here a storage snapshot functionality. 
![image](https://user-images.githubusercontent.com/5433844/96099408-7f34ff00-0ed3-11eb-9f3d-eefe382ab31f.png)

we should add them in the new ui too like the old ui for the user of managed storage
![image](https://user-images.githubusercontent.com/5433844/96099596-b4415180-0ed3-11eb-9000-4d91ac0f1d4b.png)

@utchoang can you create a PR please?

Cheers

Sven

**Comment by utchoang** [comment]
@svenvogel In the new UI, we already have the take VM snapshot button. Can you check it again.
![image](https://user-images.githubusercontent.com/13766648/96100858-0481d900-0eff-11eb-9601-fb64db934570.png)
![image](https://user-images.githubusercontent.com/13766648/96100872-09468d00-0eff-11eb-87d2-f8ac589344f3.png)
