### ISSUE TITLE
[BUG] Minor: the "Scheduled" type of events have ever-spinning blue circle icon next to it

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#814]
![image](https://user-images.githubusercontent.com/45762285/96851492-5cb55f80-1458-11eb-903d-e990c52e1c6a.png)

those blue are like the one when VM is i.e. being stopped (stopping) or started (starting) -those event's are one time "scheduled", if we can show some static image there (blue, other color, whatever)

**Comment by davidjumani** [comment]
@andrijapanicsb That's because the page doesn't periodically refresh / reload the data. It'll change when the user hits the refresh button or naviages back to this page

**Comment by andrijapanicsb** [comment]
no it's not @davidjumani - these are all OLD (a long time ago finished) actions - we simply use those buttons (from what I can tell)

**Comment by utchoang** [comment]
@andrijapanicsb As I understand, for each different type of schedule there will be a different color state, right?

**Comment by andrijapanicsb** [comment]
@utchoang , TBH, I don't know - but I don't thing a spinning circle(s), which visually indicates an ONGOING action, should be used to show an event that happened in past, and is thus finihed.
Again - this is minor, but nice to polish if possible.
