### ISSUE TITLE
[BUG] NOT WORKING

### ISSUE THREAD

**Issue by RRadziejewski** [apache/cloudstack-primate#815]
Following the installation guide on centos7 after installing
yum install cloudstack-primate

I should be able to access management ui which is not happenning how to debug this what http server is that using by default ?

Lack of informations in install guide.

**Comment by DaanHoogland** [comment]
@RRadziejewski i think you need to add some information like log output and a title that describes you issue better than "NOT WORKING". this is not inviting people to help you.

**Comment by RRadziejewski** [comment]
Problem solved sorry for incovenience and thank you for the answer.

czw., 22.10.2020, 13:54 użytkownik dahn <notifications@github.com> napisał:
