### ISSUE TITLE
[BUG]  In Private Gateway - show ACL NAME instead of the UUID

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#824]
Not really user-friendly - let's show NAME of the ACL instead (just like in other places):

![image](https://user-images.githubusercontent.com/45762285/97170702-6c041800-178c-11eb-81cc-5fc81b6c0c96.png)

**Comment by utchoang** [comment]
@andrijapanicsb @rhtyd @davidjumani cc @svenvogel
In the API description, I only see 2 fields aclid and acltype but not aclname.
So is there any other way to get aclname?

**Comment by davidjumani** [comment]
@utchoang It is present in the response, just not in the build on the qa server. Feel free to add `aclname` to the list of fileds in the deails view
