### ISSUE TITLE
[BUG] Clicking on EDIT button for global configuration doesn't move cursor to the field

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#825]
In old UI, when you click on the pencil/edit button for a global setting, the cursor automatically goes to the input filed, so you can use edit the value.

In Primate, after clicking on the pencil/edit button, it is required to click inside the field first - this should be fixed, please.

![image](https://user-images.githubusercontent.com/45762285/97191978-b9da4980-17a7-11eb-93e8-996c98b6d0c6.png)

**Comment by utchoang** [comment]
@andrijapanicsb @rhtyd @davidjumani cc @svenvogel 
In the API description, I only see 2 fields `aclid` and `acltype` but not `aclname`.
So is there any other way to get `aclname`?
