### ISSUE TITLE
[BUG] public network端口转发设置问题

### ISSUE THREAD

**Issue by feizhoulaobo** [apache/cloudstack-primate#827]
端口转发设置选择主机没办法跳转到下一页。

**Comment by feizhoulaobo** [comment]
【BUG】Problem with public Network port forwarding Settings
#
The port forwarding Settings selection host cannot jump to the next page.

**Comment by davidjumani** [comment]
@feizhoulaobo could you provide a screenshot of the problem?

**Comment by rhtyd** [comment]
@feizhoulaobo can you share steps on reproducing the problem, and details of your environment (hypervisor, version of CloudStack etc).

**Comment by rhtyd** [comment]
ping @feizhoulaobo can you update steps on reproducing the problem?

**Comment by rhtyd** [comment]
@feizhoulaobo ping any update, sorry we don't know what the problem is

**Comment by weizhouapache** [comment]
it looks like not a bug
on old UI, if click "Add VM" when create port forwarding rule, it will list the first 20 vms.
when scroll down to the bottom of the list, it will list the next 20 vms on UI.

**Comment by rhtyd** [comment]
@feizhoulaobo kindly test latest release (master or with 4.15.0.0) and if you can reproduce please raise bug on https://github.com/apache/cloudstack/issues
