### ISSUE TITLE
[BUG] Change to POST (instead of GET) when uploading account certificate

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#837]
Account certificates (whatever they are, and for whatever they are used…)
-	Old UI uses POST to post data, and I assume this is a valid way since the data can be huge (certificate length, key length, chain length etc…)
-	Primate sends it via simple GET – I’m questioning if this is wrong and should be fixed as with long text it will cause HTTP error with too long request etc.

![image](https://user-images.githubusercontent.com/45762285/97328032-e0ff4c80-1875-11eb-8439-e8057fb56600.png)

![image](https://user-images.githubusercontent.com/45762285/97328100-f4121c80-1875-11eb-8a7b-873d7c082117.png)

**Comment by rhtyd** [comment]
The upload cert feature in Accounts -> SSL cert tab is not generally used by CloudStack LB (maybe netscaler etc.). If it's simple fix go ahead @utchoang or @davidjumani  - otherwise we can push it to 1.1

**Comment by davidjumani** [comment]
Doesn't seem too hard. I'll look into it

**Comment by rhtyd** [comment]
Moving this to 1.1, not generally used or that important; get request seems to work OK.
