### ISSUE TITLE
[BUG] VMware local template requires OS type

### ISSUE THREAD

**Issue by alexandru-bagu** [apache/cloudstack-primate#840]
When trying to upload a local VMware template you cannot choose ostypeid and you get an API error.
https://prnt.sc/v8iu6w

**Comment by alexandru-bagu** [comment]
#839

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/pull/839#issuecomment-717820827

cc @nvazquez @PaulAngus

**Comment by alexandru-bagu** [comment]
bug caused by incompatibility with cloudstack 4.14 api. vmware template configurations are handled by api in 4.15.
