### ISSUE TITLE
Question: Switch out from project view

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack-primate#843]
I was able to switch from the default view to project view by clicking on the button displayed next to the project name.
Now how do i switch back to regular view? I cant seem to find any button for it

@rhtyd @davidjumani @Pearl1594 @utchoang any help?

**Comment by Pearl1594** [comment]
@ravening In the project view, Goto the dashboard tab, and at the top of the screen you should see a dropdown menu by means of which you can switch back to the Default view:
![image](https://user-images.githubusercontent.com/10495417/98109301-58ab2800-1ec3-11eb-805d-831eb1a19e9b.png)

**Comment by ravening** [comment]
@Pearl1594 ah ok..got it thanks :) I also noticed that I need to click twice to get the drop down. is it the same case for you as well?

**Comment by Pearl1594** [comment]
It works fine for me @ravening

**Comment by ravening** [comment]
> It works fine for me @ravening

good. thanks for the help. closing the issue
