### ISSUE TITLE
[BUG] add ldap user button missing

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#847]
**Describe the bug**
when a ldap server has been configured, in the old UI a button for adding an ldap user in the account overview is shown.
![image](https://user-images.githubusercontent.com/2486961/98367127-0554e900-202d-11eb-8487-4a93edcbd218.png)

In primate this is not the case:
![image](https://user-images.githubusercontent.com/2486961/98367195-21588a80-202d-11eb-9fd1-7b9cd0f6e7e0.png)

**To Reproduce**

1. configure an ldap server according to http://docs.cloudstack.apache.org/en/latest/adminguide/accounts.html#using-an-ldap-server-for-user-authentication
1. login
1. go to accounts overview
1. considder adding an ldap user according to the oldest method; manual import

**Expected behavior**
a button is expected.

**Screenshots**
see description.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**
Note that this is very minor as manual import is not the preferred way to maintain ldap users.

**Comment by utchoang** [comment]
@DaanHoogland You can find the Add LDAP Account button at the next of the Add Account button (screenshot)
![image](https://user-images.githubusercontent.com/13766648/98488806-cd80b800-225d-11eb-8d89-cb61e38c3d4a.png)

**Comment by davidjumani** [comment]
@utchoang @rhtyd Would it be better to make it more explicit like the add account button ?

**Comment by utchoang** [comment]
@davidjumani @rhtyd Do you think it is good?
![image](https://user-images.githubusercontent.com/13766648/98506450-1a7c8280-228e-11eb-9c73-46d9be77f94c.png)

**Comment by davidjumani** [comment]
@DaanHoogland ^^

**Comment by DaanHoogland** [comment]
@utchoang @davidjumani , i am not partial on how it would be implemented as long as it is visible to an ignorant user looking for it. I remember some talk a while ago about making it an option after pressing the add account button. the above looks clear to the user at least.

**Comment by davidjumani** [comment]
@utchoang Please go ahead and raise a PR for the change. Thanks
