### ISSUE TITLE
Template Permission Action

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#85]
- [x]  Update template permissions (share with template/project etc)

![Screenshot from 2019-12-24 14-46-17](https://user-images.githubusercontent.com/95203/71405684-29e5e380-265c-11ea-8b58-459434cc0dbf.png)

**Comment by rhtyd** [comment]
@utchoang /cc @svenvogel could you pick this one up as the next task. Let me know if you've any question.

**Comment by rhtyd** [comment]
For example on how to add a custom action form, you can see: https://github.com/apache/cloudstack-primate/pull/69/files

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I got it, I'll send you any question if any

**Comment by rhtyd** [comment]
Are you working on this @utchoang? If not may I assign it to someone else?

**Comment by utchoang** [comment]
@rhtyd Yes, I am working this task.

**Comment by rhtyd** [comment]
Okay, I'll find another ticket to assign to a colleague.

**Comment by utchoang** [comment]
No, I am working this task https://github.com/apache/cloudstack-primate/issues/86

**Comment by rhtyd** [comment]
Okay @utchoang don't work on this task then, I'll assign it to a colleague.

**Comment by rhtyd** [comment]
Merged in #96
