### ISSUE TITLE
[BUG] DomainAdmin user has no Configure Limits tab in Project

### ISSUE THREAD

**Issue by sm97** [apache/cloudstack-primate#854]
RPM package version: cloudstack-primate-1.0.0-20201020.x86_64

**Describe the bug**
DomainAdmin role allows to update project resource limits by default but Primate hides Configure Limit tab in WEB UI.
Only SuperAdmin has such tab.

**Expected behavior**
It's expected that every role with updateResourceLimit permission can use Configure Limit tab for project.
Atleast legacy WebUI allows DomainAdmin to update project resource limits.

**Screenshots**
Affected account props:
![2020-11-09 15_46_30-Accounts - CloudStack](https://user-images.githubusercontent.com/9654317/98544827-9df59e00-22a5-11eb-9412-065b0398ea4f.png)

Screen view for admin account;
![2020-11-09 15_51_49-Projects - admin - CloudStack](https://user-images.githubusercontent.com/9654317/98544828-9f26cb00-22a5-11eb-9927-3d6c7dc2c4fc.png)

Screen view for DomainAdmin role account:
![2020-11-09 15_53_24-Projects - domainadmin - CloudStack](https://user-images.githubusercontent.com/9654317/98544831-9fbf6180-22a5-11eb-8c8e-cf48ced3205e.png)

**Comment by rhtyd** [comment]
@Pearl1594 @sm97 what was the behaviour in old ui?

**Comment by rhtyd** [comment]
oh wait I see Pearl raised a PR, have you confirmed it @Pearl1594 ?

**Comment by rhtyd** [comment]
Just reviewed and merged the PR. @sm97 please test latest master and re-open if you're not satisfied. Thanks.
