### ISSUE TITLE
[BUG] - rootdisk size not on Create Compute Offering screen

### ISSUE THREAD

**Issue by gsirett** [apache/cloudstack-primate#859]
**Describe the bug**
new feature https://github.com/apache/cloudstack/pull/4341 allows admins to set root disk size on service offering (and therefore prevents users from choosing it)
However, this is not appearing in primate UI

**To Reproduce**
Use buld that contains PR  4341
Use primate#
login as admin
Navigate Service offerigns>compute offerings> add new compute offering

**Expected behavior**
Expected to see option to specify root disk size
(note: as this is new functionality, it may make sense to make this an intelligent option. Admins should be made aware that there is a choice between allowing users to set root disk or them "hardcoding" it

**Additional context**

**Comment by Pearl1594** [comment]
@gsirett There seems to be a field available to specify the  root disk size
![image](https://user-images.githubusercontent.com/10495417/98797232-50f30280-2432-11eb-950a-5e50f6841f37.png)

**Comment by rhtyd** [comment]
@gsirett can you check @Pearl1594 's response and close the issue (or advise us) Thanks.

**Comment by gsirett** [comment]
Defiantly not in mine.

**Comment by gsirett** [comment]
Did not appear in my version (5.15.0.-SNAPSHOT) - I'm guessing ive probably got a slightly older build. Happy to close
