### ISSUE TITLE
Replace all screenshots, button/icons in CloudStack docs to use/refer the new UI

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#867]
Replace all screenshots, button/icons in CloudStack docs to use/refer the new UI. Possible milestone target CloudStack 4.16.

**Comment by Pearl1594** [comment]
@rhtyd wouldn't mind pitching in to work on handling the documentation changes for this

**Comment by rhtyd** [comment]
Closing this, tracked here now https://github.com/apache/cloudstack/issues/4592
