### ISSUE TITLE
[BUG] Hypervisor version shows ACS version instead

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#869]
**Describe the bug**
Hypervisor version shows cloudstack version

**To Reproduce**

1. Log in as an Admin
2. Go to Hosts

**Expected behavior**
Should show host hypervisor version 

**Screenshots**

![Screenshot 2020-11-23 at 9 40 02](https://user-images.githubusercontent.com/13551960/99938230-09dd0980-2d70-11eb-9bc7-5ad2dfd9b024.png)

**Comment by rhtyd** [comment]
@davidjumani can you check and raise a PR, probably a wrong key used there?

**Comment by rhtyd** [comment]
@borisstoyanov PR has been merged, pl test against latest master and close on confirmation. Thanks.

**Comment by borisstoyanov** [comment]
![Screenshot 2020-11-24 at 9 59 38](https://user-images.githubusercontent.com/13551960/100064930-d10a6680-2e3b-11eb-99f3-dc5452e60fe6.png)
LGTM
