### ISSUE TITLE
Recurring Volume Snapshot Custom Action Form

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#88]
Implement recurring volume snapshot custom action form with tags (snapshot policies - create/update/list/delete):

![Screenshot from 2019-12-24 14-54-14](https://user-images.githubusercontent.com/95203/71406125-52221200-265d-11ea-8443-b5dfbd0f4d6d.png)

Example on how to add a custom action form, you can see: https://github.com/apache/cloudstack-primate/pull/69/files

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel tagged for next tasks to consider. Thanks.

**Comment by rhtyd** [comment]
Ping @utchoang - you may pick this one. cc @svenvogel

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel  OK. I'll working with this task. Thank you.

**Comment by rhtyd** [comment]
PR added, closing this.
