### ISSUE TITLE
[BUG] When editing physical network traffic labels - existing labels are not shown

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#882]
![image](https://user-images.githubusercontent.com/45762285/100772075-735bb880-33ff-11eb-976a-8b6816b94aa3.png)

When you choose a kind of traffic - the existing labels should be shown, as in old UI (and it is a common sense, IMO to show existing values, and not just empty fields)

Old UI below:

![image](https://user-images.githubusercontent.com/45762285/100772339-bddd3500-33ff-11eb-807a-3dd168c8df11.png)

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close against latest

**Comment by andrijapanicsb** [comment]
Tested, LGTM - thx.
