### ISSUE TITLE
Question - How to create primary storage with SharedMountPoint

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack-primate#888]
Hi all,

I'm trying to create primary storage with SharedMountPoint but the command fails because "server" has to be provided (but there isn't such field)

![image](https://user-images.githubusercontent.com/51903378/101173091-b78ec900-364a-11eb-8031-509da319bab0.png)

I've tried also with DefaultPrimary as a provider

**Comment by rhtyd** [comment]
We've merged a PR that addresses this. @slavkap can you test the latest master and close the issue? Thanks.

**Comment by slavkap** [comment]
thanks all, it works! I'm closing the issue
