### ISSUE TITLE
[BUG] OS type combo box is not reponding

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#889]
**Describe the bug**
When registering a template, after going through the motion up to selecting the os type, during selction of the template os nothing happens.
typing a partial name does not give a preselection,
clicking a name does not select,
typing a name and entering or pressing tab does not close the tab,
pressing shift-tab does not go back,
trying to check any of the bottom checkboxes does not toggle the UI for those checkboxes,
pressing cancel does not close the dialog.

**To Reproduce**

1. in a blank env with only a single isolated network defined
1. go to templates
1. press "+ Register Template from URL"
1. go through like described in the description

**Expected behavior**
a pre-selection according to entered text.
a selection by enter according to the current highlighted.
a selection according to a entry by mouse click.

**Screenshots**
<img width="664" alt="Screenshot 2020-12-04 at 17 03 58" src="https://user-images.githubusercontent.com/2486961/101186566-8c5ca780-3653-11eb-98e0-3a5251d4261a.png">

<img width="638" alt="Screenshot 2020-12-04 at 17 04 18" src="https://user-images.githubusercontent.com/2486961/101186600-954d7900-3653-11eb-9325-3947e3559a2b.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser FF
 - Version 83.0

**Additional context**

**Comment by rhtyd** [comment]
A PR was merge @DaanHoogland can you test and close this against latest master? Thanks.

**Comment by DaanHoogland** [comment]
sorry for the late confirmation, checked on nightly build :+1:
