### ISSUE TITLE
[BUG] Wrong info shown for "Network Rate"  label in Compute Offering

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack-primate#904]
**Describe the bug**

The info/tool tip displayed for "Network Rate" in Add Compute Offering is incorrect

**To Reproduce**

1. Log in as an Admin
2. Go to 'Service Offerings -> Compute Offerings'
3. Click on 'Add Compute Offering'
4. Scroll down to 'Network Rate' text box
5. Check the info displayed "_provisioning type used to create volumes. Valid values are thin, sparse, fat._" at the 'Network Rate' label, which is incorrect

**Expected behavior**
The info should indicate that the text field is to input the network rate.

**Screenshots**

<img width="517" alt="WrongInfoInAddComputeOffering" src="https://user-images.githubusercontent.com/12028987/102862558-48411380-4457-11eb-87c8-9cbf0e7b82d8.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 87.0.4280.88

**Additional context**

**Comment by rhtyd** [comment]
@sureshanaparti can you test latest master and close, Pearl fixed the issue.

**Comment by sureshanaparti** [comment]
Verified.

<img width="491" alt="ComputeOffering_NetworkRate_Info_Verified" src="https://user-images.githubusercontent.com/12028987/103511279-bd1b4100-4e8c-11eb-9070-e0576b079012.png">
