### ISSUE TITLE
[BUG] Migration of a VM (local storage) stuck on UI

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack-primate#906]
**Describe the bug**
When migrating a VM that is running on local storage the UI hangs on the VM migration pop-up; additionally, it is presented an error on UI and an event `Error while migrating VM`is created.

When closing the migration tab and refreshing the instance page then it is possible to see that the VM was correctly migrated.

**To Reproduce**

1. Log in as Admin
2. Migrate  a VM
3. See error message thrown at UI
4. VM's migration tab hangs while waiting for completing migration (which has already completed)
5. Close migration pop-up and refresh VM page
6. Assert that VM was correctly migrated, despite UI saing otherwise at first

**Screenshots**
Example of the VM migration pop-up that stays waiting for migration:

![image](https://user-images.githubusercontent.com/5025148/103284251-7b385980-49b9-11eb-98dc-d03522b53181.png)

**Comment by shwstppr** [comment]
@GabrielBrascher not completely sure but this PR, https://github.com/apache/cloudstack-primate/pull/789, might solve the issue

**Comment by GabrielBrascher** [comment]
Thanks for the hint, @shwstppr.

I am not sure if #789 tackles this issue; from what I understood that PR deals only with stopped VMs being migrated on VMware clusters? Please correct me if I am wrong.

Adding a bit of information here, this issue was created due to tests on live migration of VMs running in KVM with local storage volumes; the migration itself worked fine, except by the fact of UI not dealing with the command response. The problem seems to be related to the UI not dealing with the expected response.

**Comment by davidjumani** [comment]
@GabrielBrascher Could you share a screenshot of the error? The form should be frozen while hitting the migrate API and then close since it is async and doesn't have to wait long. It might freeze if the API call returned an error which can be fixed

**Comment by rhtyd** [comment]
@GabrielBrascher can you check and close against next RC/master?

**Comment by GabrielBrascher** [comment]
Thanks @rhtyd and @davidjumani for the update, I will check against next master.

**Comment by rhtyd** [comment]
@GabrielBrascher we're going to cut RC4 later today/tomorrow, can you test before that for possible blockers?

**Comment by GabrielBrascher** [comment]
@rhtyd @davidjumani It still migrates succesfully on backend but keeps _locked_ on the migration screen with an error message.

![image](https://user-images.githubusercontent.com/5025148/103679756-04c0cc00-4f64-11eb-93cb-d8a16ec96d1c.png)

**Comment by rhtyd** [comment]
@davidjumani pl check on priority - did you PR introduce any regression?

**Comment by davidjumani** [comment]
@GabrielBrascher Could you send a screenshot of the API response? @rhtyd Think it might be because `migrateVirtualMachineWithVolume` was called instead of `migrateVirtualMachine` since while testing the previous PR there weren't any issues

**Comment by GabrielBrascher** [comment]
@davidjumani you are right, the command called is `migrateVirtualMachineWithVolume`; therefore, the response is `migratevirtualmachinewithvolumeresponse`.

**Comment by davidjumani** [comment]
@GabrielBrascher Could you try it with https://github.com/apache/cloudstack-primate/pull/913 ?

**Comment by GabrielBrascher** [comment]
Applying changes from #913 the message is `response.migratevirtualmachineresponse is undefined`

![image](https://user-images.githubusercontent.com/5025148/103697615-eb794900-4f7e-11eb-87ce-f28519c6f59f.png)

**Comment by davidjumani** [comment]
@GabrielBrascher Could you try checking again? It's working fine on my end for migrating with volumes as well

**Comment by GabrielBrascher** [comment]
@davidjumani re-packed my test env and now it works, you are right. Thanks!
