### ISSUE TITLE
[BUG] remove dependency on cloudstack-management

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack-primate#918]
**Describe the bug**

currently cloudstack-primate has dependency on cloudstack-management (4.15.0.0) which does not make sens.
It would be better if cloudstack-primate can be installed on any server.

**To Reproduce**

```
root@mgt01:~# dpkg -i cloudstack-primate_1.0.0-20210111-131647_all.deb
Selecting previously unselected package cloudstack-primate.
(Reading database ... 30773 files and directories currently installed.)
Preparing to unpack cloudstack-primate_1.0.0-20210111-131647_all.deb ...
Unpacking cloudstack-primate (1.0.0-20210111-131647) ...
dpkg: dependency problems prevent configuration of cloudstack-primate:
 cloudstack-primate depends on cloudstack-management (>= 4.15.0); however:
  Version of cloudstack-management on system is 4.14.0.0.

dpkg: error processing package cloudstack-primate (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 cloudstack-primate
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment]
@weizhouapache for this reason, we've already given advanced users to use the archive instead of rpm/deb, see: http://download.cloudstack.org/primate/4.15.0.0/archive/

Please review and close the issue

**Comment by weizhouapache** [comment]
@rhtyd 
thanks. closed this.

I saw packages on this page, good.
http://download.cloudstack.org/primate/testing/master/archive/
